### ISSUE TITLE
Sections layout

### ISSUE THREAD

**Issue by diegohaz** [reakit/reakit#138]
I'm not fully satisfied with the current sections layout. The menu seems weird. Its UX doesn't feel good.

I'll be implementing a new layout with the menu `fixed` (not `sticky`, like it's today) on the left side.

![img_2465](https://user-images.githubusercontent.com/3068563/42581430-19636c72-8503-11e8-995c-5efbe81400c7.JPG)

Ideas are welcome.

**Comment by wordofchristian** [comment]
When you say it will be fixed, do you mean neither it nor the top navigation bar will scroll with the page?

Best,

Christian Schlensker

**Comment by diegohaz** [comment]
@wordofchristian Yes, like the mobile version (but always visible).
