### ISSUE TITLE
Typescript definitions

### ISSUE THREAD

**Issue by dicarlo2** [reakit/reakit#142]
I'd love to see official typescript definitions, preferably shipped with the package. 

Fully typing `as` will be tricky - I tried my hand at it with little success, but it felt like it should be possible.

**Comment by diegohaz** [comment]
The most effective way to include typings with this library would be actually building the library with them. Otherwise, they would eventually get out of sync.

I was planning to use flow here. Do you know if there's something that converts flow typings to typescript so we could ship both?

**Comment by wordofchristian** [comment]
Did you see this? https://github.com/joarwilk/flowgen, it seems to promise being able to generate flow type definitions from typescript. I haven't seen a whole lot to allow going the other direction. There is https://github.com/bcherny/flow-to-typescript but it is pre-alpha and seems to be designed for converting the source code, not for generating definition files.

**Comment by diegohaz** [comment]
Hmm, it seems that our best choice would be using TS.

What I love in Flow is the ability to incrementally apply it on the codebase without many changes. It's just two dependencies, and it works nice with babel.

I'm not sure if that's possible with TS. But if someone comes up with minimal changes on the build setup and a way to incrementally implement it on the code (e.g. starting with `utils` methods), I'd be happy to use it here.

**Comment by wordofchristian** [comment]
The integration story between babel and typescript seems to be getting better. It is possible to use typescript parser with babel, but requires using babel 7 which is still pre-release. There's an example repo here of how it can be done https://github.com/Microsoft/TypeScript-Babel-Starter. It might also be possible to use the [rollup plugin ](https://github.com/rollup/rollup-plugin-typescript) and run it before babel on TS and TSX files, but I'm not as familiar yet with rollup and how you chain plugins together.

**Comment by wordofchristian** [comment]
> I'm not sure if that's possible with TS. But if someone comes up with minimal changes on the build setup and a way to incrementally implement it on the code (e.g. starting with utils methods), I'd be happy to use it here.

I think the absolute minimum setup

**Comment by wordofchristian** [comment]
I can dig into this. I'll see if it's reasonable to do without upgrading to the babel 7 beta, but I think continuing to use babel would be best as I'm not sure if there is a `styled-components` plugin for typescript.

**Comment by diegohaz** [comment]
Great. :)
That's ok to upgrade babel too.

**Comment by dicarlo2** [comment]
> The most effective way to include typings with this library would be actually building the library with them. Otherwise, they would eventually get out of sync.

Agreed.

> I was planning to use flow here. Do you know if there's something that converts flow typings to typescript so we could ship both?

The conversion story for Flow -> Typescript and/or Typescript -> Flow is pretty poor - I wasn't able to find a tool that would accurately convert types in a reasonable way compared to hand written definitions.

> It is possible to use typescript parser with babel, but requires using babel 7 which is still pre-release.

From experience, there are some caveats to this:
1. Not all typescript features are implemented
2. New typescript features take time to be implemented
3. Typescript will generally emit cleaner code

As an example for 3 - all interfaces are converted to empty objects and end up in the final exported code. With that said, presumably tree shaking and/or minify would handle this.

In terms of the build pipeline - it really depends on what you're trying to export, but basically the possibilities are endless - just use typescript, typescript + babel, rollup + typescript + babel, webpack + typescript + babel, etc. etc. I'd be happy to help with this - I've been through a few iterations of build pipelines with https://github.com/neo-one-suite/neo-one from compiling just Flow, Flow + Typescript with rollup, just Typescript using gulp, and now Typescript + babel (for a few optimizations) with gulp.

**Comment by wordofchristian** [comment]
> In terms of the build pipeline - it really depends on what you're trying to export, but basically the possibilities are endless - just use typescript, typescript + babel, rollup + typescript + babel, webpack + typescript + babel, etc. etc. I'd be happy to help with this - I've been through a few iterations of build pipelines with https://github.com/neo-one-suite/neo-one from compiling just Flow, Flow + Typescript with rollup, just Typescript using gulp, and now Typescript + babel (for a few optimizations) with gulp.
@dicarlo2 

What approach did you take for combining flow and typescript? Have you found a good way to generate both definitions, or is the only good answer to write one or both by hand?

There's a WIP pr for typescript over at #146 so feedback would be welcome.

I feel like no matter how we do this we should be prioritizing typescript support over flow just based on my own personal perception of market share and community trends (it's hard to find real data on this).

**Comment by dicarlo2** [comment]
Yay, this is awesome!!!
