### ISSUE TITLE
Separate packages for themes

### ISSUE THREAD

**Issue by diegohaz** [reakit/reakit#154]
The main complaint I see regarding libraries like this is about the difficulty of customizing the style of the components, since you often have to reset many of them, and it turns out it would be easier to create from scratch.

On the other hand, libraries like `material-ui` are also very popular for providing an elegant look for people who don't want to deal with styles.

ReaKit stays in the middle, which can be bad. It's not stylized enough to please those who don't want to create styles, while others who want still have to reset a few things.

To address this problem, I'm thinking about removing all the unnecessary styles from the core package, like `background`s, `padding`s, `margin`s, `border`s etc., and creating separate packages for them. This means that those who want to customize everything will be able to plug their own theme into `Provider` without having to reset library specific styles, while others could just install a theme and use it.

This also means that some components, which are there only for styling purposes, like `Fit` and `Shadow`, will be removed. Others will be drastically cleaned up, like `Button`, which will, without any theme, resemble the browser's `<button>`. 

Some styling will still be needed, like transforms for transitions etc.

- [x] Turn the repository into a monorepo (#183).
- [x] Create `Provider` component (#184).
- [x] Remove styling-only components: `Box`, `Fit`, `Shadow`.
- [x] Extract unnecessary styles from the main package
- [x] Variables
- [x] Create another package for the styles called `reakit-theme-default`.

**Comment by wordofchristian** [comment]
This is an excellent idea. I know what initially drew me to this library was how un-opinionated it was about appearance. There should definitely be some kind of bare bones theme that gives you the very basics essentials of spacing and layout so you could actually build a website without customizing anything.

**Comment by diegohaz** [comment]
That's a great solution.

**Comment by renatorib** [comment]
Maybe the components like Shadow could still exist but respecting the shadows that come from the theme settings. Obviously if you use Shadow without a theme, it would appear blank.
Material-ui uses [Paper](https://material-ui.com/demos/paper/) with `elevation` prop, that corresponds to the shadow elevature.  There are 24 different levels (`elevation1`...`elevation24`) that you can override in the theme. [They are just props in theme obj context](https://github.com/mui-org/material-ui/blob/master/packages/material-ui/src/Paper/Paper.js#L9-L13)

**Comment by wordofchristian** [comment]
I think a lot of these decisions come down to a user's particular use cases and needs. 

I think there will be some users who want to use the core utility features of ReaKit such as `as` or `Base` but care less about the presentational ones because they have very specific presentational needs. Those users can just ignore the presentational components and just use the utility and functional components (e.g. Step and Hidden). 

I dislike the idea of the Shadow component having no appearance if no theme is included. That could be confusing for new users. I think the default happy path should be to have some kind of basic appearance. Maybe the basic default appearance is derived from a default theme, then there is a sepearate "blank slate" theme that removes all appearance and lets the user start from scratch.

**Comment by renatorib** [comment]
Agreed.

**Comment by xuopled** [comment]
It could be very nice to multiples themes, separted from the core feature.
```
 impost {ThemeProvider} from "styled-components"

const theme = {
   // styled-components basic theme key
   ... 
   // reakit theme key
}

<ThemeProvider theme={theme}>
...
</ThemeProvider>
```

> libraries like material-ui are also very popular for providing an elegant look for people who don't want to deal with styles.

True, I was looking for a library and I discover this one. But I'm afraid to use it from now if you plan to remove all styles in the near future

**Comment by wordofchristian** [comment]
> True, I was looking for a library and I discover this one. But I'm afraid to use it from now if you plan to remove all styles in the near future

Ne t'inquiète pas @xuopled

The the current styling would still be available. One likely way we might do this is to turn the current styles into the recommended basic them, or you can create your own, or use a third party theme.
