### ISSUE TITLE
Remove child components

### ISSUE THREAD

**Issue by diegohaz** [reakit/reakit#155]
When I was building this library, I wanted to use enhanced components for everything. That is, I didn't want to use `div`s, `li`s and other HTML elements at all.

But, in performance terms, using HTML elements directly will always be faster than using any React component. If we're rendering a big list of `List.Item`s, for example, the difference could be some dozens os milliseconds (or maybe hundreds if you're running it from an old smartphone).

So I'm thinking about deprecating/removing these components:
- `Table.*` (except `Table.Wrapper`)
- `List.Item`

Also, for other components, if you aren't using any feature of ReaKit, like `as`, inline styles, or default styles, it makes more sense to use the HTML element instead.

If they have styles, it should be added to the parent element:
```jsx
const List = styled(Base)`
  li {
    margin-bottom: 0.25em;
  }
`;
```

**Comment by Thomazella** [comment]
closed in #158
