### ISSUE TITLE
RFC: Form

### ISSUE THREAD

**Issue by diegohaz** [reakit/reakit#161]
I think ReaKit should provide a solution for every common UI problem. 

I know that this may be a bit too ambitious, specially when there're so many good libraries out there already solving the same problem (e.g. [Formik](https://github.com/jaredpalmer/formik) and [Final Form](https://github.com/final-form/react-final-form)).

However, I also see some advantages of having it included in this library:

- people already using ReaKit wouldn't need to waste time looking for other libraries;
- it would provide an API very similar to all other parts of ReaKit (`Form.Container`, `Form.Input` etc.), which means a lower learning curve for those already using ReaKit;
- and, of course, they will always have the option to use another library.

This is the very initial API I'm thinking about:

```jsx
const initialState = {
  values: {
    username: "",
    age: ""
  }
};

const actions = {
  submit: () => state => postAPI(state.values),
  validate: () => state => myValidateFn(state.values)
};

<Form.Container initialState={initialState} actions={actions}>
  {form => (
    <React.Fragment>
      <MyInput as={Form.Input} name="username" {...form} />
      <MyInput as={Form.Input} name="age" {...form} />
      <MyButton as={Form.Submit} {...form} />
    </React.Fragment>
  )}
</Form.Container>
```

**Comment by kevinwolfcr** [comment]
*imo*, this is outside of the scope of this library, which is to provide visual primitives to build websites.

What if a user wants to use another solution rather than the provided one?

**Comment by diegohaz** [comment]
Thanks for your feedback, @kevinwolfcr.

> imo, this is outside of the scope of this library, which is to provide visual primitives to build websites.

That's an interesting point to talk about. In the early days I used to call it a "component system" as opposed to "component library", because it was never just a collection of components.

I think "toolkit" is a good category to put it in for now. It provides "tools" for building UIs. Primitives, but not only visuals. After all, [containers](https://reakit.io/guide/state-containers) are renderless components and are an important part of this library.

My intent is that one could simply install `react`, `react-dom` and `reakit` (plus a builder, like Next.js, Parcel, CRA etc.) and create an app from zero to hero. No need to look for, choose and learn different libraries for every problem. 

I know that may be too ambitious, but I think that's achievable, specially if we use abstract third-party libraries underneath.

> What if a user wants to use another solution rather than the provided one?

That's ok. It will work seamlessly as it does now. 

This library is decoupled in a way so you can replace every single piece of it. As an example, you can replace containers by `redux`, `mobx` or any other state management library. Or you can use containers and replace the stateless components by `material-ui`.

**Comment by kevinwolfcr** [comment]
Ok. I see where you want to go. What I will recommend you, it's to keep the component system _unopinionated_ (as it does now, providing container components) and maybe extend it with addons, so if a user wants to install the full form, they can install a module named `@formik/form-helpers`, or something like that.

**Comment by lluia** [comment]
👍  I like the API and idea, as soons as there's always the choice to use this or some other library. 

Is there any plan to for example 🌳 shake `Form.Container` in case we ended up using another lib like **Formik** instead?

**Comment by diegohaz** [comment]
@lluia I think the API will be pretty similar to Formik, so it'll be easy to switch between both.

**Comment by PlayMa256** [comment]
If we compose this + step, we could also create a form wizard, which is very helpful. I had to create one and it was sort of hard at first. It is a common component in websites.

**Comment by renatorib** [comment]
I think submit should receive 2 arguments. `state` and `actions` (need to think about how not to collide the names :smile:) because we will need to pass functions that set, for example, loading indication. It's like FormikBag

```jsx
submit: () => async (state, actions) => {
  actions.setSubmitting(true)
  const res = await callApi('...')
  actions.setSubmitting(false)
  if (res.error) {
    // reporting error message in the UI will be made by throw or some action?
    // throw new Error() // or // return actions.setError()
  }
  // reporting sucess message in the UI will be made by some action or return?
  // actions.setSuccess()  // or // return 'Success'
}
```

I also think it might be worth creating a structure that is easy to put formik or final-form in, rather than creating an new API. For example, formik does not apply validation logics, however it makes it easy to use with Yup. It might be the best way for now. But if the idea is really to create an api, I want to be able to help, I like forms :)

**Comment by diegohaz** [comment]
Closing as this has been added in v1.
