### ISSUE TITLE
RFC: Page

### ISSUE THREAD

**Issue by diegohaz** [reakit/reakit#164]
Following #161, we should also have a simple routing solution built in the library.

I guess we can use https://github.com/ReactTraining/history, which is used by react-router.

This is my initial thoughts around the API (opinions are welcome):

Router:
```jsx
import createHistory from "history/createBrowserHistory"

const history = createHistory();

<Page.Container initialState={{ history }}>
  {page => (
    <Page path="/foo" {...page}>
      ...
    </Page>
    <Page match={h => h.location === "/foo"} {...page}>
      ...
    </Page>
  )}
</Page.Container>
```

Link:
```jsx
<Page.Container>
  {page => (
    <Page.Link href="/foo" {...page}>Link</Page.Link>
  )}
</Page.Container>
```

Usage with `Overlay`:

```jsx
<Page.Container>
  {page => (
    <Overlay fade expand as={Page} path="/foo" {...page} />
  )}
</Page.Container>
```

Usage with `Tabs`:

```jsx
<Page.Container>
  {page => (
    <div>
      <Tabs>
        <Tabs.Tab as={Page.Link} tab="tab1" href="/tab1" {...page}>Tab 1</Tabs.Tab>
        <Tabs.Tab as={Page.Link} tab="tab2" href="/tab2" {...page}>Tab 2</Tabs.Tab>
      </Tabs>
      <Tabs.Panel as={Page} tab="tab1" path="/tab1" {...page}>Panel 1</Tabs.Panel>
      <Tabs.Panel as={Page} tab="tab2" path="/tab2" {...page}>Panel 2</Tabs.Panel>
    </div>
  )}
</Page.Container>
```

**Comment by Andarist** [comment]
Personally I think if you want to include things like routing, forms and similar into this toolkit it would be far better to outsource them, become opinionated about "the stack" rather than reinventing those wheels.

**Comment by diegohaz** [comment]
I agree, @Andarist. Actually, I want to reuse as most of the core of those libraries as possible, but have a different API.

That's why I implemented popper on Popovers, but not react-popper. Maybe can use final-form (not react-final-form) in forms.

But I'm not sure routers would have a higher level abstraction other than the history library.

**Comment by sallespro** [comment]
Mr. Haz, very nice pra xuxu. i'm going in this direction https://github.com/c8r/x0#routing , maybe it interests you.

**Comment by allpwrfulroot** [comment]
My projects use Next.js, which has a completely different take on routing than React Router. Would rather the component library stay agnostic to routing ^_^;;

**Comment by diegohaz** [comment]
I think `Page` should be a [`Hidden`](https://reakit.io/components/hidden) component controlled by browser's history. That is, when the `path` prop matches against the current location, it turns on its `visible` prop.

This means that all `Hidden` derivate components, such as [`Popover`](https://reakit.io/components/popover), [`Overlay`](https://reakit.io/components/overlay) and any other created by the user, could be a "page". 

```jsx
<Page.Container>
  {page => (
    <Overlay fade expand as={Page} path="/foo" {...page} />
  )}
</Page.Container>
```

And yes, this also means page transitions out of the box.

@allpwrfulroot This would be optional, of course, and could be used together with other routing solutions.

**Comment by lluia** [comment]
> This means that all Hidden derivate components, such as Popover, Overlay and any other created by the user, could be a "page".

Not sure if `Page` would be a good name then, maybe something more abstract like `Content` ?

```jsx
<Content.Container>
  {content => (
    <Overlay fade expand as={Content} path="/foo" {...content} />
  )}
</Content.Container>
```

**Comment by enesTufekci** [comment]
[Reach Router](https://github.com/reach/router) has similar api. Maybe we can consider either use this directly or implement something similar?
