### ISSUE TITLE
Remove lodash dependency

### ISSUE THREAD

**Issue by diegohaz** [reakit/reakit#171]
Reference: https://github.com/reakit/reakit/pull/170#issuecomment-410509334

I think that's a good idea to remove the dependency on lodash and create util modules instead. We're currently using `kebabCase`, `uniq`, `uniqueId` and `omit`. We should create **one file per function** and test them.

An initial work was done by @Andarist here:
https://github.com/reakit/reakit/blob/f688d223bd8888691577b3a19ead02c475b75dab/src/utils/lodash-like.js#L1-L25

**Comment by Thomazella** [comment]
I'll add a benchmark too.

**Comment by Andarist** [comment]
Just a note - `omit` doesnt have to be implemented at all, in many cases you can just use object rest spread for that.

**Comment by Thomazella** [comment]
closed in #181
