### ISSUE TITLE
Add pre-commit hook for Prettier

### ISSUE THREAD

**Issue by diegohaz** [reakit/reakit#179]
Reference: https://github.com/reakit/reakit/pull/177#discussion_r208318143

**Comment by joao-alberto** [comment]
Can be done using 'husky' and 'pretty-quick' or do you preffer sh scripts as mentioned in discussion?

**Comment by diegohaz** [comment]
The [first option](https://prettier.io/docs/en/precommit.html#option-1-lint-staged-https-githubcom-okonet-lint-staged) seems to give us more control. I'd go for it.

**Comment by joao-alberto** [comment]
Oh yeah, I forgot about lint-staged, I'll do

**Comment by Thomazella** [comment]
Hope it works with lazy commit all on vscode :p
