### ISSUE TITLE
Rename Base to Box

### ISSUE THREAD

**Issue by diegohaz** [reakit/reakit#186]
With #154, we'll remove some components that are there only for styling purposes, like `Shadow` and `Box`.

`Base` is a really powerful component and should be used more often, specially for rapidly creating tiny styled components, like in [this example](https://codesandbox.io/s/lr73v99prq) by @renatorib.

That was the intent of "display" components like `Block` and `Flex`. However, it's not so easy to decide which one to use at the creation time (the moment you write `styled(Something)`). Often, I have to change it, which leads to a bad developer experience, in my opinion.

But I really don't like this name (`Base`). Looking for some patterns in related libraries, I've seen `Box` as a common name to represent a component that can receive style props and children:

- [styled-system](https://github.com/jxnblk/styled-system/tree/master/system-components#add-style-props-without-defaultprops)
- [jsxstyle](https://github.com/jsxstyle/jsxstyle#getting-started)
- [grid-styled](https://github.com/jxnblk/grid-styled#box-)

So, the intent of this issue is to propose renaming `Base` to `Box` when #154 lands. And, maybe, deprecating/removing the other primitive components in favor of shortcut props on `Box`:

```jsx
<Box block />
<Box inline />
<Box inlineBlock />
<Box flex row />
...
```

**Comment by renatorib** [comment]
I like the idea. My 50 cents:

I like doing it because sometimes I want a specific UI element without losing the benefits that reakit/Base offers (like `as`, shortcut props, etc.)
```jsx
const kinds = { self: blue, target: red }

export const Board = styled<{ kind: 'self' | 'target' }>(Base)`
  margin: 0 auto;
  background: ${props => kinds[props.kind]};
  width: 600px;
  height: 400px;
`;

<Board color="green" kind="target" />
```

But I think it can be more typescript-friendly something like a factory, since it's a common case. I may be wrong, or have done something wrong, but I've always had problems with component's props inference + custom props using typescript.

```jsx
const kinds = { self: blue, target: red }

export const Board = reakitBox<{ kind: 'self' | 'target' }>`
  margin: 0 auto;
  background: ${props => kinds[props.kind]};
  width: 600px;
  height: 400px;
`;

<Board color="green" kind="target" />
```

**Comment by diegohaz** [comment]
@renatorib This is how you should do it:
https://github.com/reakit/reakit/blob/85a03333c0a287c17305534da275215570c02329/packages/reakit/src/Arrow/Arrow.ts#L13

I'm not sure if it will infer `props` in interpolated functions (it should), but the final `Board` component will work as expected.

**Comment by renatorib** [comment]
Yeah, I forgot that now we can pass generics to tagged template directly. That's really nice.  
Anyway, have you ever had problems with inference? The times I got totally lost with this are countless.
