### ISSUE TITLE
RFC: Builder (or how to make a living from this project)

### ISSUE THREAD

**Issue by diegohaz** [reakit/reakit#191]
Hey! I'd like to share with you guys my thoughts on how I plan to make a living from this project. And, depending on how well things go, invite more people to join in.

Until a few months ago I was working for [a company](https://hellomd.com) based in San Francisco, CA. So I left my job there to dedicate myself full time to ReaKit. I had seen an opportunity that had not yet been explored (and not yet priced).

## Boilerplates

Some of my first open source projects were boilerplates and project generators. [ARc](https://github.com/diegohaz/arc) is the most successful one, followed by [rest](https://github.com/diegohaz/rest) and [nod](https://github.com/diegohaz/nod). I was so fond of creating boilerplates that I created [a boilerplate to create other boilerplates](https://github.com/diegohaz/yo). 😅

One thing I noticed is that, even though I stay a long time without updating the projects, they continue to receive many unique visitors daily. In fact, **no project of mine receives as many visitors as ARc and Rest**, not even the ones that have more stars. Even though the word *boilerplate* has been depreciated over time, people still have a demand for it.

The main advantage of boilerplates is that they usually come with handy pre-configured features like [social login](https://github.com/diegohaz/arc/blob/ed91161fe95283ecf63f321792403810a364b593/src-example/store/social/actions.js), [analytics](https://github.com/diegohaz/arc/blob/ed91161fe95283ecf63f321792403810a364b593/src-example/store/gtm/actions.js), [i18n](https://github.com/react-boilerplate/react-boilerplate/blob/master/app/i18n.js) and more.

On the other hand, some of the major complaints regarding boilerplates are:

1. it's very difficult to keep your project in sync with boilerplate updates;
2. either you end up with a lot more code and complexities than you really need;
3. or you'll have a lot of work to remove unnecessary stuff.

The first problem was solved by the modern frameworks and generators, such as [Next.js](https://github.com/zeit/next.js), [Gatsby](https://github.com/gatsbyjs/gatsby) and [Create React App](https://github.com/facebook/create-react-app). But they don't offer all the features boilerplates may have.

For the second one, on ARc, instead of pushing everything to the user at once, I've created an [example source folder](https://github.com/diegohaz/arc/tree/ed91161fe95283ecf63f321792403810a364b593/src-example) with all the custom features, and split the repository into some [feature branches](https://github.com/diegohaz/arc/tree/c35279360a674fd897a53d099500e731cb38f96a#branches). So they could "opt-in" for those features. That worked very well for not pushing unnecessary code to the user, but it has also come with a cost: it's very hard to maintain.

For the third problem, react-boilerplate, for example, provided [docs](https://github.com/react-boilerplate/react-boilerplate/blob/master/docs/general/remove.md) on how to remove some features. That's definitely better than letting the user figure it out by himself, but that's worse than letting him choose if he wants the feature at first place.

## ReaKit

ReaKit wasn't that ambitious at first. In fact, this is the result of [an old desire](https://github.com/diegohaz/arc/issues/35#issuecomment-268139291) to publish the [components](https://github.com/diegohaz/arc/tree/c35279360a674fd897a53d099500e731cb38f96a/src-example/components/atoms) I wrote for ARc.

This has grown and, at some point, [I realized that it needed some examples](https://github.com/reakit/reakit/issues/6) so people could have a better understanding on how to use it in real world projects. But, by my past experiences, I knew that those examples would eventually be used as boilerplates/starter projects with all their inherent flaws and qualities.

Why not, then, giving the user the pieces and letting him generate his own starter project that also works as an example of the library?

## Builder

How long does it take you to set up a project with everything you know you'll need up front? A few hours? Days?

<br>

|   |   |   |   |   |
|:-:|:-:|:-:|:-:|:-:|
| Next.js | Gatsby | Create React App | TypeScript | GraphQL |
| CRUD | Monorepo | Password login | Social login | Forgot password | Profile page |
| Blog | Internationalization | Search | Notifications | Chat |
| Messages | Forms | Newsletter registration | Product catalog | Administration |
| Charts | Wordpress integration | Payments | Markdown pages | 404 page |
|   |   |   |   |   |

<br>

The goal is to let the user choose between multiple technologies and features - some free, some premium -, see and use it in real time. And, finally, download it as a starter/skeleton project built with ReaKit.

<br>

![img_2524](https://user-images.githubusercontent.com/3068563/44100512-9f8fa54a-9fbb-11e8-8e3d-a7b2eadb3758.jpg)

<br>

I really want to ship this by the end of the year. I would really appreciate your feedbacks. :)

**Comment by Thomazella** [comment]
I'd focus on figuring out who the public is, and market the hell out of it. "Bolierplate tools"

**Comment by diegohaz** [comment]
@dicarlo2 That's interesting. Thank you for bringing it. :)

It somehow reminds me of Meteor. I'll take a closer look later.

**Comment by lluia** [comment]
@diegohaz interesting, would that _"bolierplate tool"_ be more interesting not being tied to **Reakit** but rather having it as a _feature_? 

Thinking from the point of view that, if you want to make a leaving out of it you'll need to broeaden its user base and tying it to **Reakit** ties it to its userbase ( .i.e I'm interested on this tool but to generate a bolierplate without **Reakit** as I'm not on the styled components 🚚 )

**Comment by diegohaz** [comment]
@lluia We'll need to create some UI for some features, so initially it'll be developed only with Reakit, but nothing stops us to build other versions, since it'll be really modular.
