### ISSUE TITLE
Popover example #1 could be more clear

### ISSUE THREAD

**Issue by Slapbox** [reakit/reakit#204]
https://reakit.io/components/popover

![image](https://user-images.githubusercontent.com/6835891/44482423-42805c80-a616-11e8-9b4f-e6d801c252cc.png)

Clicking this button doesn't do anything. The white box that says "Popover" is there no matter what. I assume this is supposed to be the popover.

**Comment by Slapbox** [comment]
Okay so it does work, but it's kind of misleading at first. I expected the button to do something in this example.

**Comment by diegohaz** [comment]
Hey, @Slapbox. It was a "static" example. You should toggle the `visible` prop in order to control it.

But I agree it may not be clear enough. Would you mind sending a PR?

**Comment by Slapbox** [comment]
@diegohaz I'm just starting out using this library and not 100% sure if this is what you mean, but I submitted a simple PR.

https://github.com/reakit/reakit/pull/206
