### ISSUE TITLE
Explanations of 'Fade', 'Slide', and 'Expand' ?

### ISSUE THREAD

**Issue by Slapbox** [reakit/reakit#207]
What exactly to the `fade`, `slide`, and `expand` do in Popovers?

I'm not seeing any difference in the entrance/exit of the popover with any combination, or lack-thereof, of these properties.

**Comment by Slapbox** [comment]
```js
<Popover
      placement="left-end"
      flip="false"
      fade="false"
      slide="false"
      expand="false"
      animated="false"
      duration="1000ms"
      hideOnClickOutside
      style={{ zIndex: 10000 }}
      {...popover}
>
</Popover>
```

No matter what options I pass, I can't get rid of the bounce effect on entrance of the popover, except for setting duration to `0ms` which is an unpleasantly sudden entrance.

**Comment by Slapbox** [comment]
I've tried passing false as a string and a bool, and while the effects vary, it always animates unless duration is explicitly set to `0ms`

**Comment by diegohaz** [comment]
@Slapbox Try to use `timing="ease"`.

`fade`, `slide` and `expand` only change the animation type, not the timing function.

**Comment by diegohaz** [comment]
Closing this for now. Let us know if you have more problems. You can also use our [Spectrum community](https://spectrum.chat/reakit) or [Slack channel](https://join.slack.com/t/reakit/shared_invite/enQtNDExMDcwNTk2MTMwLWI1Mzk1Y2YzMTAzZGUyMGIzMjQxZGU4OGM3MDI0OTcyYWU0NzZjZmIxNDcxZTVlODZiODA3YjE5N2FiOWMxZWQ). Those are more suitable for support questions.

**Comment by Slapbox** [comment]
Ah awesome I didn't know there was a Slack channel. You should definitely mention that on the main page of the repo.

That being said, I'm not clear on how the `expand` animation is supposed to work. I also saw, when toggling a bit faster than the animations, a rotating/flipping in effect. I'm not clear if that's from the `flip` property, or if `flip` is something else. A page with definitions for these would go a long way.
