### ISSUE TITLE
Use prop function in theme provider

### ISSUE THREAD

**Issue by IniZio** [reakit/reakit#211]
I tried to use prop function in theme
```js
const theme = {
  Base: `
    font-family: 'Roboto';
    background-color: ${prop(`theme.colors.${prop('backgroundColor')}`, prop('backgroundColor'))};
    color: ${prop(`theme.colors.${prop('color')}`, prop('color'))};
  `
}
```

But it doesn't work, not really sure if there is a workaround or cannot be used like that? :thinking:

**Comment by diegohaz** [comment]
Hi, @IniZio.

This is related more to https://github.com/diegohaz/styled-tools than to ReaKit.

But I think the issue is the way you're using it. `theme.colors.${prop('color')}` will result in something like `theme.colors.[Function]`, which is obviously not what you want.

You can try this:

```js
const theme = {
  Base: `
    font-family: 'Roboto';
    background-color: ${withProp('backgroundColor', bg => prop(`theme.colors.${bg}`, bg))};
    color: ${withProp('color', color => prop(`theme.colors.${color}`, color))};
  `
}
```

**Comment by IniZio** [comment]
Sorry, also I should have asked in chat instead.... thanks :joy:
