### ISSUE TITLE
Reakit crashes to React ErrorBoundary in Production only due to Styled-Components failure

### ISSUE THREAD

**Issue by Slapbox** [reakit/reakit#213]
Styled-Components fails when `NODE_ENV=production` for some reason, for some people. There's a bug about it here: https://github.com/styled-components/styled-components/issues/1610

The specific error is: https://github.com/styled-components/styled-components/blob/master/src/utils/errors.md#10

I know this isn't necessarily the problem of Reakit maintainers, but I wanted to bring it to your attention. Reakit is proving unusable for me in production unfortunately.

Reakit versions `0.14.3` and `0.14.4`

**Comment by diegohaz** [comment]
Hey, @Slapbox. I've never seen that before. We're running our website (https://reakit.io) in production without problems.

Could you provide a way to reproduce the error? Maybe a small repository.

**Comment by Slapbox** [comment]
I'll certainly try, but I'm not confident in my ability to reproduce this in a share-able repo since styled-components is widely used and this bug seems to be reported very rarely.

In the meantime, this is the full extent of my usage of Reakit currently:

```js
import { Base, Block, Button, InlineBlock, Popover } from 'reakit';
       <MyWrappingComponent>
          <Popover.Container>
            {popover => (
              <Block relative>
                <Base
                  as={Popover.Toggle}
                  aria-hidden="true"
                  className="fa fa-list-alt noteInfo"
                  title="View Note Info"
                  {...popover}
                />
                <Popover
                  duration="250ms"
                  expand={false}
                  fade
                  flip={false}
                  hideOnClickOutside
                  placement="left-end"
                  slide="left"
                  style={{
                    padding: 0,
                    zIndex: 10000
                  }}
                  {...popover}
                >
                  <Popover.Arrow />
                  <ErrorBoundary>
                    <MyComponent />
                  </ErrorBoundary>
                </Popover>
              </Block>
            )}
          </Popover.Container>
       </MyWrappingComponent>
```

**Comment by Slapbox** [comment]
I ended up restructuring my entry point pretty much completely to remedy this. I'm not sure I can give any actionable advice to anyone to fix this. I moved my `require` statements to the very last thing to execute on startup, which may be the thing that did the trick.
