### ISSUE TITLE
Converting all components to Typescript

### ISSUE THREAD

**Issue by ewgenius** [reakit/reakit#219]
Basing on #142 and some recent changes, it seems that Typescript is selected for this project, but typings applied only to a couple of components. Are there any plans to add types for the rest components?

I'm looking for an opportunity to contribute 🙂 

Current status:

| Component | Status | Developer |
|-|-|-|
| Popover | In Progress | @ewgenius |
| Tooltip | (depends on Popover) | @ewgenius |

**Comment by ewgenius** [comment]
@diegohaz awesome! I will start from `Backdrop` component. Is there any place to track type coverage progress (if not, maybe we can do this in this issue)?

Also maybe it makes sense to update this part as well to encourage new contributions to be typed as well https://github.com/reakit/reakit/blob/master/CONTRIBUTING.md#creating-components?

**Comment by diegohaz** [comment]
We can use this issue to track typing progress on components. 👍

And, yes, CONTRIBUTING.md needs to be updated. Would you like to take this too?

**Comment by ewgenius** [comment]
Yes, I can take this 👍

**Comment by Thomazella** [comment]
I wanted to hit 👍🏻 but hit 👎🏻 accidentally. I think this is a great issue and we should get it done, I'll help if I can. 😆

**Comment by enesTufekci** [comment]
@ewgenius @diegohaz is the progress table up to date? I can help with this.

**Comment by ewgenius** [comment]
@enesTufekci just updated with `Hidden` PR completion. I think you can take any component in work 👍

**Comment by renatorib** [comment]
I picked `Group` components, https://github.com/reakit/reakit/pull/251

**Comment by Thomazella** [comment]
popover and tooltip are now free to take as I'm busy :/

**Comment by ewgenius** [comment]
Taking Popover in work

**Comment by ewgenius** [comment]
@diegohaz #262 seems to be the last components to update - is there anything else we need to convert?

**Comment by diegohaz** [comment]
DONE! 🎉

Thank you, guys. I'm gonna review everything to find any missing bugs, cut a release and prepare an announcement for this week or the next. 

I'll mention you guys in the newsletter if you don't mind. :)

**Comment by Thomazella** [comment]
@PlayMa256 @renatorib Done guys! @ewgenius Thanks for your many contributions :)

**Comment by PlayMa256** [comment]
Yeeeeee we did itttt
