### ISSUE TITLE
Incompatibility with `as` prop in styled-components v4 (RFC)

### ISSUE THREAD

**Issue by wordofchristian** [reakit/reakit#226]
## Background
styled-components [just released V4](https://medium.com/styled-components/announcing-styled-components-v4-better-faster-stronger-3fe1aba1a112) bringing a lot of great new features 🎉 

However, among these new features they added their own [polymorphic `as` prop](https://www.styled-components.com/docs/api#as-polymorphic-prop) that looks very similar to [the one in reakit](https://reakit.io/guide/as), but they behave in subtly different and incompatible ways. 

The `as` prop provided by components in reakit allow you compose together the behaviors of several components at once:

```jsx
import { Button } from 'reakit';
import styled from 'styled-components';

const MyButton = styled(Button)`
  background-color: red;
`

<MyButton as="a">Hello</MyButton>

// renders <a role="button" tabindex="0">Hello</a>
```

In this example the resulting HTML is an a tag with all the attributes of the `Button` component.

Compare that to when you use the `as` prop from a styled-components component it will replace which component is rendered rather than composing them.

So in the example above, the `Button` component would get ignored resulting in:

```jsx
<a>Hello</a>
```

## Problem

his presents a legitimate compatibility problem for reakit going forward. Additionally it presents a lot of possible confusion for newcomers. It would likely and totally understandable if when people see the reakit `as` prop, they would just assumed it would work like the native styled-components prop.

## Possible solution

Rename the reakit prop to something else.

A couple proposed options are:

- `with`
- `uses`
- `use`
- `compose`

I think this would clear up any possible confusion and also is a better description of how the prop behaves, given that it can also take an array of components:

```jsx
<MyComponent with={[Button, "a"]}>Hello</MyComponent>
<MyComponent uses={[Button, "a"]}>Hello</MyComponent>
<MyComponent use={[Button, "a"]}>Hello</MyComponent>
<MyComponent compose={[Button, "a"]}>Hello</MyComponent>
```

The enhancer should also be renamed:

```js
composeWith([Button, "a"])(MyComponent) // with is a reserved word
uses([Button, "a"])(MyComponent)
use([Button, "a"])(MyComponent)
compose([Button, "a"])(MyComponent)
```

Other ideas welcome:

Please respond with any other ideas for solutions or general thoughts on this proposal.

**Comment by PlayMa256** [comment]
+1 for `Uses` which seems to be much similar to what `as` does here and from an user POV, makes much more sense.

**Comment by Thomazella** [comment]
I agree a rename makes sense, I'd be fine with anything expect `compose` (too long) :)

**Comment by wordofchristian** [comment]
It seems like `uses` is the way to go given that `with` is a reserved word and `compose` is too long. 

I like `uses` more than `use` because it seems more declarative while the latter is more imperative.

**Comment by diegohaz** [comment]
I also agree with `use`/`uses`.

Do you guys think `uses` sounds better even on the method forms?
```jsx
<Button uses="a" />
Button.uses("a");
uses("a")(Button);
```
vs.
```jsx
<Button use="a" />
Button.use("a");
use("a")(Button);
```

**Comment by diegohaz** [comment]
The more I think about it, the more I like `with` 😄

It seems that React will soon adopt reserved keywords as props, like `class` and `for`, so maybe we don't need to worry too much about using `with` as a prop.
https://github.com/facebook/react/issues/13525

We just can't use `with` as a standalone method.

Now I'm thinking about this API:
```jsx
combineWith([Button, "a"])(MyComponent);
MyComponent.with([Button, "a"]);
<MyComponent with={[Button, "a"]} />;
```

**Comment by xuopled** [comment]
It seems not published yet. I can't make it work with `styled-components` v4

**Comment by PlayMa256** [comment]
Not yet, it was merged into next not master. Haz is finishing up some final touches until we can release this with all the confidence. Also i'm finishing up a codemod which will automate most of the refactor needed.
