### ISSUE TITLE
Create a guideline for typings

### ISSUE THREAD

**Issue by PlayMa256** [reakit/reakit#229]
As we are moving towards full `typescript`, would be good to set some guidelines of "best" practices, or at least what we think that is good/readable. This will help during the conversion of all the components to TS and also when new components are created.

I'm leaving as an inspiration, the bare-bone that webpack had created when they started to add types to their codebase, it think that it is such a good start.

https://github.com/webpack/webpack/issues/7122

What are your thoughts about it? Let's discuss!!

---
### Guidelines so far: 

When you have scenarios like: 
```js
const C = Card as typeof Card & CardComponents;

C.Fit = CardFit;

export * from "./Card";

export default C;
```
It is prefered to use the following:

```js
export * from "./Card";
export * from "./CardFit";

export default Object.assign(Card, {
  Fit: CardFit
});

```

- Always export prop types:
    ```ts
    export interface DividerProps {
      vertical?: boolean;
    }
    ```

- Always export `default` and `*` from component files (that will export types):

    ```ts
    import Divider from "./Divider";
    export * from "./Divider";
    export default Divider;
    ```

- If it's a component that renders another component (wrapper), we must extend props interface:
    ```tsx
    import Box, { BoxProps } from "../Box";

    export interface DividerProps extends BoxProps {
      vertical?: boolean;
    }

    const DividerComponent = (props: DividerProps) => <Box {...props} />;
    ```

When you have: `const component = (props: CodeProps) => ....`

Turn into: `const CodeComponent = (props: CodeProps) => ...`

**Comment by Thomazella** [comment]
I like the idea of improving the codebase but I'm getting started with TS and jsdoc, so my contribution to the discussion will be mostly motivational :)

**Comment by Thomazella** [comment]
patterns such
```
const C = Card as typeof Card & CardComponents;

C.Fit = CardFit;

export * from "./Card";

export default C;
```
Do we keep it or prefer something more descriptive? `TypedCard` I'd say I prefer the long name.

**Comment by PlayMa256** [comment]
+1 for Longer name too. `Typed(Something)`

**Comment by diegohaz** [comment]
I agree. I didn't think much about this when I was coding it. XD

**Comment by PlayMa256** [comment]
I'll edit the main post, to reflect what is being discussed. Then at the end we can create a real guideline

**Comment by Thomazella** [comment]
perhaps something about type x interface?
always export the types from the files its defined in?

**Comment by codyaverett** [comment]
If you all didn't already know, @Hotell created some awesome and extremely detailed React + Typescript guides.  I highly recommend giving them a read.
https://medium.com/@martin_hotell

**Comment by renatorib** [comment]
What about? https://github.com/reakit/reakit/pull/252

**Comment by PlayMa256** [comment]
Also would be good to add that, some components  had a functional component called just `Component`, it is better to put a proper name to it, i.e:

```
const component = (props: CodeProps) => ....
```

Turn into:

`const CodeComponent = (props: CodeProps) => ...`

**Comment by PlayMa256** [comment]
I guess we are good to have a proper document now. I'll create that!

**Comment by jpdesigndev** [comment]
Is anyone else having issues with Typescript 3+ and `<Flex wrap />`. There seem to be some incompatibilities I can't overcome.

**Comment by diegohaz** [comment]
@jpdesigndev Is this happening with `reakit@0.15.5`? Could copy and paste the error message here?

**Comment by jpdesigndev** [comment]
@diegohaz Yes, see edit ^. Let me know if more context would help.

**Comment by diegohaz** [comment]
Ok, I identified the problem. Working on a fix. Thanks for reporting it. :)

**Comment by jpdesigndev** [comment]
Wow, that was fast. I'm brand new to TS. Otherwise, I may be more useful. Thanks for looking into this so quickly.
