### ISSUE TITLE
More component examples

### ISSUE THREAD

**Issue by diegohaz** [reakit/reakit#258]
I'd like to provide more examples of components – specially, but not only, containers – in the docs.

If you have ideas or demands on your project, please leave a comment here. We'll code the most upvoted ones. 👍

**Comment by diegohaz** [comment]
**Step/Tabs transitions**

When the user goes to the next step, the current step slides to the left and hide, then the next step slides from the right side, like a Carousel.

**Comment by diegohaz** [comment]
Feedback by @hnordt:

**More real world examples**

In our home page, we have a simple example of Popover. I think we can make it look more like a real app with Sidebar, Toolbar, Avatar, Heading etc. and show the code of each part in tabs (highlighting the preview area for the current code).

**Comment by merriam** [comment]
It would be grand if we had a place to put CodePen or equivalent links for the examples.  Even looking at the first pages (Composition), I find it difficult to run the examples.

- The snippets are evocative and concise, which is what I want if I grok the fundamental usage.  Until then, I need to see the `<Provider theme={theme}>` tag, which would be shown in a running CodePen example.
- Its unclear if the examples are wrong when they are challenges for me.  For example, the page shows `use()` exported directly from reakit, but that fails for me. I would know if the challenge was in the documentation, the import statements, the scaffolding, or the bear-of-little-brain.

Perhaps a top level `/samples` directory and we can add links to the docs?  Having even one 'monster' per chapter where all the functions are shown would help.  There is a little research in having CodePen automatically pull from the repo; if build one the community will provide.
