### ISSUE TITLE
Docs subtitles should have anchors

### ISSUE THREAD

**Issue by diegohaz** [reakit/reakit#260]
Just like on GitHub READMEs, section subtitles should display a symbol (maybe a pink hash) with a link to that part when the title is hovered. 

It's already passed to the `h2` as an `id`:

![image](https://user-images.githubusercontent.com/3068563/46251534-5c8a3780-c42b-11e8-8d25-b078dd6e5b9e.png)

I think we should grab that ID and pass it to an anchor instead.

This is the relevant part on the code:
https://github.com/reakit/reakit/blob/e1fe327766e78eee7a5d8565bcf4047f00e22b57/packages/website/src/components/Markdown.js#L28-L33

**Comment by kraigh** [comment]
I'm learning React and would like to try to help with this, trying to understand how its working and what the best approach is.

So, in Markdown.js you're converting the markdown for each documentation page into JSX on line 104:

`const Markdown = ({ text }) => compiler(text, { overrides, forceBlock: true });`

In the lines above, you create some custom styled components like `const StyledHeading = styled(Heading)` where you provide some override styles. There's also a custom `Anchor` component which includes a link and an icon.

Right before compiling the markdown, you provide the component each markdown element should render as, like `h1: asComponent(StyledHeading, "h1"),`

I'm assuming the `id` in the heading comes from a prop, probably calculated by the <Heading> component in Reakit.

I'm trying to think through how to do this- i'm thinking maybe more explicitly create the `<Heading>` component for H2s and maybe add a `<Link>` or `<Anchor>` inside it. The Anchor component already in that file could be used, I think?

So maybe in addition to `const StyledHeading = styled(Heading)` do something like:

```const LinkedHeading = {
    return(
        <Heading>
            <Link href=SOMETHING /> // Get the href from a prop from the Heading?
            {props.children} // Is this correct to get the Heading content??
        </Heading>
    );
}
```

Obviously with some additional props and stuff, just trying to get a sense of what to do. Also style information would need to be added somewhere.

Then, assuming all H2s should include the links, do something like `h2: asComponent(LinkedHeading, "h2"),`

Am I on the right track?

**Comment by diegohaz** [comment]
You're on the right path, @kraigh.

The #title-id will be passed to your `LinkedHeading` component if you pass `LinkedHeading` instead of `StyledHeading` in the overrides:
https://github.com/reakit/reakit/blob/c831afc53290aa666869f0926ccee3762dc74960/packages/website/src/components/Markdown.js#L96-L101

**Comment by diegohaz** [comment]
Done in https://next.reakit.io
