### ISSUE TITLE
"Unexpected" filter hotkey experience on Reakit's website

### ISSUE THREAD

**Issue by codyaverett** [reakit/reakit#263]
# Bug report

**What is the current behavior?**
On Reakit Website if you hit key `/` the filter input will take focus.  This hinders usage of the Component example playground components.

**If the current behavior is a bug, please provide the steps to reproduce.**
Hit the `/` key anywhere on the site.  It kinda surprised me that we could filter like that on the site, the input focus box didn't exactly grab my attention until I hit the `/` key a bunch and looked around for a bit.

![reakitplaygroundsadtimes gif](https://user-images.githubusercontent.com/3270702/46443004-5351e100-c731-11e8-9989-a016a26dd96c.gif)

**What is the expected behavior?**

I think the `/` key should not focus while we are typing in playground textboxes, otherwise we can't easily code out any simple thoughts or examples into the component playground boxes.

Another option could be to make it a multi-key hotkey.

I'd expect to see something when a hotkey is activated.
Storybook has a popup modal for example: 
![Storybook hotkey popup example](https://user-images.githubusercontent.com/3270702/46443248-48e41700-c732-11e8-869a-c1b92a2ed533.png)

There already is next component/previous article button at the bottom of each page, so it may not be too much of a stretch to have hotkeys for these as well.
![reakit next and previous article buttons](https://user-images.githubusercontent.com/3270702/46443315-9791b100-c732-11e8-9d6c-dca208317d24.png)

Thoughts?

**Other relevant information:**
reakit version:  0.15.4

**Comment by Thomazella** [comment]
*facepalm* Thanks cody!

**Comment by PlayMa256** [comment]
Thank you for the report! We are going to work on a fix for that! 
Thomazella pointed me to where it is happening, I'll open a pr fixing it!

Issued like this are what makes our docs even better!!,

**Comment by codyaverett** [comment]
Np @Thomazella, I quite like the idea of having hotkeys on the site.
Sounds good! Thanks @PlayMa256 👍
