### ISSUE TITLE
Typings: Group component props not optional as documented

### ISSUE THREAD

**Issue by codyaverett** [reakit/reakit#268]
# Bug report

**What is the current behavior?**
Typings for <Group> component expect `vertical` and `verticalAt` to be defined.

![image](https://user-images.githubusercontent.com/3270702/46695112-3fe0c300-cbd4-11e8-93ff-f51130377522.png)

![image](https://user-images.githubusercontent.com/3270702/46695077-26d81200-cbd4-11e8-8e6d-c9aafcafd2d0.png)

Works if both `vertical` and `verticalAt` are defined.

![image](https://user-images.githubusercontent.com/3270702/46695035-08721680-cbd4-11e8-83e8-325595c20ff5.png)

**If the current behavior is a bug, please provide the steps to reproduce.**
Typescript project using Group tag without any props will trigger typings error.

**What is the expected behavior?**
Does not work as documented. https://reakit.io/components/group

I was expecting to not need props.

**Other relevant information:**
reakit version: 0.15.5
typescript verison: 3.0.3

**Comment by diegohaz** [comment]
Thanks for reporting it, Cody. It should be fixed in `v0.15.6`. Could you try it?
