### ISSUE TITLE
Improved theming capabilities

### ISSUE THREAD

**Issue by dennari** [reakit/reakit#270]
I've been looking around for a React UI library implemented with TypeScript and using styled-components. Reakit fits the bill (nice job!), but there's obviously still a lot to be done.

One of the first things I was missing was configurable but consistent white space. What I mean is that currently the paddings and margins seem to be hardcoded in to the theme. Btw I think it's great that the theming part seems to be nicely decoupled.

Perhaps it would be worthwhile to follow some existing efforts on this front. For example Smooth-UI, another project I checked out (but completely lacking in the TypeScript department), has this: https://github.com/smooth-code/smooth-ui/blob/master/packages/shared/core/theme.js.

I'd be interested in discussing this further and perhaps helping out.

**Comment by Thomazella** [comment]
That's a really good suggestion @dennari ! Theming just landed recently and we're going to expand it and improve it :)

**Comment by diegohaz** [comment]
Thanks for the feedback, @dennari.

This can be easily done in a custom theme:

```js
import { css } from "reakit";
import { theme as th } from "styled-tools";
// if you want to extend from default theme
import defaultTheme from "reakit-theme-default";

const theme = {
  ...defaultTheme,
  spaces: [0, "8px", "16px", "24px", "32px", "40px"],

  Button: css`
    ${defaultTheme.Button};
    padding: ${th("spaces", 3)}; // 24px
  `
};
```

Theme abstractions are hard thing. The current [palette](https://github.com/diegohaz/styled-tools#palette) abstraction is the result of two years of experiments (mostly with [styled-theme](https://github.com/diegohaz/styled-theme) and [styled-tools](https://github.com/diegohaz/styled-tools)). 

The theme solution we adopt here is generic enough so people can create abstractions on it. I'd like to see what people do before introducing them to the library.

**Comment by PlayMa256** [comment]
Just complementing what haz has said:

What do you think you cannot do with the current theming capabiltiies? And what do you would like to be able to?

**Comment by dennari** [comment]
Thanks for getting back so quickly. I definitely agree that theme abstractions are hard to get right.

> What do you think you cannot do with the current theming capabiltiies? And what do you would like to be able to?

Looking at @diegohaz's example code and the theming guide, it looks like the theming system itself is more than capable. Probably for me it would've been enough just to have a more complete default theme to build upon. Or an example project which looks great and I could use as a base.

**Comment by Thomazella** [comment]
We plan on adding one :) `reakit-theme-material` or something like that. For the default one we went full bare-bones though. 🤔 But if you have any problems using it, we can help.

**Comment by PlayMa256** [comment]
> Probably for me it would've been enough just to have a more complete default theme to build upon. Or an example project which looks great and I could use as a base.

A more complete is kind of hard to do, since "complete" is subjective for people. What we can do is improve the docs adding a project example on how to theme, where people can run and experiment, specially with codesandbox it can be done so fast.

**Comment by dennari** [comment]
You guys are fast 😄. Having example projects and additional themes sounds exactly right! I only now looked at the website code and realized I should've done that way earlier as it's a nice example of a complete and polished project.

**Comment by dennari** [comment]
How should I approach this: let's say I want to have a button with different variants, let's say `minimal` for example. I only need to change the padding. How could I reference a prop of the button in the theme code? Or is this definitely something that is done in the component code itself?

**Comment by Thomazella** [comment]
```
// minimal button
import {styled, button} from 'reakit';

const MinimalButton = styled(Button)`
    padding: ${props => props.theme.padding.zero}
`;

export default MinimalButton;

```

```
// other button
import {styled, button} from 'reakit';

const OtherButton = styled(Button)`
    padding: ${props => props.theme.padding[2]}
`;

```

**Comment by diegohaz** [comment]
@dennari
> How could I reference a prop of the button in the theme code?

You can use interpolated functions like this:
```js
import { css } from "reakit";

const theme = {
  Button: css`
    padding: ${props => props.variant === "minimal" ? props.theme.padding[0] : props.theme.padding[2]};
  `
};
```

Or using [styled-tools](https://github.com/diegohaz/styled-tools):
```js
import { css } from "reakit";
import { ifProp, theme } from "styled-tools";

const theme = {
  Button: css`
    padding: ${ifProp({ variant: "minimal" }, theme("padding.0"), theme("padding.2"))};
  `
};
```

**Comment by Grsmto** [comment]
A good pattern for theming is one thing I'm really looking for as well. Like the scaling spacing example you just pasted is something that would help a lot imo.

it seems like you guys are not using abstractions like [Styled System](https://github.com/jxnblk/styled-system) on purpose. It would be really interesting to know why and what are the pros/cons to maybe extract some kind of theming good practices for this?

**Comment by Slapbox** [comment]
Is there any more reading on how to use `styled-tool`'s `palette`? 

It makes absolutely no sense to me at all to define an array of unlabeled colors instead of a single color. Can anyone shed some light on that?

**Comment by diegohaz** [comment]
@Slapbox 
The best documentation is on `styled-tools`' README: https://github.com/diegohaz/styled-tools#palette

The array is for shades. If it were labeled, it would be something like this:

```js
const palette = {
  gray: {
    darkest: "#000",
    darker: "#333",
    dark: "#666",
    medium: "#999",
    light: "#bbb",
    lighter: "#ddd",
    lightest: "#eee"
  }
}
```

Using array scales better in my opinion, but you can use labels as well if you prefer.

**Comment by Slapbox** [comment]
@diegohaz thanks a lot for that! It makes a bit of sense why you'd prefer the array method now after taking a somewhat long look at the example. I think the benefit isn't obvious at first glance due to the fact that the color values aren't visible as colors, and the otherwise innocuous array usage examples add to the confusion in this weird case.

This is what made the benefit obvious,
![image](https://user-images.githubusercontent.com/6835891/53704600-095a4d80-3dec-11e9-85db-41421b334ab4.png)

```js
  color: ${palette("primary", -1)};        // props.theme.palette.primary[3]
  color: ${palette("primary", 10)};        // props.theme.palette.primary[3]
  color: ${palette("primary", -10)};       // props.theme.palette.primary[0]
```
