### ISSUE TITLE
Testing all components

### ISSUE THREAD

**Issue by diegohaz** [reakit/reakit#271]
In #241, we replaced [enzyme](https://github.com/airbnb/enzyme) by [react-testing-library](https://github.com/kentcdodds/react-testing-library) (RTL). 

Only a few components were being tested, so we decided to open it for contributions. Whether you're a beginner (with react, open source or tests) or an experienced developer who want to learn RTL by contributing to this project, this is for you. 😄

### Test cases

1️⃣ **html attrs**: test if a component renders html props (like `id`, `aria-label` etc.) - [example](https://github.com/reakit/reakit/blob/9018a8976e0b52edbe209a6dd7fd4c81d5f90eec/packages/reakit/src/Backdrop/__tests__/Backdrop-test.tsx#L12-L18)
2️⃣ **styled**:  test if styles match (for every prop that changes styles) - [example](https://github.com/reakit/reakit/blob/9018a8976e0b52edbe209a6dd7fd4c81d5f90eec/packages/reakit/src/Backdrop/__tests__/Backdrop-test.tsx#L20-L113)
3️⃣ **prop**: test the behavior of every custom prop - [example](https://github.com/reakit/reakit/blob/9018a8976e0b52edbe209a6dd7fd4c81d5f90eec/packages/reakit/src/Backdrop/__tests__/Backdrop-test.tsx#L5-L10)
4️⃣ **lifecycle**: test the behavior of lifecycles - [example1](https://github.com/reakit/reakit/blob/9018a8976e0b52edbe209a6dd7fd4c81d5f90eec/packages/reakit/src/Hidden/__tests__/Hidden-test.tsx#L11-L20), [example2](https://github.com/reakit/reakit/blob/9018a8976e0b52edbe209a6dd7fd4c81d5f90eec/packages/reakit/src/Step/__tests__/Step-test.tsx#L41-L45)
5️⃣ **events**: test the behavior of events - [example](https://github.com/reakit/reakit/blob/9018a8976e0b52edbe209a6dd7fd4c81d5f90eec/packages/reakit/src/Hidden/__tests__/Hidden-test.tsx#L22-L54)
6️⃣ **others**: more tests if the component needs

Components with only 1️⃣2️⃣ are easier.

### Instructions

1. Choose the component you want to test. Please, do one per PR. Components with sub components (e.g. `Group` and `GroupItem`) go in a single PR.
2. Comment on this issue (a member will edit this post with your info).
3. Take a look at [Contributing with code](https://github.com/reakit/reakit/blob/master/CONTRIBUTING.md#contributing-with-code).
4. Create a `__tests__` folder and a `${ComponentName}-test.tsx` file inside (you can take a look at other components that are already tested).
5. Implement the tests while running `yarn test --watch`.
6. Commit, push and open the PR. 🎉

### Components

| Component | Status | Developer | Test cases |
| - |:-:| - | - |
| [Avatar](/reakit/reakit/tree/master/packages/reakit/src/Avatar) | ✅ | @diegohaz | 1️⃣2️⃣ |
| [Backdrop](/reakit/reakit/tree/master/packages/reakit/src/Backdrop) | ✅ | @diegohaz | 1️⃣2️⃣3️⃣ |
| [Block](/reakit/reakit/tree/master/packages/reakit/src/Block) | ✅ | @diegohaz | 1️⃣2️⃣ |
| [Blockquote](/reakit/reakit/tree/master/packages/reakit/src/Blockquote) | ✅ | @codyaverett | 1️⃣2️⃣ |
| [Box](/reakit/reakit/tree/master/packages/reakit/src/Box) | ✅ | @ReutSher1 | 1️⃣2️⃣3️⃣ |
| [Button](/reakit/reakit/tree/master/packages/reakit/src/Button) | ✅ | @lluia | 1️⃣2️⃣ |
| [Card](/reakit/reakit/tree/master/packages/reakit/src/Card)* |  ✅ | @lluia | 1️⃣2️⃣3️⃣ |
| [Code](/reakit/reakit/tree/master/packages/reakit/src/Code) | ✅ | @lluia | 1️⃣2️⃣3️⃣ |
| [Divider](/reakit/reakit/tree/master/packages/reakit/src/Divider) | ✅ | @lluia | 1️⃣2️⃣3️⃣ |
| [Field](/reakit/reakit/tree/master/packages/reakit/src/Field) | ✅ | @lluia | 1️⃣2️⃣ |
| [Flex](/reakit/reakit/tree/master/packages/reakit/src/Flex) | ✅ | @lluia | 1️⃣2️⃣3️⃣ |
| [Grid](/reakit/reakit/tree/master/packages/reakit/src/Grid)* | ✅ | @lluia | 1️⃣2️⃣3️⃣ |
| [Group](/reakit/reakit/tree/master/packages/reakit/src/Group)* | ✅ | @lluia | 1️⃣2️⃣3️⃣ |
| [Heading](/reakit/reakit/tree/master/packages/reakit/src/Heading) | ✅ | @lluia | 1️⃣2️⃣ |
| [Hidden](/reakit/reakit/tree/master/packages/reakit/src/Hidden)* | 🚧 | @diegohaz | 1️⃣2️⃣3️⃣4️⃣5️⃣6️⃣ |
| [Image](/reakit/reakit/tree/master/packages/reakit/src/Image) | ✅ | @lluia | 1️⃣2️⃣ |
| [Inline](/reakit/reakit/tree/master/packages/reakit/src/Inline) | ✅ | @lluia | 1️⃣2️⃣ |
| [InlineBlock](/reakit/reakit/tree/master/packages/reakit/src/InlineBlock) | ✅ | @lluia | 1️⃣2️⃣ |
| [InlineFlex](/reakit/reakit/tree/master/packages/reakit/src/InlineFlex) | ✅ | @lluia | 1️⃣2️⃣3️⃣ |
| [Label](/reakit/reakit/tree/master/packages/reakit/src/Label) | 🚧 | @rafael-vitor | 1️⃣2️⃣ |
| [Link](/reakit/reakit/tree/master/packages/reakit/src/Link) | 🚧 | @rafael-vitor | 1️⃣2️⃣ |
| [List](/reakit/reakit/tree/master/packages/reakit/src/List) | 🚧 | @rafael-vitor | 1️⃣2️⃣ |
| [Navigation](/reakit/reakit/tree/master/packages/reakit/src/Navigation) | 🚧 | @rafael-vitor | 1️⃣2️⃣ |
| [Overlay](/reakit/reakit/tree/master/packages/reakit/src/Overlay)* | ✅ | @amogower  | 1️⃣2️⃣3️⃣4️⃣5️⃣6️⃣ |
| [Paragraph](/reakit/reakit/tree/master/packages/reakit/src/Paragraph) | ✅  |@lluia  | 1️⃣2️⃣ |
| [Popover](/reakit/reakit/tree/master/packages/reakit/src/Popover)* | ✅ | @amogower | 1️⃣2️⃣3️⃣4️⃣5️⃣6️⃣ |
| [Portal](/reakit/reakit/tree/master/packages/reakit/src/Portal) | ✅ | @amogower | 1️⃣2️⃣4️⃣6️⃣ |
| [Sidebar](/reakit/reakit/tree/master/packages/reakit/src/Sidebar)* | ✅ | @amogower | 1️⃣2️⃣3️⃣4️⃣5️⃣6️⃣ |
| [Step](/reakit/reakit/tree/master/packages/reakit/src/Step)* | 🚧 | @diegohaz | 1️⃣2️⃣3️⃣4️⃣5️⃣6️⃣ |
| [Table](/reakit/reakit/tree/master/packages/reakit/src/Table)* | ✅ | @amogower | 1️⃣2️⃣ |
| [Tabs](/reakit/reakit/tree/master/packages/reakit/src/Tabs)* | ✅ | @amogower | 1️⃣2️⃣3️⃣4️⃣5️⃣6️⃣ |
| [Toolbar](/reakit/reakit/tree/master/packages/reakit/src/Toolbar)* | ✅ | @amogower | 1️⃣2️⃣3️⃣4️⃣5️⃣6️⃣ |
| [Tooltip](/reakit/reakit/tree/master/packages/reakit/src/Tooltip)* | 🚧 | @amogower | 1️⃣2️⃣3️⃣4️⃣5️⃣6️⃣ |

\* Contains sub components

**Comment by gustavo-depaula** [comment]
Tests case 1️⃣and 2️⃣seems like testing implementation details. Are they really necessary (and useful)?

**Comment by diegohaz** [comment]
@gustavo-depaula I don't think  1️⃣ is testing implementation details. 

The user of this library will expect the output element to render all HTML attributes they passed in. This is pretty much testing input/output. I think, though, there should be more effective ways to test that (like, it's not covering all possible html attributes), but it's okay for now.

Regarding  2️⃣, it's useful because we'll easily see style changes, which are often breaking changes.

**Comment by lluia** [comment]
I'm happy to write a few more tests, I could initially do for 👍🏻
- `Button`
- `Code`
- `Divider`
- `Field`

**Comment by PlayMa256** [comment]
its yours!

**Comment by amogower** [comment]
Keen to contribute, happy to take a look at:
- Overlay
- Popover
- Portal
- Tabs

**Comment by PlayMa256** [comment]
@amogower go for it!

**Comment by lluia** [comment]
I'm happy to write tests for 4 more:
- `Flex`
- `Grid`
- `Group`
- `Heading`

**Comment by PlayMa256** [comment]
done @lluia

**Comment by amogower** [comment]
Happy to take on a few more:

- Sidebar
- Table
- Toolbar
- Tooltip

**Comment by PlayMa256** [comment]
its yours @amogower

**Comment by lluia** [comment]
I'm happy to take the next four 🎊 💪
- `Image`
- `Inline`
- `InlineBlock`
- `InlineFlex`

**Comment by diegohaz** [comment]
Done @lluia (you can edit the post too 😁)

**Comment by lluia** [comment]
I'll take the last two:
- `Card`
- `Paragraph`
