### ISSUE TITLE
reakit-theme-default/ts/index.d.ts (3,45): Cannot find module 'styled-tools'.

### ISSUE THREAD

**Issue by wilomgfx** [reakit/reakit#272]
# Bug report

**What is the current behavior?**
If there is a heard reload (force reload from the browser) or create-react-app (with the typescript scripts) hot reloads/reloads the following error appears.

`reakit-theme-default/ts/index.d.ts (3,45): Cannot find module 'styled-tools'.`

Won't go away unless i save inside a typescript file and let it reload it self.

**If the current behavior is a bug, please provide the steps to reproduce.**

Use any reakit components when using the reakit-theme-default with the `Provider` component used

**What is the expected behavior?**

It should not cause that error

**Other relevant information:**
my related packages versions
 "react-scripts-ts": "3.1.0",
    "reakit": "^0.15.7",
    "reakit-theme-default": "^0.1.8",
    "styled-tools": "^1.5.1"

**Comment by diegohaz** [comment]
Hi @wilomgfx. Thanks for reporting.

Unfortunately, I couldn't reproduce it. I created a new app using `create-react-app-typescript`, installed the same dependencies and changed `App.tsx` with the following code:
```tsx
import * as React from 'react';
import { Button, Provider } from 'reakit';
import theme from 'reakit-theme-default';

class App extends React.Component {
  public render() {
    return (
      <Provider theme={theme}>
        <Button>Button</Button>
      </Provider>
    );
  }
}

export default App;
```

Ran `yarn start` and hard refreshed the browser. Everything seems to work. Is there any more steps I have to do to reproduce it?

**Comment by wilomgfx** [comment]
I'm using `allowSyntheticDefaultImports` in `tsconfig.json` if that ever changes something. I also use `styled.` to extend the components provided. I don't know if that changes anything.

**Comment by PlayMa256** [comment]
Could you try to put together a small repo/codesandbox?

**Comment by Thomazella** [comment]
Also could not reproduce. Hard reload is when you hold `shift`?
![screen shot 2018-10-14 at 5 32 32 pm](https://user-images.githubusercontent.com/15015324/46921871-3e017000-cfd7-11e8-8dbd-3e67ab9a3aa0.png)

**Comment by wilomgfx** [comment]
Hard reload, yep or just a normal one really. It's really strange! As soon as i get home i'll fire a repro repo.

**Comment by wilomgfx** [comment]
Could repro on codesanbox... but it seems to be happening if i change something inside a `.ts` file. Not sure if it's still related to `reakit` or `CRATS`

I'll port a minimal repo app from my current app asap

**Comment by wilomgfx** [comment]
I now also get the error for `Constate` :(

**Comment by wilomgfx** [comment]
ok sorry for the delay. Here is my repo 

https://github.com/wilomgfx/reakit-issue-272

Seems to be happening after a set amount of time (like 5 mins) or when modifying any `.ts` files... really strange!

**Comment by wilomgfx** [comment]
@diegohaz @Thomazella @PlayMa256 anyone :P ?

**Comment by Thomazella** [comment]
let me clone it!

**Comment by Thomazella** [comment]
> Seems to be happening after a set amount of time
Doesn't make sense to me. I'd guess it's a local thing.
- try using another text editor (not vscode)
- noticed it has an auto reload thing? `nodemon`? could be that.
- try `rm -fr node_modules && yarn`

**Comment by wilomgfx** [comment]
@Thomazella  ok thanks for trying, i really have no idea why it does that. At first i thought it was a set amount of time, after that i noticed it did it (more?) when modifying only `.ts` files.

1. I have not tried using something else than vscode, i could try webstorm.

2. Where do you see nodemon being used ?

3. I did that numerous times 😢

**Comment by Thomazella** [comment]
> Where do you see nodemon being used ?

I didn't look, sorry. I just meant "reload thing" lol

try on vscode: `cmd+shift+p` select typescript version, set to workspace.

**Comment by wilomgfx** [comment]
seems like setting the typescript version to workspace fixes it... kinda strange! But it fixes it. I'll close this one.
