### ISSUE TITLE
Mismatch props in tabs

### ISSUE THREAD

**Issue by ramiel** [reakit/reakit#279]
# Bug report

**What is the current behavior?**

The `current` props passed by Tabs.Container to its children is a number. Children accept a string instead. A warning is shown in console

**If the current behavior is a bug, please provide the steps to reproduce.**

Just use tabs 

**What is the expected behavior?**

Both types should match and probably the type should be a number

**Other relevant information:**
reakit version:  0.15.8

**Comment by diegohaz** [comment]
Should be fixed in `v0.15.9`
