### ISSUE TITLE
Typescript: Failed compilation reakit unresolved types from 'packages/reakit/src/_utils/types'

### ISSUE THREAD

**Issue by codyaverett** [reakit/reakit#283]
# Bug report

**What is the current behavior?**
Specific Typescript build fails to compile.
Several logs stating `not able to find module 'packages/reakit/src/_utils/types' are thrown.

![image](https://user-images.githubusercontent.com/3270702/47402506-963d1e00-d70b-11e8-855d-6a7ba3ad201f.png)

It compiles just fine in Code sandbox, but when it is exported it throws the above errors on build.

**If the current behavior is a bug, please provide the steps to reproduce.**

To reproduce, you can clone this repository, https://github.com/codyaverett/FYGanttChart , install dependencies, then `npm start` or `npx tsc -p .` from the project directory.
If you were to import this into codesandbox it will work.  🗡 

**What is the expected behavior?**

I don't know how else to phrase the expected behavior other than "It should work".
But it works in code sandbox... I'm super confused as to why ATM.

Could it be a codesandbox export issue..? 

**Other relevant information:**

reakit version: 0.15.8 or 0.15.9
typescript version: 3.1.3

I tested it on both mac and windows and got the same error results.

**Comment by diegohaz** [comment]
Thank you for reporting it, @codyaverett. I'm investigating it.

**Comment by diegohaz** [comment]
Should be fixed in `v0.15.10`. :)

**Comment by codyaverett** [comment]
Now I'm just getting errors from my own code! 👍 Thanks very much @diegohaz for the lightning quick turnaround on that!
