### ISSUE TITLE
Popover is blurry

### ISSUE THREAD

**Issue by thedrew12** [reakit/reakit#286]
# Bug report

**What is the current behavior?**
Sometimes when the popover is open, noticeable in Chrome, it renders css with translate3d as a decimal value `transform: translate3d(-224px,30.53125px,0px);`, which causes the output to look blurry. It seems to look better when the values aren't a decimal point. 
I haven't found a way to fix this on my end. From looking at the code, it seems a way to fix it would be in the `numberToPx` function by adding the `value.toFixed()`.
**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
It shouldn't be blurry.

**Other relevant information:**
reakit version: 0.15.10

**Comment by PlayMa256** [comment]
Proven to work: https://codesandbox.io/s/vyyqwkm92y

**Comment by diegohaz** [comment]
I'm not seeing the issue (maybe because of retina display?). Could you guys take a screenshot, please?

It should be easy to fix if the problem is with floating points.

**Comment by thedrew12** [comment]
@diegohaz Yeah, I can't reproduce this issue on my retina display, but I can on my external monitors. I'll take a screenshot tomorrow. I'm pretty sure the issue is floating points.

**Comment by PlayMa256** [comment]
The only problem is on chrome: http://prntscr.com/lfeo5j

**Comment by diegohaz** [comment]
I'd say that using `Math.round()` here on both values would fix the issue:
https://github.com/reakit/reakit/blob/7b3a78ebeb2ba9b0d930ae1722a27f88443249a9/packages/reakit/src/Popover/Popover.tsx#L64-L65

I don't have a non retina display here. Could you guys try it? (clone the repo and run `yarn && yarn website`)

**Comment by PlayMa256** [comment]
Seems to fix it. 
![image](https://user-images.githubusercontent.com/831308/48133010-7e71a800-e27c-11e8-85f2-87a7ceae4c4d.png)

**Comment by diegohaz** [comment]
Should be fixed in `v0.15.11`. Thanks for reporting @thedrew12
