### ISSUE TITLE
All custom styles get overwritten with 'unset'

### ISSUE THREAD

**Issue by ConneXNL** [reakit/reakit#289]
Using the beta version of reakit (didn't test normal version as I am already on SC 4.)

Doing
```
const MyBox = styled(Box)`
        background: ${rgba('black', 0.8)};
        background-color: ${rgba('black', 0.8)};
        color: red;
`;
```

produces:

```
.dGkyAZ {
    margin: unset;
    padding: unset;
    border: unset;
    background: unset;
    font: unset;
    font-family: inherit;
    font-size: 100%;
    box-sizing: border-box;
    background-color: unset;
    color: inherit;
}

.Box-sc-6sssmg-0 {
}

.kEorAp {
    background: rgba(0,0,0,0.8);
    background-color: rgba(0,0,0,0.8);
    color: red;
}
```

I am not sure where these 'unset' properties come from but they take presence over my custom styles.

```
const MyBox = styled(Box)`
      &&{
        background: ${rgba('black', 0.8)};
        background-color: ${rgba('black', 0.8)};
        color: red;
     }
`;
```
does work.

**Comment by diegohaz** [comment]
Thanks for reporting it @ConneXNL. The unset styles come from `Box`. I'll investigate it.

**Comment by diegohaz** [comment]
Hmm, I couldn't reproduce it: https://codesandbox.io/s/m4zj3o5q6p

Could you please provide a sandbox/repo with a reproduction?

**Comment by ConneXNL** [comment]
I upgraded to SC 4.1.* (I was at 4.0.*).
This seems to have resolved the issue.

I am closing this comment as it might be a SC issue rather then a reakit issue.
