### ISSUE TITLE
Getting a reference to the element

### ISSUE THREAD

**Issue by ghostika** [reakit/reakit#293]
# Bug report

**What is the current behavior?**
Using `innerRef` on a Reakit component generates a warning:
`Stateless function components cannot be given refs. Attempts to access this ref will fail.`

Using `ref` on a Reakit component will return a StyledComponent wrapper, not a ref to the original element.

**If the current behavior is a bug, please provide the steps to reproduce.**
```
const StyledBlock = styled(Block)`
styles...
`;

<StyledBlock innerRef={c => { this.styledRef = c; }}
```

**What is the expected behavior?**

Should return the underlaying DOM element.
Using `const StyledBlock = styled.div` returns the actual `div`

**Other relevant information:**
reakit version:  
v.0.15.10

**Comment by diegohaz** [comment]
Hi @ghostika. Try to use `elementRef` instead.

**Comment by ghostika** [comment]
@diegohaz Perfect, thanks, it worked. Is this somewhere documented?

**Comment by diegohaz** [comment]
Awesome! It's not documented yet.
