### ISSUE TITLE
Popover classes going wild, when parent is set to display:none

### ISSUE THREAD

**Issue by tizzle** [reakit/reakit#307]
# Bug report

**What is the current behavior?**
When is set a parent element of the Popover.Container to `display:none` reakit changes the classname of the Popover constantly when scrolling.

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Go to the [Popover example](https://reakit.io/components/popover) on the reakit website.
2. Scroll to the second example, click the "Toggle" button to see the Popover.
2. Open the Dev-Tools of your browser.
3. Examine the wrapping InlineBlock of the "Toggle" button in Dev-Tools.
4. Add a new style to this element: `display: none`
5. Scroll a bit
6. Witness the Popover element getting a new style on every scroll.

**What is the expected behaviour?**
The Popover should not get a new classname.

**Other relevant information:**
reakit version:  "reakit": "^0.15.11"

I made a short gif: http://eightdaysaweek.cc/files/REAKIT_POPOVER.gif

**Comment by diegohaz** [comment]
Thank you for reporting it @tizzle. I'm investigating it.

**Comment by tizzle** [comment]
Thanks @diegohaz,

i think this is due to the event handlers checking if the Popover is within bounds of the browser window to flip it if necessary. Let me know if you need any more information.

**Comment by diegohaz** [comment]
Should be fixed in `v0.15.12`
