### ISSUE TITLE
"types" key in proxy packages is bugged

### ISSUE THREAD

**Issue by jxom** [reakit/reakit#316]
# Bug report

**What is the current behavior?**

Seems like the compiled proxies "types" path point to @diegohaz's machine. :P 

Example:

```jsx
{
  "name": "reakit/Box",
  "private": true,
  "main": "../lib/Box",
  "module": "../es/Box",
  "types": "../ts//Users/diegohaz/Projects/reakit/packages/reakit/src/Box"
}
```

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

I guess it should point to the respective type def file, right?

```jsx
{
  "name": "reakit/Box",
  "private": true,
  "main": "../lib/Box",
  "module": "../es/Box",
  "types": "../ts/Box/index.d.ts"
}
```

I'll probs open a PR for this tomorrow - it's getting close to midnight here 😴 

**Other relevant information:**
reakit version: 0.16

**Comment by diegohaz** [comment]
Good catch! Sorry about that haha
