### ISSUE TITLE
[Feature Request] Portal support for popover/tooltip

### ISSUE THREAD

**Issue by ConneXNL** [reakit/reakit#318]
## Feature request
Popover and Tooltip should be rendered in a portal (by default?). In almost all the cases you want your tooltips and other overlays to be on top of everything else.

**What is motivation or use case for adding/changing the behavior?**
Currently, you run into z-index / overflow issues. Libraries like popper fix this (which is also used in reakit), its power is just isn't leveraged.

**Comment by diegohaz** [comment]
Thank you @ConneXNL. This is a planned feature. We just need to figure out how to get the reference element in Popover/Tooltip. Currently, it's using `findDOMNode` to get the parent element, but it doesn't work with portals.

This is my initial thought:
```jsx
<Popover.Container>
  {popover => (
    <div>
      <Popover.Reference as={Button} {...popover} />
      <Popover {...popover} /> 
    </div>
  )}
</Popover.Container>
```

**Comment by diegohaz** [comment]
Closing since popovers and tooltips are rendered in portals by default in v1.
