### ISSUE TITLE
Reakit + styled-system = weird behavior

### ISSUE THREAD

**Issue by xuopled** [reakit/reakit#319]
# Bug report

Hello, I'm trying ti use styled-system with the last reakit version but I can't make everything work.
Maybe I'm doing something wrond. In that case, please help me understand my mistake .

**What is the current behavior?**

The generated css is weird and unwanted style prop is attached to dom element.
The font size don't use the theme scale

**If the current behavior is a bug, please provide the steps to reproduce.**

Theme:
```
import {css} from "reakit"
import {fontSize, display} from "styled-system"

export default {
  fontSizes: [12, 20],
  Box: css`
    ${fontSize};
    ${display};
  `,
}
```

App:
```
import {Box} from "reakit"
export default () => (
  <Box fontSize={1} display={["none", "block"]}>
    {"reakit"}
  </Box>
)
```

**What is the expected behavior?**

The generated css is:
```
<div font-size="2" display="none,block" class="random" style="font-size:2px;display:none,block">reakit</div>
```

It should be:
```
<div class="random">reakit</div>

.random {
   font-size: 20px;
  display: none;
}

@media screen and (min-width: 1024px) {
  .random {
    display: block;
  }
}
```

**Other relevant information:**
reakit:  0.16.0-beta.0
styled-component: 4.1.2

**Comment by diegohaz** [comment]
Hi @xuopled. Thanks for reporting it.

I've never used styled-system. If you can't change the props names to something other than css props, it'll not work with Reakit, since it transforms css props into inline styles.
