### ISSUE TITLE
Keeping `css` prop functionality?

### ISSUE THREAD

**Issue by joserocha3** [reakit/reakit#323]
Hi, this is more of a question but I was not sure where else to ask. I was using rebass and am switching over reakit (props to Haz for that). rebass allows the use of the `css` prop along with `css` import from `styled-components/macro`. So the `Container` component below works with rebass and reakit@**next**, but not with the current `master` branch of reakit.

**Question**
Are you planning on keeping support for this feature and moving it into `master`?

```javascript
import React from 'react'
import { Box } from 'rebass'
// import { Box } from 'reakit' // uncommenting this line and commenting the one on top breaks `css`
import { css } from 'styled-components/macro'

const Container = props => (
  <Box
    css={css`
      padding: 0 2rem;
      width: 100%;
      margin: 0 auto;
      max-width: 1024px;   
    `}
    {...props}
  />
)

export default Container
```

**Comment by diegohaz** [comment]
Hey @joserocha3. Current master only works with `styled-components` v3. Reakit v0.16, which supports SC4, is still in beta and will be officially released soon (and merged into master). I'm working on it.
