### ISSUE TITLE
Sorry about the good-first-issues label removal

### ISSUE THREAD

**Issue by madiodio** [reakit/reakit#327]
Hi there @diegohaz. I just noticed that the all the good-first-issue labels are removed by my account (let a toddler too closed to my laptop 😢). So if you see these removal, they were not intentional and I'm really sorry about that. And seems like there is no way to undo that.

Again I'm really sorry and closing this issue.

**Comment by diegohaz** [comment]
No worries. I think I wouldn't notice it anyway 😅
