### ISSUE TITLE
Unable to component props in a TypeScript project

### ISSUE THREAD

**Issue by jeremija** [reakit/reakit#338]
# Bug report

Hello and thank you for this wonderful and easy to use project! I ran into compilation issues when trying to use it in a Typescript project. I did my best to extract only the relevant code below.

**What is the current behavior?**
I can use the components normally, but as soon as I define a component property, TypeScript compilation fails. It looks like all components are affected, but I only added 2 samples for brevity.

**If the current behavior is a bug, please provide the steps to reproduce.**

Contents of `package.json`:

```json
{
  "scripts": {
    "build": "tsc --noEmit --esModuleInterop --jsx react Test.tsx"
  },
  "devDependencies": {
    "@types/react": "^16.8.8",
    "@types/react-dom": "^16.8.2",
    "react": "^16.8.4",
    "react-dom": "^16.8.4",
    "reakit": "^0.16.0",
    "typescript": "^3.3.3333"
  }
}
```

Contents of `Test.tsx`:

```tsx
import React from 'react'
import {Button, Heading} from 'reakit'

export class Test extends React.PureComponent {
  render() {
    return (
      <div>
        <Heading>Heading level 1</Heading>
        <Button>Button</Button>
        <Heading use='h2'>Heading level 2</Heading>
        <Button palette='secondary'>Button</Button>
      </div>
    )
  }
}
```

Running the following:

```bash
npm install
npm run build
```

results with Typescript compile errors:

```
> @ build ***
> tsc --noEmit

Test.tsx(11,10): error TS2322: Type '{ children: string; use: string; }' is not assignable to type 'IntrinsicAttributes & Pick<Pick<{}, never>, never> & ClassAttributes<any> & Pick<{}, never> & { readonly use?: string | string[] | undefined; readonly useNext?: string | string[] | undefined; }'.
  Property 'children' does not exist on type 'IntrinsicAttributes & Pick<Pick<{}, never>, never> & ClassAttributes<any> & Pick<{}, never> & { readonly use?: string | string[] | undefined; readonly useNext?: string | string[] | undefined; }'.
Test.tsx(12,10): error TS2322: Type '{ children: string; palette: string; }' is not assignable to type 'IntrinsicAttributes & Pick<Pick<{}, never>, never> & ClassAttributes<any> & Pick<{}, never> & { readonly use?: {} | {}[] | undefined; readonly useNext?: {} | {}[] | undefined; }'.
  Property 'children' does not exist on type 'IntrinsicAttributes & Pick<Pick<{}, never>, never> & ClassAttributes<any> & Pick<{}, never> & { readonly use?: {} | {}[] | undefined; readonly useNext?: {} | {}[] | undefined; }'.
```

**What is the expected behavior?**
Using documented component properties should not result in TypeScript compilation errors, as long as they are correctly defined.

**Other relevant information:**
reakit version: 0.16.0
typescript version: 3.2.4

**Comment by diegohaz** [comment]
Hi @jeremija

Try to `npm install @types/styled-components`

**Comment by jeremija** [comment]
Thanks, that was it! Would it be possible to bundle these definitions with reakit somehow? Alternatively, it could be mentioned in `docs/get-started.md` to prevent others from running into the same issue.

**Comment by diegohaz** [comment]
Yeah, some people have run into that too. I think we should add a note to docs. Would you like to do that?

**Comment by jeremija** [comment]
Thanks for the invite @diegohaz. Glad I was able to help!

I have one more question regarding Reakit and TypeScript. Since I haven't used `styled-components` before, I noticed the TS compilation time increase drastically now that compilation succeeds. In the simple example I provided, it jumped from being instant without Reakit to about 5s with Reakit. On the project I'm working on it jumped from ~1s to about 15s after adding a few Reakit components to a single component in the project. 

Just wondering if this is the usual experience with `styled-components` or `reakit`, or do you think there might be room for improvement in my configuration?

**Comment by diegohaz** [comment]
We use lots of complex types from `@types/react`. I don't know if that's causing that problem, but there should be something we can do about it.
