### ISSUE TITLE
Reakit test snapshot

### ISSUE THREAD

**Issue by yazpid** [reakit/reakit#341]
Hello

Could you tell me how you deal with updating snapshots without changing name hash? I'm tried to use `jest-styled-components` but it is not working for me. Is it something similar tool for reakit ?

**Comment by diegohaz** [comment]
I guess you need babel-plugin-styled-components.

**Comment by yazpid** [comment]
> 
> 
> I guess you need babel-plugin-styled-components.

@diegohaz I'm tried configure `babel-plugin-styled-components` but then in snapshots I have the same result (without css class with name like `c0`, `c1`)
