### ISSUE TITLE
Perfomance issue with @types/styled-components

### ISSUE THREAD

**Issue by kolengri** [reakit/reakit#344]
I like to use reakit with typescript, but I am faced with a performance problem.
if I install the package @types/styled-components, then the project and typechecking starts working extremely slowly.

**If the current behavior is a bug, please provide the steps to reproduce.**
I created the repository for you, where you can check it
https://github.com/kolengri/reakit-perfomance-issue

```
yarn

yarn tsc --diagnostics
```

and try to remove `@types/styled-components`

```
yarn remove @types/styled-components

yarn tsc --diagnostics
```

**Other relevant information:**
reakit version:  0.16.0

**Comment by diegohaz** [comment]
Thanks for the reproduction @kolengri. That's a huge difference.

I'm not sure if it's our types (maybe [reuse](https://github.com/diegohaz/reuse/blob/master/src/use.tsx) types) or the [styled-components](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/styled-components/index.d.ts) ones, which are pretty complex.

**Comment by kolengri** [comment]
I think it's definitely. I've tried to remove reuse types. 
With complex project it's going to be worst :( 3s vs >120s

**Comment by diegohaz** [comment]
That's unfortunate.

The good news is that the dependency on styled-components has been removed in Reakit v1. I'll publish an alpha version this week (the official release will take a month or so though).

**Comment by diegohaz** [comment]
Closing this as styled-components is not a dependency anymore (v1) and it seems there's only much we can do about this on v0 as the problem seems to live on styled-components types.
