### ISSUE TITLE
Benefits of inline styling

### ISSUE THREAD

**Issue by sara-dubois** [reakit/reakit#349]
First of all - this is neither a bug report, a feature request or any critique.

I've enjoyed Reakit very much and the [Inline styling](https://reakit.io/guide/styling) concept has proved to be excellent ergonomics when fastly building up a UI.

But apart from the subjective liking of this way of styling, are there other benefits worth knowing about?

Again, this is not critique in any way - only curious to learn as I'm new to this and would like to present this to my team.

**Comment by diegohaz** [comment]
Hey sara.

Some benefits I can think of:

- Faster prototyping.
- It has the highest specificity in the cascade (you can only override it with `!important`).
- It's great for critical CSS (you don't need to wait for external CSS files to be ready).
- It's great for styles that change often (like a few times per second).

That said, I only recommend it for prototyping.

**Comment by RodrigoNovais** [comment]
I was looking for an issue that talks about the inline styles before open a new one but it seems not to be a very recorrent topic
That are some rules that I wouldn't call critical that are being setted inline. I wonder if I'm supposed to fill my CSS with `!important` (wish I'd love to avoid) or if there's anyway I could override it

Let's take the `SelectArrow` and the `width` and `height` being forced to `1em`, I don't understant how critical that would be
