### ISSUE TITLE
Feature Request - Adding more components

### ISSUE THREAD

**Issue by Muhnad** [reakit/reakit#353]
### Motivation

there is a lot of missing components you can add/provide that will help the community, so I think you need to add a roadmap for upcoming components something like trello TO DO, WORKING ON and so on...

### Example
examples of missing components that need a lot of accessibility support in websites so building it on reakit would be great.

- Skip-navigation
- Date picker
- Time picker
- Notification toasters
- Tags.
- Uploader.

that's on my mind right now

### Possible implementations
we can start to prioritize components and start working on to launch on next release.

I implemented a [skip-navigation](https://github.com/Muhnad/skip-links) component and published it on npm I think we can merge it on reakit.

**Comment by diegohaz** [comment]
Maybe it can be of some help: https://twitter.com/diegohaz/status/1128727153300971520

**Comment by jlarmstrongiv** [comment]
Not a definitive list, but I think adding components from [w3.org](https://www.w3.org/TR/wai-aria-practices-1.1/) would be great.  Makes it easy by following their naming convention and examples.

**Comment by fernandosouza** [comment]
I'm willing to help on this.

**Comment by jlarmstrongiv** [comment]
I went ahead and compared the list on [w3.org](https://www.w3.org/TR/wai-aria-practices-1.1/) to the existing components in reakit:

- [ ] Accordion (Sections With Show/Hide Functionality)
- [ ] Alert
- [ ] Alert and Message Dialogs
- [ ] Breadcrumb
- [x] Button - [implemented](https://reakit.io/docs/button/) 
- [ ] Carousel (Slide Show or Image Rotator)
- [x] Checkbox - [implemented](https://reakit.io/docs/checkbox/)
- [ ] Combo Box
- [x] Dialog (Modal) - [implemented](https://reakit.io/docs/dialog/), as Dialog
- [x] Disclosure (Show/Hide), [implemented](https://reakit.io/docs/hidden/), as Hidden
- [ ] Feed
- [ ] Grids (Interactive Tabular Data and Layout Containers)
- [ ] Link
- [ ] Listbox
- [x] Menu or Menu bar - [implemented](https://reakit.io/docs/menu/)
- [x] Menu Button - [implemented](https://reakit.io/docs/menu/)
- [x] Radio Group -  [implemented](https://reakit.io/docs/radio/)
- [ ] Slider
- [ ] Slider (Multi-Thumb)
- [ ] Spinbutton
- [ ] Table
- [x] Tabs - [implemented](https://reakit.io/docs/tab/)
- [x] Toolbar - [implemented](https://reakit.io/docs/toolbar/)
- [x] Tooltip Widget - [implemented](https://reakit.io/docs/tooltip/), as Tooltip
- [ ] Tree View
- [ ] Treegrid
- [ ] Window Splitter

I figured I might as well include helpers that do not correspond to w3.org widgets to show the scope of reakit:
- [Form](https://reakit.io/docs/form/), experimental 
- [Group](https://reakit.io/docs/group/)
- [Popover](https://reakit.io/docs/popover/)
- [Separator](https://reakit.io/docs/separator/), reference [w3](https://www.w3.org/TR/wai-aria-1.1/#separator)
- [VisuallyHidden](https://reakit.io/docs/visually-hidden/)
- Abstract Components
  - [Box](https://reakit.io/docs/box/)
  - [Portal](https://reakit.io/docs/portal/)
  - [Rover](https://reakit.io/docs/rover/), references [w3](https://www.w3.org/TR/wai-aria-practices-1.1/#kbd_roving_tabindex)
  - [Tabbable](https://reakit.io/docs/tabbable/)

A few questions and comments after making the list:
- I didn’t realize how many components were already implemented _and_ followed w3 guidelines.  Nice!! 👍 
- Should hidden be renamed or aliased as disclosure for consistency?
- Components that could use more documentation:  [Group](https://reakit.io/docs/group/).  Maybe [separator](https://reakit.io/docs/separator/).  
- I’d like to help too, but I need to familiarize myself with the v1 codebase, typescript, w3 accessibility docs, and testing.

**Comment by diegohaz** [comment]
Thank you @jlarmstrongiv.

I've checked the alert dialog.

Regarding the codebase, I have to update the CONTRIBUTING.md file with instructions. But the `reakit` package is pretty standardized. Once you understand a component, the others follow the same pattern. Any question, just ask, I'll be glad to help.

**Comment by cyrus-za** [comment]
+1 for datepicker. Can't seem to find one out there that is simple to use and that allows you to quickly navigate through years for date of birth

**Comment by Muhnad** [comment]
my thoughts when I opened this issue was we need to create more components that used a lot in the web these days and has a low of accessibility guidelines beside almost of a new toolkit these days create the same components no one tried to build new components that used widely and need support from the community.

BTW, what reakit reached is great and I like what they did.

**Comment by artalar** [comment]
What is actually a "message" component?
How can I implement notifications, like it https://ant.design/components/message/?
(do I need to create separate issue?)

**Comment by diegohaz** [comment]
@artalar I think it's better to create a new issue. The pattern you're looking for is [Alert](https://www.w3.org/TR/wai-aria-practices/#alert). We're going to create it at some point once we're out of beta, but it's not a priority of mine right now. If you create an issue, someone can rope in and work on that.

**Comment by artalar** [comment]
Ok, thx.
By the way: https://inclusive-components.design/notifications/

**Comment by diegohaz** [comment]
Closing this. Let's discuss about new components in their specific issues.
