### ISSUE TITLE
Disappearance of lots of components

### ISSUE THREAD

**Issue by axhamre** [reakit/reakit#356]
Half of all components since 0.16.0 seem to be gone (Grid, Image, Flex etc).

1. What is the rationale about this drastic move?

2. Any suggestion how to mitigate the situation when heavily dependent on these components?

**Comment by diegohaz** [comment]
Please use this issue (left this comment there if possible): https://github.com/reakit/reakit/issues/350

There will be an explanation and a nice migration path described here.
