### ISSUE TITLE
Mobile usability

### ISSUE THREAD

**Issue by sesam** [reakit/reakit#357]
## 🚀 Feature request
Tabs (likely also TabsModal)
- has too small touch area
- don't suggest scrolling right to see the rest of the menu

### Motivation
Using reakit.io I first failed to see and scroll on the tabbed menus. Seems my first scroll attempt didn't hit the touchable area well enough.
Tried on Samsung S9.

Suggestions:
increase touch height 20-30%
Render some ... or similar when overflow 

### Example

On mobile, can't photoshop now

**Comment by diegohaz** [comment]
I agree. I guess this can be implemented in reakit-system-bootstrap.

**Comment by benschac** [comment]
Can I grab this one?

**Comment by diegohaz** [comment]
Sure. It's yours @benschac

**Comment by benschac** [comment]
Was thinking: 
https://www.smashingmagazine.com/2012/02/finger-friendly-design-ideal-mobile-touchscreen-target-sizes/

```
A touch target that’s 45 - 57 pixels wide allows the user’s finger to fit snugly inside the target. The edges of the target are visible when the user taps it.
```

We're currently right at 44px.
<img width="374" alt="Screen Shot 2019-05-16 at 12 12 34 PM" src="https://user-images.githubusercontent.com/2502947/57870154-85054d00-77d4-11e9-8d79-a9d5583bece6.png">

**Comment by diegohaz** [comment]
Hmm. So, maybe just an `:after` pseudo-element with a gradient here to indicate that there are more tabs: https://github.com/reakit/reakit/blob/690bd6e775a2736372edd00b56f0d73a278e2ea3/packages/website/src/components/HomePlayground.tsx#L233-L253

**Comment by benschac** [comment]
Don't increase the padding / target height?

**Comment by sesam** [comment]
This PR https://github.com/reakit/reakit/pull/359 from a couple of months back (!!) needs some love to move things forward.
