### ISSUE TITLE
TooltipReference always sets tabIndex to 0

### ISSUE THREAD

**Issue by jole78** [reakit/reakit#363]
In the Tooltip component, the TooltipReference always sets tabIndex to 0. There might be a reason for that but let's say I'm builing a Dialog with a close button (x) at the top right. The button also has a tooltip wrapping it. Now the problem is that even though I set my close button to have tabindex -1 (to focus something else instead) the button will have tabindex reset to 0 which will give it focus and the notification shows up when the dialog opens.

I've managed to hack around it...but maybe there could be an alternative or more supported escape hatch or something.

<br>

> Using Reakit at work? Please, consider asking your company to sponsor us. ❤️
> https://opencollective.com/reakit

**Comment by diegohaz** [comment]
Hey @jole78 

If I understand correctly, you want to disable tabbing on the close button because you want the initial focus to be on a different component within the dialog. Is this accurate?

If that's the case, I think you're trying to approach the problem with the wrong solution.

First of all, disabling the tab behavior on that element is a an accessibility issue. Since you chose to use Reakit, I guess you don't want that, right? That's why the `tabIndex` prop is enforced on that component.

The solution is to use the `unstable_initialFocusRef` prop on Dialog:
```jsx
import React from "react";
import { useDialogState, Dialog } from "reakit";

function MyDialog() {
  const initialFocusRef = React.useRef();
  const dialog = useDialogState();
  
  return (
    <Dialog unstable_initialFocusRef={initialFocusRef} {...dialog}>
      <MyCloseButton onClick={dialog.hide} />
      <AnotherComponent ref={initialFocusRef} />
    </Dialog>
  );
}
```

Since it's `unstable`, I recommend you to abstract it into a new component that you control:
```jsx
import { Dialog as ReakitDialog } from "reakit";

function Dialog({ initialFocusRef, ...props }) {
  return <ReakitDialog unstable_initialFocusRef={initialFocusRef} {...props} />;
}
```

If it changes in the future (unlikely, but it's better to be safe), you only need to update this component.

**Comment by jole78** [comment]
I'm probably thinking about this from the wrong angle here but maybe some "pseudo" code can bring insights:

Dialog here is a custom "wrapped" version of RK Dialog.
```jsx
<Dialog>
<SomeFormInADialog />
....

// inside custom dialog comp
          <Tooltip text="Close the dialog (or press ESC)">
            <Button>
              <Icon as={CloseDialogIcon} />
            </Button>
          </Tooltip>

        // render children from user of dialog here
      {children}
```
I don't want to force the user of my custom dialog comp to set an initial focus thing. What happens now is that since the Button with the Tooltip is rendered first it gets the initial focus and the Tooltip shows up when the Dialog opens up.

I can of course move the Button to the end of the dialog and absolute position it on top of the children...that works...but...??

**Comment by diegohaz** [comment]
I see. In this case, I think I would keep the initial focus going onto the close button by default, but I'd not use a tooltip. A button with a visually hidden element inside would be enough to me:
```jsx
<Button>
  <VisuallyHidden>Close the dialog</VisuallyHidden>
  <Icon as={CloseDialogIcon} />
</Button>
```
The close icon should be direct enough for visually abled users. They don't need a tooltip for this.

But, yes, if you want to stick with the tooltip, I think putting the element below the content is the easiest workaround (not sure if it's the best one as it would mess up with the tab order).

Regarding your original question, I actually checked it and Reakit doesn't override the html props you pass in. So, passing `tabIndex={-1}` to the tooltip reference element, despite being a terrible idea, should render with `tabindex="-1"`. You can test it in isolation on the playground. So I guess your implementation aren't passing the props properly.

**Comment by jole78** [comment]
Thanks for the input Diego. Guess it turned out being more of question. At least now I know which options I have. Gonna close the issue. Again tnx 👍
