### ISSUE TITLE
Please make pre-1.0 documentation available

### ISSUE THREAD

**Issue by Slapbox** [reakit/reakit#364]
I'm trying to use `Step.Container`, but all the docs are gone unless I dig through the git history? Am I overlooking something?

Pre-1.0 needs to be supported for a while.

**Comment by diegohaz** [comment]
Hi @Slapbox. Links are in the README: https://github.com/reakit/reakit#installation

https://v0.reakit.io

**Comment by Slapbox** [comment]
@diegohaz thanks for the blazing fast response. Can I suggest forwarding old pages like https://reakit.io/components/step/stepcontainer to some new page? MANY links to Reakit on Google now go to 404, which will definitely hurt SEO.

Is the Step component renamed to something else now? I think some more transition material is needed.

**Comment by diegohaz** [comment]
`Step` can be created using [`Rover`](https://reakit.io/docs/rover). I'm gonna write a guide on it on the migration guide.

And, oh, I probably forgot to redirect a few urls. I'm gonna add Step redirects. If you find more missing ones, could you please update the `redirect_from` property in the README files?
Example: https://github.com/reakit/reakit/blob/master/packages/reakit/src/Popover/README.md

**Comment by Slapbox** [comment]
Awesome thanks @diegohaz!

I'll update anything I come across, though since I'm going to be in the `0.16.x` docs specifically rather than using Google now, I probably won't come across any more.
