### ISSUE TITLE
Remove default element styles from dialog components

### ISSUE THREAD

**Issue by Regaddi** [reakit/reakit#366]
### Motivation

The default element styles on the elements require some nasty overriding. When using [styled-jsx](https://github.com/zeit/styled-jsx) it requires some `!important` styles to overwrite the element styles (which otherwise have highest priority).

Dialog:
![image](https://user-images.githubusercontent.com/1336590/58419741-b232e480-808b-11e9-8f34-c1aa8d9d266a.png)

DialogBackdrop:
![image](https://user-images.githubusercontent.com/1336590/58419763-bfe86a00-808b-11e9-9efb-c40eb7ce5aa7.png)

### Example

Just remove the element styles. We can handle them on our own 😄 

### Possible implementations

tbd.

**Comment by diegohaz** [comment]
@Regaddi those styles are probably more useful than annoying. But that's my guess. I'd like to get feedback from more people.

Could you please elaborate more why you want to override those css rules? I'm particularly curious about why you would like to override `display: none` when the dialog is hidden.

That said, there are other ways to work around this. Although I think `!important` is most simple one, you can use strip out the style attribute by using render props:

```jsx
<Dialog>
  {({ style, ...props }) => (
    <div  {...props}>
      ...
    </div>
  )}
</Dialog>
```

**Comment by Regaddi** [comment]
> Could you please elaborate more why you want to override those css rules?

Mainly `z-index` as we have a z-index management in our theme. The positioning is minor. I agree that `display: none;`  should be fine to be set by Reakit.

**Comment by diegohaz** [comment]
If Reakit had some sort of zIndex management built-in, would it be possible to integrate with your own solution?

Something like this:
```jsx
import { ZProvider, Dialog } from "reakit";

<ZProvider value={2}>
  <Dialog>
    ...
  </Dialog>
</ZProvider>
```

**Comment by fleischie** [comment]
I had similar issues with the `z-index` attribute beeing of a specific value (we have our own `z-index` hierarchies in my current project).

As I was using `styled-components`, I managed to change the index via
```typescript
styled(DialogBackdrop).attrs({ style: { zIndex: <desired-z-index> } })
```

**Comment by diegohaz** [comment]
Could you guys give more details on how you manage z-index in your projects?

@fleischie It doesn't work because Reakit sets `zIndex` as inline styles, which have precedence. You would need to use `!important`.

**Comment by Regaddi** [comment]
We're defining our general theming values in a `theme.js` file. Things like global font sizes, font families, colors, spacings and z-index values are centrally stored there.
A custom react hook allows to read those values inside of our components.

```js
// theme.js

const zIndex = {
  navbar: 1,
  modalBackdrop: 2,
  modal: 3,
  tooltip: 4
}

export { zIndex }
```

```jsx
// hooks.js
import * as theme from './theme'

export const useTheme() => theme
```

```jsx
// modal.js
import {
  useDialogState,
  Dialog,
  DialogDisclosure,
  DialogBackdrop
} from 'reakit/Dialog'

import { useTheme } from './hooks'

export const Modal = ({ children, title }) => {
  const { zIndex } = useTheme()
  const dialog = useDialogState()

  return (
    <>
      <DialogDisclosure {...dialog} />
      <DialogBackdrop className="backdrop" {...dialog} />
      <Dialog aria-label={title} className="dialog" {...dialog}>{children}</Dialog>
    </>
    <style jsx>{`
      .backdrop {
        background: rgba(255, 255, 255, 0.5);
        bottom: 0;
        left: 0;
        position: fixed;
        right: 0;
        top: 0;
        z-index: ${zIndex.modalBackdrop};
      }
      .dialog {
        position: fixed;
        z-index: ${zIndex.modal};
      }
    `}</style>
  )
}
```

**Comment by fleischie** [comment]
Yupp, same.

**Comment by diegohaz** [comment]
This makes sense. Thank you.

One question: how would you handle nested dialogs with backdrops? With your current approach, I guess the nested dialog backdrop will not dim the parent dialog.

Anyway, I think the best solution for you right now is to strip out the style attribute with render props as I have exemplified in a comment above.

**Comment by fleischie** [comment]
We currently habe at max one Modal rendered at a time, that also has a Backdrop. Anything nested (e.g. a Popup Dialog) does not have its own Backdrop, as its not our Modal component.

**Comment by ronnyhaase** [comment]
> Components are unstyled by default

That's great! Keep it real.

- Less headache for Reakit
- As pointed out some larger projects might come with a solution for handling z-index, which likely conflicts with whatever Reakit comes up with
- I think since Reakit in some cases doesn't make smart assumptions about some ARIA attributes and instead asks the developer to take proper care of them, why not do the same for z-index?

That was my opinion, but I think there is also one actual issue here: Backdrop is always in front of Dialog by default, because it is `position: fixed`, while Dialog is not.

**Comment by diegohaz** [comment]
@ronnyhaase Backdrop being in front of Dialog is definitely a bug.

I'm thinking on a way to get rid of z-indexes or at least make them easily overridable. Should have something in the next few days.
