### ISSUE TITLE
Checkbox on Firefox when using keyboard checks and unchecks immediately

### ISSUE THREAD

**Issue by ksmithut** [reakit/reakit#368]
### Current behavior

When using firefox, tabbing to a checkbox and pressing "spacebar" to check (or uncheck) the checkbox, it immediately undoes the action.

### Steps to reproduce the bug

Provide a repo or sandbox with the bug and describe the steps to reproduce it.

0. Be using Firefox (I'm using 67.0 on macOS 10.14.15)
1. Open sandbox: https://codesandbox.io/s/reakit-uzqn7
2. Tab to the Reakit checkbox
3. Press spacebar (a few times for good measure)

### Expected behavior

It should toggle the checkbox once per spacebar press, but it seems to be doing it twice

### Possible solutions

I haven't looked at the code for the checkbox yet, but I plan to.

**Comment by diegohaz** [comment]
Good catch @ksmithut. Thank you.

Working on it.

**Comment by ksmithut** [comment]
@diegohaz Thanks for the quick work! It is much appreciated.

**Comment by diegohaz** [comment]
Thank you for the donation @ksmithut :)

The fix will go live in the next version (likely this weekend).

**Comment by tom-sherman** [comment]
Looks like this bug is back on Firefox. Sandbox with latest reakit version here: https://codesandbox.io/s/reakit-checkbox-space-q82kg?file=/index.js
