### ISSUE TITLE
Tooltip following pointer

### ISSUE THREAD

**Issue by thefrontendwizard** [reakit/reakit#373]
## 🚀 Feature request

Tooltip that follows the cursor while hovering the element.

### Motivation

There might be use cases where this is interesting, specially when the reference is large.

### Example

Ideally, this should be a boolean on `useTooltipState`, something like `followCursor`/`followPointer`/`followMouse`.

```jsx
useTooltipState({ followCursor: true });
```

### Possible implementations

https://codesandbox.io/s/reakit-tooltip-following-mouse-7wolg

**Comment by diegohaz** [comment]
Thank you @thefrontendwizard 

For anyone reading this: this can be implemented in the user land by using Reakit building blocks (https://codesandbox.io/s/reakit-tooltip-following-mouse-7wolg). So, please, if you need this feature, do this in your project and give us feedback so we can find a better API/implementation.

**Comment by diegohaz** [comment]
Closing this as it doesn't seem something that we should implement in the library. For people needing this, the CodeSandbox above should help.

**Comment by dmgawel** [comment]
> For anyone reading this: this can be implemented in the user land by using Reakit building blocks (https://codesandbox.io/s/reakit-tooltip-following-mouse-7wolg). So, please, if you need this feature, do this in your project and give us feedback so we can find a better API/implementation.

@diegohaz It would be great to either revisit implementing this feature in the library or improve the example user-land implementation (which was **very** helpful already! 🙇‍♂️). I'm struggling with some issues that are handled perfectly in native `useTooltipState`, but are present in the CodeSandbox:
* Showing only one tooltip at once,
* Updating tooltip position on scroll (that's especially apparent on mobile, when scroll is not triggering mousemove).

I hope you could reconsider it or give the example implementation another pass 🤞
