### ISSUE TITLE
Provide an example using styled components

### ISSUE THREAD

**Issue by ryardley** [reakit/reakit#377]
### Motivation

I found this awesome project via the styled components website while searching for a component library which used styled-components under the hood. After reading the docs I discovered styled-components had been factored out of the new release to make the lib style agnostic which I think is an excellent move. 

However because of the history of this project with styled components many people will come here searching for a component kit relate to styled-components or that can be used with styled components and the suggestions of using emotion in the docs may send them away whilst this lib would still potentially provide the functionality they need.   

### Example

I suggest an example provided using styled-components so it is clear how to use reakit with styled-components

### Possible implementations

I have provided a PR to the docs website that displays an example with styled components here: https://github.com/reakit/reakit/pull/379

**Comment by diegohaz** [comment]
I totally agree. Thank you.
