### ISSUE TITLE
There is bug in Modal Window, whenever we try to scroll background screen scrolls. 

### ISSUE THREAD

**Issue by swatiQait** [reakit/reakit#391]
### Current behavior

Explain what's happening.

### Steps to reproduce the bug

Provide a repo or sandbox with the bug and describe the steps to reproduce it.

1. Open sandbox: https://codesandbox.io/s/m4n32vjkoj (you can use it as a base)
2. Remove any line
3. See console logs

### Expected behavior

Explain how it should behave.

### Possible solutions

If possible, describe how this bug could be fixed.

### Environment

```sh
$ npx envinfo --system --binaries --npmPackages

Paste here
```

**Comment by swatiQait** [comment]
Scroll be be applied to modal Screen only.

**Comment by diegohaz** [comment]
Could you please provide a reproduction sandbox or something? I can't reproduce this behavior (background scroll is always locked unless you're using a non-modal dialog)
