### ISSUE TITLE
Checkbox augmented as button has backwards event.target.checked value

### ISSUE THREAD

**Issue by mattdaly** [reakit/reakit#393]
### Current behavior

When augmenting a `Checkbox` as a `button` (https://github.com/reakit/reakit/tree/master/packages/reakit/src/Checkbox#as-prop), the value of `event.target.checked` in the `onChange` handler is backwards - when `aria-checked` is `true`, `event.target.checked` is `false`.

As a side note, the typescript build fails when passing `button` to `as` - `TS2322: Type '"button"' is not assignable to type '"input" | undefined'.`

### Steps to reproduce the bug

1. Open sandbox: https://codesandbox.io/s/reakit-checkbox-as-button-fmglt
2. Toggle the Checkbox component and see it's state be in sync
3. Toggle the Toggle component and see it's state be out of sync

### Expected behavior

`event.target.checked` stays in sync with the value of `aria-checked`, behaving the same as a normal Checkbox component

**Comment by diegohaz** [comment]
Thank you for the reproduction @mattdaly. Indeed it's a bug.

I'll tackle this as soon as I get some free time. But, just in case someone wants to give it a try first, I guess this is the relevant piece of code: https://github.com/reakit/reakit/blob/51b9a0e434d7b4bd12d50bd9877a3a1997fd87c0/packages/reakit/src/Checkbox/Checkbox.ts#L74-L107

**Comment by diegohaz** [comment]
Regarding the typescript error, I can't see it on CodeSandbox (TypeScript version in CodeSandbox is outdated) and I couldn't reproduce it locally with the latest version of TypeScript.

**Comment by mattdaly** [comment]
My bad, the typescript error is in a local project. It appears to be related to a rollup and typescript integration, I will investigate it further and open a separate issue if it persists.

**Comment by brandonjpierce** [comment]
Ran into this problem myself recently. The problem actually lies in the internal `onClick` function passing a different event than the one emitted from an actual `onChange` event.

https://github.com/reakit/reakit/blob/master/packages/reakit/src/Checkbox/Checkbox.ts#L112

`onChange` is being passed a `MouseEvent` here instead of a `onChange` synthetic event thus the incorrect value.
