### ISSUE TITLE
Issue when using dialogs and `unstable_FormRemoveButton` together

### ISSUE THREAD

**Issue by tom-sherman** [reakit/reakit#395]
### Current behavior

Dialogs are bugging out when I use them inside of a form along with `unstable_FormRemoveButton`. 

The dialogs flicker under some circumstances.

### Steps to reproduce the bug

Provide a repo or sandbox with the bug and describe the steps to reproduce it.

1. Open sandbox: https://codesandbox.io/s/form-remove-item-and-dialog-bug-1hwzl
2. Remove the default item by clicking remove and then confirming with the dialog. Item is removed correctly.
3. Add two items into the form
4. Click "remove item" on any of the items
5. Dialog is flashed up for a couple of frames

### Expected behavior

I want to be able to open a modal to confirm the removal of each individual item.

### Environment

```sh
$ npx envinfo --system --binaries --npmPackages

  System:
    OS: Linux 4.15 Linux Mint 19.1 (Tessa)
    CPU: (6) x64 Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz
    Memory: 462.80 MB / 7.62 GB
    Container: Yes
    Shell: 4.4.19 - /bin/bash
  Binaries:
    Node: 12.6.0 - /usr/bin/node
    npm: 6.9.0 - /usr/bin/npm
  npmPackages:
    framer-motion: ^1.2.1 => 1.2.1 
    g: ^2.0.1 => 2.0.1 
    prettier: ^1.18.2 => 1.18.2 
    react: ^16.8.6 => 16.8.6 
    react-dom: ^16.8.6 => 16.8.6 
    react-router-dom: ^5.0.1 => 5.0.1 
    react-scripts: 3.0.1 => 3.0.1 
    react-twemoji: ^0.2.3 => 0.2.3 
    reakit: ^1.0.0-beta.4 => 1.0.0-beta.4 
    serve: ^11.1.0 => 11.1.0 
    source-map-explorer: ^2.0.1 => 2.0.1 
    styled-components: ^5.0.0-beta.8 => 5.0.0-beta.8 
```

**Comment by diegohaz** [comment]
Thanks for reporting @tom-sherman!

I guess this is related to the fact that dialogs can only have one disclosure at the moment. Right now this can be fixed on your side by having one dialog to each item.

But we do need to support multiple disclosures.

Related: https://spectrum.chat/reakit/general/hi-wondering-if-its-possible-to-open-a-dialog-outside-of-using-the-disclosure~7c70c29f-60a0-4419-a492-ad0fae62c489?m=MTU2MDQ2NTYzMzkxMw==

**Comment by tom-sherman** [comment]
@diegohaz no problem! In my sandbox, isn't each item getting its own dialog inside of the map fn?

**Comment by diegohaz** [comment]
@tom-sherman You have only one `useDialogState`. It shouldn't be used for multiple Dialog components. You can abstract the Dialog into another component and put `useDialogState` there.

**Comment by diegohaz** [comment]
Closing as this isn't really a bug. But we'll probably need to add a warning about using `useHiddenState` (and derivatives) for multiple `Hidden` components.

**Comment by tom-sherman** [comment]
Thanks for the tip!
