### ISSUE TITLE
Form: Add textarea input type

### ISSUE THREAD

**Issue by tom-sherman** [reakit/reakit#397]
### Motivation

It's a widely used input type.

### Possible implementations

Would function exactly as `FormInput` but using a `<textarea>` instead of an `input`.

**Comment by diegohaz** [comment]
I expect people use the `as` prop like this:
```jsx
<FormInput as="textarea" />
```

**Comment by tom-sherman** [comment]
Makes sense, worth adding this to the docs if it's the preferred way of doing things?

**Comment by diegohaz** [comment]
Yes, definitely!
