### ISSUE TITLE
Form onValidate as a prop

### ISSUE THREAD

**Issue by cbush** [reakit/reakit#400]
Hi, thank you for the great library. I have run into an issue and could use some help. If there's an intended way for me to do this, let me know and I can close the issue.

## 🚀 Feature request

`<Form>` should have onValidate as a prop, not part of state

### Motivation

I would like to change the value of onValidate in the form. Consider if onValidate called a callback prop of the enclosing component. This callback will not get updated in the onValidate function because it was only set at the first render's useFormState() call. There doesn't seem to be a way to update this value when props change -- again, let me know I'm missing something!

### Example

The issue is illustrated here. When the parent's onValidate prop is updated, the Form will still use the old onValidate:
```
const MyComponent = ({ onValidate }) => { // takes callback as a prop
  const form = useFormState({ // initialize form state
    values: { foo: "" },
    onValidate // will not be updated when parent onValidate prop changes (!)
  });
  return (
    <Form {...form}>
      <FormInput {...form} name="foo" />
    </Form>
  );
};

const Example = () => {
  const [count, setCount] = useState(0);
  return (
    <>
      <Button onClick={() => setCount(count + 1)}>{count}</Button>
      <MyComponent
        onValidate={() => {
          // Note this always prints 0, even though count is changing!
          console.log(count);
        }}
      />
    </>
  );
};
```

### Possible implementations

Could be made similar to the onSubmit prop -- which also needs to receive values.

**Comment by diegohaz** [comment]
Hey @cbush! Thanks for creating this issue.

I didn't understand the motivation behind this. You just described the solution as the motivation. But which problem are you really trying to solve? Maybe there's a better way to do this. A CodeSandbox example would be appreciated.

**Comment by cbush** [comment]
Thanks for your reply. 

My onValidate needs to use props of the enclosing component.

In my app, the List component that has an array of Items. Let's say each Item has a form with an editable title. I'm not using Redux, so the pattern I've been using is passing 'actions' as callback props. So in this case `onUpdateItem` is passed as a prop to Item. When the form is validated, I want to update the List's items with something like
```
{items.map((item, index) => (
  <Item title={item.title} onUpdateItem={(item) => {
    const newItems = [...items];
    newItems[index] = item;
    setItems(newItems);
  }} />```

But, as illustrated, this just uses the `items` array as it was whenever that Item was first mounted.

I also want to do this in validate so that these props are updated as the user types or focuses out, not just when hitting submit.

Granted, I could be approaching this entirely the wrong way, so I'm open to discussion.

Your help is most appreciated!

**Comment by diegohaz** [comment]
I'll need more time to think on this, but one thing you can do today is to use a ref to store the updated value:

```jsx
function useLiveRef(value) {
  const ref = React.useRef(value);
  React.useEffect(() => {
    ref.current = value;
  });
  return ref;
}

function Component() {
  const [items, setItems] = React.useState([]);
  const itemsRef = useLiveRef(items);
  const form = useFormState({ onValidate: values => itemsRef.current... })
}
```

**Comment by cbush** [comment]
Thank you, that works perfectly.

I think I have an even more compelling example for why onValidate and onSubmit should be props. If you want to use _any_ prop in the onValidate or onSubmit callback, you would have to do something like above. Example:

```
const MyComponent = ({ count }) => {
  // takes callback as a prop
  const form = useFormState({
    // initialize form state
    values: { foo: "" },
    onValidate: () => {
      // Note this always prints 0, even though count is changing!
      console.log(count);
    }
  });
  return (
    <Form {...form}>
      <FormInput {...form} name="foo" placeholder="Edit me and check console" />
    </Form>
  );
};

const Example = () => {
  const [count, setCount] = useState(0);
  return (
    <>
      <Button onClick={() => setCount(count + 1)}>{count}</Button>
      <MyComponent count={count} />
    </>
  );
};
```
On that note, I see onSubmit actually can be used as a prop, but how does one access the values in that callback?

Thanks again for your attention to this! For now, the ref is working just fine.

**Comment by tom-sherman** [comment]
@cbush I believe the `onSubmit` prop is attached to the native `submit` DOM event, that's why it works as a prop.

**Comment by diegohaz** [comment]
Yep! If you pass `onSubmit` to `Form`, you're simply using the React event. It has nothing to do with Reakit, and by doing so you'll loose some Reakit Form features. This is the method that is passed to `<form onSubmit />` under the hood by Reakit: https://github.com/reakit/reakit/blob/be29f3b733b08798a8d6fe36f194da7ba62e78de/packages/reakit/src/Form/FormState.ts#L350-L372

**Comment by cbush** [comment]
Ah, makes sense. In that case, if you do decide to make onValidate a prop, it would be nice to also make onSubmit a genuine reakit prop.

I'm noticing the pattern of storing callbacks in hook state in other libraries now (specifically react-dnd). In a redux type of app this is probably never an issue because the callback will just fire off some action. The live ref is coming in handy!
