### ISSUE TITLE
Initial transition of Dialog isn't working

### ISSUE THREAD

**Issue by stramel** [reakit/reakit#401]
### Current behavior

The majority of the time when using the unstable animation API, it doesn't properly trigger initial transitions on Dialog/Sidebar.

### Steps to reproduce the bug

https://codesandbox.io/s/reakit-be2y4

### Expected behavior

It should transition open

### Additional Context

I used the Sidebar migration guide from #350 with @diegohaz's comment for animating it. https://github.com/reakit/reakit/issues/350#issuecomment-493121473

**Comment by diegohaz** [comment]
Hi @stramel. You should use the `.hidden` selector. I'm not sure it's documented, but it should be once the animated prop is stable.

```js
const SidebarContainer = styled(Dialog)`
  position: fixed;
  left: 0;
  top: 0;
  height: 100vh;
  overflow: auto;
  z-index: 999;
  outline: 0;
  transition: transform 0.3s ease-in-out;
  transform: translateX(0);
  &.hidden {
    transform: translateX(-100%);
  }
`;
```

**Comment by stramel** [comment]
Ah, much better! Thanks @diegohaz! Looking forward to documented & stable animation!

**Comment by stramel** [comment]
@diegohaz Is there anyways to target the entering vs exiting transitions? I was hoping to apply a different transition for enter vs exit.

**Comment by diegohaz** [comment]
I forked your sandbox and created an example with different transitions for entering and exiting states: https://codesandbox.io/s/reakit-enterleave-animation-ys3z3

But there are probably other ways to do that.

**Comment by stramel** [comment]
Perfect! Thank you again!

**Comment by stramel** [comment]
Perfect! Thank you again!
