### ISSUE TITLE
v1 Provider type requires `unstable_system` but optional according to docs

### ISSUE THREAD

**Issue by stramel** [reakit/reakit#403]
### Current behavior

Trying to use `Provider` for SSR in my project that uses Typescript. The typing on `Provider` is stating that `unsable_system` is required. The getting started documentation states that it is optional. https://reakit.io/docs/get-started/#server-side-rendering

### Expected behavior

I would expect to be able to use `Provider` without any props.

**Comment by diegohaz** [comment]
Thank you @stramel. It was fixed in 29c4456339306f020996c38276c2f9edf3f6697b and will be available in the next patch.
