### ISSUE TITLE
reakit-system error: Cannot find module 'reakit/Box/Box'

### ISSUE THREAD

**Issue by AndresRodH** [reakit/reakit#413]
### Current behavior

Following the [migration guide](https://github.com/reakit/reakit/issues/350) from v0 to v1 installing `reakit@1.0.0-beta.5` as `reakit-next`. `reakit-system` throws the following error:

```
TypeScript error in /Users/andresrodriguez/CFS/roadside-app/node_modules/reakit-system/src/createComponent.ts(3,30):
Cannot find module 'reakit/Box/Box'.  TS2307

    1 | // TODO: Refactor
    2 | import * as React from "react";
  > 3 | import { BoxHTMLProps } from "reakit/Box/Box";
      |                              ^
    4 | import { As, PropsWithAs } from "reakit-utils/types";
    5 | import { splitProps } from "reakit-utils/splitProps";
    6 | import { memo } from "./__utils/memo";
```

### Steps to reproduce the bug

1. Follow the [migration guide](https://github.com/reakit/reakit/issues/350) and use v 1.0.0-beta.5 as the version for reakit-next

### Expected behavior

Should not throw an error

### Environment

```sh
    reakit: ^0.16.0 => 1.0.0-beta.5 
    styled-components: ^4.3.2 => 4.3.2 
    typescript: ^3.5.2 => 3.5.2 
```

**Comment by diegohaz** [comment]
Hi @AndresRodH! Thanks for opening the issue.

I'll need some time to dig into this, but for now you can try to play with [Yarn resolutions](https://yarnpkg.com/lang/en/docs/selective-version-resolutions/). Maybe the following works:
```json
"resolutions": {
  "reakit-system/reakit": "1.0.0-beta.5"
}
```

You can also rename the old reakit version to something else and keep the new one intact, but this will require more work unfortunately.

**Comment by AndresRodH** [comment]
@diegohaz Unfortunately yarn resolutions didn't work :( I can always wait until this is resolved to migrate to v1.

**Comment by AndresRodH** [comment]
@diegohaz Thanks for getting into this so quickly! Do you have an estimate for a release that includes this fix? I am getting some work ahead by manually adding the BoxHTMLProps type to reakit-system

**Comment by diegohaz** [comment]
Next release will be this weekend. Sorry for the delay.

**Comment by AndresRodH** [comment]
Don't be! Thanks for this great lib :)
