### ISSUE TITLE
Form: File fields are object-ified on submit

### ISSUE THREAD

**Issue by ahdinosaur** [reakit/reakit#415]
hi `reakit` folx! :smiley_cat: 

### Current behavior

If a field contains a value that is any type of object, it will be converted into a plain object by [`filterOnEmpty`](https://github.com/reakit/reakit/blob/master/packages/reakit/src/Form/__utils/filterAllEmpty.ts) as used in [`submit`](https://github.com/reakit/reakit/blob/master/packages/reakit/src/Form/FormState.ts#L364).

For my use case, I want to use a custom field where the field's value is a `File` object, but currently on submit this is converted to a plain object, so the `onSubmit` callback receives the object-ified value.

### Expected behavior

For my use case, I'd like the `onSubmit` callback to receive values matching the current `form.values`.

### Possible solutions

I made a simple fork which works for my use case: https://github.com/ahdinosaur/reakit/commit/1a087b457ded7a7e45f2ccfaa0f42e42895f0bb5#diff-9bd4c653b00790c2eb1e8f7c0f580a96, where `filterOnEmpty` only recurses into plain objects.

If this is an appropriate fix, happy to make a pull request. Also happy to follow any guidance on how to make a better change.

:heart:

**Comment by diegohaz** [comment]
Hi @ahdinosaur!

Thanks for opening the issue and working on a solution. There may be some improvements, but I guess that works. Feel free to open a PR.

**Comment by diegohaz** [comment]
Hi @ahdinosaur! Are you still willing to work on this? :)
