### ISSUE TITLE
with next.js(server side render) warning: Prop `aria-controls` did not match. Server: "hidden-tt4h6d" Client: "hidden-vlpmbp"

### ISSUE THREAD

**Issue by rumsky** [reakit/reakit#416]
## 🐛 Bug report
with next.js(server side render) warning: Prop `aria-controls` did not match. Server: "hidden-tt4h6d" Client: "hidden-vlpmbp"

### Current behavior
using MenuDisclosure and Menu, there is a warning:Prop `aria-controls` did not match. Server: "hidden-tt4h6d" Client: "hidden-vlpmbp"

### Environment
"next": "^9.0.3",
"reakit": "^1.0.0-beta.5",
"styled-components": "^4.3.2"

**Comment by rumsky** [comment]
Because I want to tirgger by 'hover', I add  onMouseEnter / onMouseLeave on MenuDisclosure, then the warning occurred. If I remove onMouseEnter / onMouseLeave the warning disappear

`<MenuDisclosure
          {...menu}
          onMouseEnter={() => {
            setVisible(true);
          }}
          onMouseLeave={() => {
            setVisible(false);
          }}>
          Preferences
        </MenuDisclosure>`

**Comment by rumsky** [comment]
on Server console warning :
Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format. This will lead to a mismatch between the initial, non-hydrated UI and the intended UI. To avoid this, useLayoutEffect should only be used in components that render exclusively on the client. See https://fb.me/react-uselayouteffect-ssr for common fixes.

**Comment by diegohaz** [comment]
Hi @rumsky! Thanks for opening the issue.

Are you using [Provider](https://reakit.io/docs/get-started/#server-side-rendering)?

Regarding the other warning, could you please provide a repository or CodeSandbox with the code?

**Comment by rumsky** [comment]
here is respo:
https://github.com/rumsky/next-with-reakit
In _app.js I add Provider, but error still have error in both client and server side.

**Comment by rumsky** [comment]
Update:
I add babel-plugin-styled-components and .babelrc , the client error resolved，but server still error.
`
Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format. This will lead to a mismatch between the initial, non-hydrated UI and the intended UI. To avoid this, useLayoutEffect should only be used in components that render exclusively on the client. See https://fb.me/react-uselayouteffect-ssr for common fixes.
`

**Comment by diegohaz** [comment]
@rumsky Thanks for the reproduction!

So, the ID mismatch between server and client has gone?

That one about `useLayoutEffect` is just a warning, but I'm gonna take a better look at it over the next week.

**Comment by rumsky** [comment]
Yup, the ID mismatch between server and client has gone`
useLayoutEffect` still exist

**Comment by diegohaz** [comment]
So, I've checked all the uses of `useLayoutEffect` we have in Reakit. None of them is supposed to run on the server, but they do need to run before the next painting, so `useEffect` wouldn't work.

That said, that warning can be ignored.

**Comment by rumsky** [comment]
Could you resolve the warning?If this library support SSR,I think it's better resolve 'useLayoutEffect' warning. There are too many warning in server console, It's hard to find important information，very annoying

**Comment by vvo** [comment]
Not sure what can be done here, but ignoring warnings is usually not the preferred solution for developers trying to get rid of warnings.

I guess one way to solve it in userland would be to load dynamically the component maybe? Like with Next.js dynamic import: https://nextjs.org/docs/advanced-features/dynamic-import

**Comment by diegohaz** [comment]
@vvo This is an old issue. The warning I suggested we should ignore (`useLayoutEffect` on the server) doesn't exist anymore. If you're referring to the ID mismatch warning, please see #844.
