### ISSUE TITLE
textarea : Can't put caret at a specific position when focusing 

### ISSUE THREAD

**Issue by efflam** [reakit/reakit#418]
### Current behavior
When using `FormInput` as `textarea` and if there is already some text inside the input, it's impossible to put the caret at a specific position on focus.

### Steps to reproduce the bug
The bug can be experienced on the form docs page.
Use `FormInput` as `textarea` as described in the docs
```
<FormInput
        {...form}
        name="message"
        placeholder="What's on your mind?"
        as="textarea"
      />
```

### Environment
Chrome, Safari at least

**Comment by diegohaz** [comment]
Thanks for reporting it @efflam!

I believe that we should add `HTMLTextareaElement` here:
https://github.com/reakit/reakit/blob/ee9623e4607ca2331563e2a44cc51ef6a874e438/packages/reakit/src/Tabbable/Tabbable.ts#L80
