### ISSUE TITLE
Ability to trigger Dialog programmatically 

### ISSUE THREAD

**Issue by stramel** [reakit/reakit#425]
### Motivation

I'm using the `Dialog` to build an AlertDialog that I want to trigger when someone tries to change location or when they are in an "edit" state. Triggering this programmatically would make things easier than trying to wrap a button.

**Comment by diegohaz** [comment]
Hey @stramel. See if this helps you: https://spectrum.chat/reakit/general/opening-an-alert-programmatically~e4528a6e-8209-4d55-a519-ef2a7a03d77e

**Comment by stramel** [comment]
@diegohaz That will work, didn't see `show` documented anywhere.
