### ISSUE TITLE
Feature request: Exposes Portal Context

### ISSUE THREAD

**Issue by lxcid** [reakit/reakit#428]
### Motivation

I was wondering what do you think about exposing the `PortalContext` so that we can control where portal should live in the DOM. This might be useful if I want to manage the root level DOM elements.

I'm not sure if hiding PortalContext is something you explicitly wanted and have a reason for. If so, could you share your thoughts?

### Example

Using `LayersManager` (https://github.com/giuseppeg/react-layers-manager/blob/master/src/LayersManager.js) as an example:

```js
export default class LayersManager extends React.Component {
  root = React.createRef()
  host = React.createRef()
  state = {
    root: this.root.current,
    host: this.host.current,
  }
  componentDidMount() {
    this.setState({
      root: this.root.current,
      host: this.host.current,
    })
  }
  render() {
    return (
      <PortalContext.Provider value={this.state.host}>
        <Provider value={this.state}>
          <div ref={this.root} style={{ opacity: 0.9999999 }}>
            {this.props.children}
          </div>
          <div ref={this.host} style={{ opacity: 0.9999999 }} />
        </Provider>
      </PortalContext.Provider>
    )
  }
}
```

Any portal created inside the `children` will be append as child of `host`. And nested portal will still function as designed.

### Possible implementations

Just need to `export PortalContext`?

**Comment by diegohaz** [comment]
Hi @lxcid! Thanks for opening the issue!

I think the only reason for not exposing this was the lack of use cases. You're bringing one to light right now, so I think we should add that.

Would you like to do that?

**Comment by lxcid** [comment]
Thanks Haz! I see, I’m not sure yet about my use case, but I believe some people might be concern about where their portal get created inthe DOM tree. If you have no objection I can send a small PR once I get home.

btw, I love your portal implementation. I’ve been looking around and I think yours is the best one. 👍
