### ISSUE TITLE
Out of beta roadmap

### ISSUE THREAD

**Issue by diegohaz** [reakit/reakit#429]
Reakit v1 reached to the point that it's pretty stable in terms of functionality and lack of bugs. But there is a few things I'd like to address before getting it out of beta. I'm gonna use this issue to track them:

- [x] **`Menu` components naming**

  `StaticMenu` should become `MenuBar`. And there should be a `useMenuBarState`. `Menu` will compose from `MenuBar` (same as today with `StaticMenu`), and `useMenuState` will be a combination of `useMenuBarState` and `usePopoverState`.

- [x] **Browser support**

  We should make sure Reakit (the core `reakit` library at least) supports all the major browsers, but also IE 11, with automated tests (maybe using BrowserStack). That's a requirement in my current job, so I'm gonna focus on this over the next couple of weeks. Related to #360.

- [ ] **Performance**

  Components already have good performance, but I'm a little bit concerned about `Menu` when there are lots of `MenuItem`s or sub menus. We have to find a way to automate performance testing and improve `Menu`.

**Comment by lluia** [comment]
> Components already have good performance, but I'm a little bit concerned about Menu when there are lots of MenuItems or sub-menus. We have to find a way to automate performance testing and improve Menu.

@diegohaz what type of performance issue you refer to? ( _scrolling?_ )

I think we could use **Storybooks** for it having a story that renders a very large menu, or an example on the website 🤔

**Comment by diegohaz** [comment]
It's mostly when you keep arrow keys pressed. A big improvement has been made on f5546009dd3f64dbc327a89fd4a391061514b6da, and #615 has more improvements and a story with a large menu bar. I think there's nothing else actionable here.

![May-20-2020 07-00-27](https://user-images.githubusercontent.com/3068563/82433294-9f1cdf80-9a67-11ea-83b1-8d3937aac0c6.gif)
