### ISSUE TITLE
Button `:active` styles not applied in Firefox

### ISSUE THREAD

**Issue by folz** [reakit/reakit#432]
### Current behavior

When clicking on a Button in Firefox, the hover styles are applied on hover but the active styles are not applied on click.

When using Chrome, the active styles are applied correctly on click.

### Steps to reproduce the bug

1. In Firefox, navigate to https://reakit.io/docs/button/
2. Click the Button

### Expected behavior

The active styles should be applied, as they are in Chrome.

### Possible solutions

¯\\_(ツ)_/¯ 

I did notice that you perform a variety of checks on the onMouseDown handler of Tabbable, it's possible that one of those event.preventDefaults() is somehow preventing Firefox from thinking the Button is being clicked?

### Environment

Verified locally and via Browserstack on Firefox 69 (latest) on both Windows 10 and Mac Mojave

**Comment by diegohaz** [comment]
Thank you for opening the issue, @folz! :)

I confirm that this is the line that is preventing Firefox from setting the `:active` state on any `Tabbable` component (including `Button`):
https://github.com/reakit/reakit/blob/efaa95e2090853fa70c401487f0173c6cb684738/packages/reakit/src/Tabbable/Tabbable.ts#L98

I'm still not sure how to fix that. That `preventDefault` is necessary so we can consistently set focus on buttons when they get clicked (currently, some browsers set focus, others don't).

**Comment by folz** [comment]
Gotcha, I appreciate the time you spent looking into it.

I came across https://github.com/w3c/csswg-drafts/issues/2262, which links to two other Firefox bugs [[one]](https://bugzilla.mozilla.org/show_bug.cgi?id=1430196) [[two]](https://bugzilla.mozilla.org/show_bug.cgi?id=771241). It appears that, unlike other browsers, Firefox considers the `:active` state finished once `preventDefault()` is called, so there is not really a way to both use `preventDefault` and have the `:active` pseudoclass. Same thing would apply to the `:hover` pseudoclass if reakit called preventDefault on that event.

Since I am mainly interested in applying styles,

**Comment by folz** [comment]
I wrote a PR to demonstrate how `data-active` might be applied, as I think that a consistent visual `active` state is closely related to accessibility and is something that Reakit should consider addressing across browser differences.

However, I get that this might be outside the scope of what you want Reakit core to ship with, so please feel free to close the PR and I'll introduce those changes locally to my repo.

**Comment by diegohaz** [comment]
I posted a Twitter thread about turning Reakit buttons into divs: https://twitter.com/diegohaz/status/1176998100495491072

Getting rid of this `onMouseDown` will potentially fix this problem and #448
