### ISSUE TITLE
Feature Request: Allow to move focus across items of a grid

### ISSUE THREAD

**Issue by iagobruno** [reakit/reakit#435]
### Motivation

I was building an interface with a cards grid and wanted the user to be able to navigate in these cards nonlinearly using the arrow keys. I looked for something to help me in the documentation and here in the repository and even found that in the past Reakit had a [Grid component](https://github.com/reakit/reakit/blob/v0.14.0/src/components/Grid/Grid.js) but it was removed. Anyway, I implemented a solution by myself but here is the proposal for you to evaluate.

### Current behavior

Currently, [`Rover`](https://reakit.io/docs/rover/) components can be grouped horizontally or vertically and the [`useRoverState`](https://reakit.io/docs/rover/#useroverstate) hook will move focus across items linearly, respecting the chosen orientation. 

```js
function Component() {
  const rover = useRoverState();

  return (
    <Group>
      <Rover {...rover} as={Tabbable}></Rover>
      <Rover {...rover} as={Tabbable}></Rover>
      <Rover {...rover} as={Tabbable}></Rover>
    </Group>
  )
}
```

![cats](https://user-images.githubusercontent.com/3616259/65008721-a9874800-d8e0-11e9-8faf-dda3b11991ea.jpg)

### Proposal

Add a new "grid" value to the orientation option of `useRoverState` hook that lets you move focus freely in any direction through the Rover components in a grid.

```js
function Component() {
  const rover = useRoverState({
    orientation: 'grid',
    columns: 3 // Number of columns for hook calculate which item is above and below.
  });

  return (
    <Group className="grid">
      <Rover {...rover} as={Tabbable}></Rover>
      <Rover {...rover} as={Tabbable}></Rover>
      <Rover {...rover} as={Tabbable}></Rover>
      <Rover {...rover} as={Tabbable}></Rover>
      <Rover {...rover} as={Tabbable}></Rover>
      <Rover {...rover} as={Tabbable}></Rover>
    </Group>
  )
}
```

![cats2](https://user-images.githubusercontent.com/3616259/65009444-17cd0a00-d8e3-11e9-8112-39174146533b.jpg)

### Possible implementations

I think [this answer](https://stackoverflow.com/a/15674160/2789759) in StackOverflow can help you when implementing the new logic.

**Comment by diegohaz** [comment]
Thank you for opening the issue, @httpiago!

A `Grid` component is planned. It will follow the [WAI-ARIA Grid Pattern](https://www.w3.org/TR/wai-aria-practices/#grid). And the API I'm thinking on is something like this:
```jsx
const grid = useGridState();
return (
  <Grid {...grid}>
    <GridRow {...grid}>
      <GridCell {...grid}>Row 1 / Col 1</GridCell>
      <GridCell {...grid}>Row 1 / Col 2</GridCell>
      <GridCell {...grid}>Row 1 / Col 3</GridCell>
    </GridRow>
    <GridRow {...grid}>
      <GridCell {...grid}>Row 2 / Col 1</GridCell>
      <GridCell {...grid}>Row 2 / Col 2</GridCell>
      <GridCell {...grid}>Row 2 / Col 3</GridCell>
    </GridRow>
  </Grid>
);
```

It's open for discussion though. So feel free to suggest a different idea.

cc @Saeris

**Comment by Saeris** [comment]
Would there be any way we could make this work with CSS Grid? I'm not thrilled about the idea of specifying rows and columns in the HTML markup, because then re-flow logic would have to be calculated as different break-points are reached.

I realize that would be far from simple to implement, I just have to point it out as a major concern of mine for implementing a responsive arrow-key navigable grid.

**Comment by diegohaz** [comment]
As per the [spec](https://www.w3.org/TR/wai-aria-1.1/#gridcell), grid cells should be contained within a [row](https://www.w3.org/TR/wai-aria-1.1/#row). This serves as a hint for screen readers announce the exact position of the cell in the grid when it's focused.

But automatically identifying the positions of the elements on the viewport would be cool as well. A solution could be adding the row elements automatically to the DOM. I don't know how good/bad is it.

**Comment by httpiago** [comment]
@diegohaz I liked your suggestion of creating new Grid components, it is more elegant than my idea. A real implementation example would be:

```js
import { chunk } from 'lodash'

const items = ['one', 'two', 'three', 'four', 'five', 'six']

function Component() {
  const grid = useGridState();
  const rows = React.useMemo(() => chunk(items, 3), []);

  return (
    <Grid {...grid}>
      {rows.map(cols => (
        <GridRow {...grid}>
          {cols.map(cell => (
            <GridCell {...grid}>{cell}</GridCell>
          ))}
        </Grid>
      ))}
    </Grid>
  );
}
```

But I agree with @Saeris, it would be interesting to avoid setting breakpoints manually and leave it to CSS to define.

**Comment by tom-sherman** [comment]
I've played around with hacking something together in userspace and you can support a subset of Grid keyboard navigation functionality relatively easily: https://codesandbox.io/s/keen-morse-me8jp

Disclaimer: I hacked this together in a morning and I'm not sure how accessible or performant it is, you probably don't wanna use this in production as-is.

**Comment by diegohaz** [comment]
Ah, missed this one. This is actually supported now with [Composite](https://reakit.io/docs/composite/#two-dimensional-navigation) and, more specifically, the experimental [Grid](https://reakit.io/docs/grid/) module.
