### ISSUE TITLE
PopoverDisclosure could probably have a better name

### ISSUE THREAD

**Issue by Slapbox** [reakit/reakit#441]
Super trivial, but the longer I've coded the more I've found that trivial naming issues from my past later drive me nuts.

I don't know that any of these are better, but I feel certain there's a better name for this out there.

**Possible Alternatives:**

- PopoverIndicator
- PopoverHint
- PopoverTrigger
- PopoverOpener

**Comment by diegohaz** [comment]
Hi @Slapbox! May I know why you think `Disclosure` is a bad name?

It's based on the [WAI-ARIA Disclosure Pattern](https://www.w3.org/TR/wai-aria-practices/#disclosure):
> A disclosure is a button that controls visibility of a section of content.

That's also a standard across the library: [`HiddenDisclosure`](https://reakit.io/docs/hidden/), [`MenuDisclosure`](https://reakit.io/docs/menu/), [`DialogDisclosure`](https://reakit.io/docs/dialog/).

An alternative name could be `Button`. It makes more sense with `MenuButton` (there's even a [dedicated section for "menu button"](https://www.w3.org/TR/wai-aria-practices/#menubutton) on the WAI-ARIA Authoring Practices), but less sense with `HiddenButton`, for example.

**Comment by Slapbox** [comment]
disagree with their choice in that case, but have no doubt that it was well considered and you're totally right to follow their guidelines. 

I think you were right to identify it as most closely fitting the criteria laid out for `Disclosure` and not `Menu Button`.

Keep up the amazing work!
