### ISSUE TITLE
Popover placement behavior changed from v0 to v1 causing popover to leave viewport

### ISSUE THREAD

**Issue by Slapbox** [reakit/reakit#446]
### Current behavior

Popover is always popping down to the right in my configuration, off the screen.

All placement options yield the following identical `transform` on the popover container element:

```
transform: translate3d(-6px, 40px, 0px);
```

### Steps to reproduce the bug

_To be provided later_

### Expected behavior

Popover with `placement: 'left'` should pop left. I tried using `unstable_flip`, expanding the containing element, changing the `display` property of the `<PopoverDisclosure />` - unfortunately the popover always goes down to the right, out of the viewport.

### Possible solutions

Unknown

### Environment

```sh
$ npx envinfo --system --binaries --npmPackages

  System:
    OS: Windows 7
    CPU: (2) x64 Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz
    Memory: 5.09 GB / 13.75 GB
  Binaries:
    Yarn: 1.17.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.2.0 - C:\Users\Remie\AppData\Roaming\npm\npm.CMD

```

**Comment by Slapbox** [comment]
I've been trying to find a way to recreate this all morning both in online sandboxes from scratch and by mangling and reverse engineering my own code, but no luck. All I've got right now is this very demonstration of a `Popover` using `placement: 'left-start'`

https://recordit.co/9X4KpO2Hdm

There's adequate room in all directions around the element for the `Popover` to display. In my environment it doesn't matter whether the containing element has adequate space, whether I position the button using `margin`, `padding`, `flex`, or any other attempt I've made.

I'm using React hot loading, and if I save changes while the popover is open, it moves to the proper position, but on re-opening it opens in the wrong location again. [Video (takes a few seconds for anything to change at the start due to waiting for hot-loader)](https://recordit.co/Yej9xGBYfl)

**Comment by Slapbox** [comment]
I'm noticing nothing I do with `unstable_flip` seems to be valid.

I get the following error for every attempt:

```
Warning: Received `true` for a non-boolean attribute `unstable_flip`.

If you want to write it to the DOM, pass a string instead: unstable_flip="true" or unstable_flip={value.toString()}.
```

**I've tried each of these with the same results:**
- `unstable_flip`   
- `unstable_flip={true}`   
- `unstable_flip="true"`

**Comment by diegohaz** [comment]
I have no idea what it could be. Could you try `reakit@1.0.0-beta.8`? It has a bug fix on `Popover` related to another issue, but there's a chance that it'll work for your issue too.

**Comment by Slapbox** [comment]
That gets things much closer! I think there's still some discrepancy between `v0` and `v1`, but it could be a configuration issue on my point at this point. Still tinkering.

Are valid placements the same as [used by Popper.js](https://popper.js.org/popper-documentation.html#Popper.placements)?

**Comment by Slapbox** [comment]
It's fixed!
