### ISSUE TITLE
Remove open Dialog flicker

### ISSUE THREAD

**Issue by namjul** [reakit/reakit#449]
### Motivation

`body-scroll-lock` has the option `reserveScrollBarGap` the preserve scrollbar-width.
If this gets enabled the dialog would not flicker when opening it.
https://github.com/willmcpo/body-scroll-lock#reservescrollbargap

### Possible implementations

Could be enabled here:
https://github.com/reakit/reakit/blob/master/packages/reakit/src/Dialog/__utils/usePreventBodyScroll.ts#L16

**Comment by diegohaz** [comment]
Thank you! Would you like to send a PR for that?
