### ISSUE TITLE
Expand usability of primitives in styled-components/emotion

### ISSUE THREAD

**Issue by Slapbox** [reakit/reakit#451]
### Motivation

Improve composability of styles for elements. You're no doubt aware that with `emotion` you can do something like below. I don't know if it's possible, but it would be really cool and helpful to be able to use Reakit primitives in these sorts of situations. (Though I'm feeling 50/50 on @diegohaz swooping in and schooling me on why this isn't necessary because there's a better pattern, which I welcome.)

```js
import styled from '@emotion/styled';

const Button = styled.button``
const Input = styled.input`
  text-align: center;

  & + ${Button} {
    margin-left: 0.5rem;
  }
`;

```

### Example

```js
import { Button } from 'reakit';
import styled from '@emotion/styled';

const Input = styled.input`
  text-align: center;

  & + ${Button} {
    margin-left: 0.5rem;
  }
`;
```

### Possible implementations

Possible to leverage the way `styled` already does this with its own primitives and composed elements? I'm guessing not.

**Comment by diegohaz** [comment]
I think the easiest way to do that is wrapping Reakit components on your app:
```js
import { Button as ReakitButton } from "reakit";
import styled from "@emotion/styled";

export const Button = styled(ReakitButton)``;
```
```js
import styled from '@emotion/styled';
import Button from "../Button";

const Input = styled.input`
  text-align: center;

  & + ${Button} {
    margin-left: 0.5rem;
  }
`;
```
