### ISSUE TITLE
PopoverArrow size prop doesn't work

### ISSUE THREAD

**Issue by SpadarShut** [reakit/reakit#454]
### Current behavior
passing size prop to `PopoverArrow` doesn't work. It just sets the size attribute in the DOM node, but actual size is still 30.

### Steps to reproduce the bug

https://codesandbox.io/s/reakit-sspbs

### Expected behavior

Arrow size should change and the size prop should not be on the DOM node.

**Comment by diegohaz** [comment]
Thanks for reporting this issue! That will be fixed in the next release! In the meanwhile, you can override `style.fontSize` on the component:
```jsx
<PopoverArrow style={{ fontSize: 50 }} />
```
