### ISSUE TITLE
Form onValidation shouldn't throw

### ISSUE THREAD

**Issue by rumkin** [reakit/reakit#468]
## Enhancement

Current form onValidation property has two design issues: 1. It throws. 2. It throws non-error.

First, validation method shouldn't throw it should return a report/explanation why data is invalid. Programmer should decide what to do with this report and probably throw exception. Validation should throw only when something went wrong like invalid options were passed.

Second, throwing non-error object leads is an error-prone behavior due to lack of stack it could lead to hard to track bugs. It seems ok while you control the code within you component, but it still a very bad design.

### Motivation

Avoiding this allow to create some unified method, which could be used anywhere outside of the component without a single change.

### Possible implementations

It's better when validation method returns an array of issues, and have the next interface:

```typescript
type Validator = (any, object?): Array<Issue>

type Issue = {
  path: Array<string|number>
  rule: string
  details: object
}
```

Simple number validator:

```typescript
function validateNumber(value:any):Array<Issue> {
  if (typeof value === 'number') {
    return []
  }
  else {
    return [
       {rule: 'isNumber', path: [], details: {expect: true, is: false}}
    ]
  }
}
```

Such issues could be used with i18n package. Its' creation could be wordy, but it solvable with factory methods.

You can check how this implemented on practice at [TypedProps package](https://github.com/rumkin/typed-props).

**Comment by diegohaz** [comment]
Thank you for opening the issue @rumkin!

I still don't have opinions about this. But researching a bit, I see that Formik also throws: https://github.com/jaredpalmer/formik/blob/5bae8e05f60e1801d8740317a38c2992f7750470/src/Formik.tsx#L722

Just putting here for future reference.

**Comment by jperasmus** [comment]
+1 for non-throwing validation. API's I've used in the past that I liked is if the validation method returns `undefined`/`null` for no issues and a record of failing fields with their errors (array). Similar to how https://validatejs.org/#validate does it.

**Comment by rumkin** [comment]
@diegohaz I mean that validator itself shouldn't throw its result. The result of validation method call should be returned. And the error should be thrown only when something unexpected happen. But, when you try to send (or use somehow) the data that hasn't pass the validation, then you should throw.

Throwing non-errors considered as anti-pattern/bad practice anyway. Here are references in eslint and bluebird documentations:
* [Eslint's](https://eslint.org/docs/rules/no-throw-literal) in the first paragraph.
* [Bluebird's](http://bluebirdjs.com/docs/warning-explanations.html#warning-a-promise-was-rejected-with-a-non-error) special paragraph.

**Comment by diegohaz** [comment]
Similar thread on Yup: https://github.com/jquense/yup/issues/144

The only difference is that Yup throws an actual [error object](https://github.com/jquense/yup/blob/1426feceb6c5544c526711bedcf388afaf6115b9/src/ValidationError.js), which is something we could do here as well.

**Comment by diegohaz** [comment]
@rumkin 
> I mean that validator itself shouldn't throw its result. The result of validation method call should be returned.

You mean something like this?
```jsx
const form = useFormState({
  onValidate(values, { setErrors, setMessages }) {
    ...
    // instead of throw errors;
    setErrors(errors);
  }
});

// is it OK if this throws?
form.validate();
```

**Comment by rumkin** [comment]
@diegohaz I mean something like this:

```js
const from = useFormState({
  onValidate(values) {
    // ...
    return errors
  }
})

form.isValid // -> false
form.submit() // throws, due to isValid is false
```

**Comment by diegohaz** [comment]
How would you handle the concept of messages that aren't errors?

For example, when validating an `username` field you could either return `Username already exists` or `Username available`.

**Comment by rumkin** [comment]
Now I've got what you want. In this case seems logical to return validation messages like this:

```ts
enum ReportType {
  error,
  warning,
  success,
}

interface Report {
  type: ReportType
  path: Array<string|number> // Path to property for nested forms
  message: string
}
```

If there is a report with type equal to `error`, then isValid flag became false and form submitting blocks. 

But I don't see any reason to stop here. Report's message could support react components. It allows to return controls for fixing the issue: it could be a list of valid values to select, a button to restore previous correct value, etc.

**Comment by tecfu** [comment]
This issue should be labeled as a security flaw, in addition to being labeled as an enhancement. 

See here: https://github.com/jquense/yup/issues/144#issuecomment-581583304

**Comment by rumkin** [comment]
There is another throw-less validation realized in Angular. It has a validator interface which produces an Object with the errors occurred while validation ([Angular's documentation](https://angular.io/guide/form-validation#custom-validators)).

Here is how it looks:
```jsx
function validateNameLength(name) {
    if (name < 2) {
        return {minLength: 2}
    }
    else if (name > 20) {
       return {maxLength: 20}
    }
    else {
       return null
    }
}
```

I don't like the idea to return objects (instead of array of issues), but it illustrates that library developers had chosen non-throwing design and still use it after 8 years of development and many breaking changes they made in the project.

**Comment by Guria** [comment]
Follow up from #661 
I do agree with no throw API proposed here, just because we have a big confusion by treating Validation Error as Runtime Error. But semantically it is just a state (even might be a derived state) of the form. And using throw here is just like using `goto` operator.

One possible option I was thought about is to return instance of either `FormErrors` or `FormMessages`. Than callee could use instanceof checks to detemine whether it is errors or messages. Drawback for this option is that instanceof checks are not working for objects from another document (eg, iframe) as I remember. Another drawback is that it wouldn't possible to have message on one field and error on another, just like in current solution.

So actually I like https://github.com/reakit/reakit/issues/468#issuecomment-557598586 with `form.validate()` not throw on validation errors too.

I'd like to propose to move out forms to separate package like `reakit-forms` since it contains a pretty opinionated way to define form state.

**Comment by Guria** [comment]
Can I take this issue for myself?

**Comment by diegohaz** [comment]
@Guria Sure!

**Comment by Guria** [comment]
> @Guria Sure!

Should we discuss a direction/target API first?
What about moving to a separate package?

I have also a question, why there is no Input primitive outside Forms. Is it intentional?

**Comment by diegohaz** [comment]
Why do you think it should be a separate package? (I’m not against it, just trying to understand the reasoning)

It’s not intentional that there’s no Input primitive. There should be one eventually. It’s just not one of my priorities right now, but I will review and accept PRs on it.

Regarding the API, I tend to prefer throwing an error class like you suggested in the other issue, but I’m all open for suggestions.

**Comment by Guria** [comment]
> Why do you think it should be a separate package

Form management may be built on top of the base reakit primitives very differently. Consumer might prefer to use any 3rd party for bunch of reasons (some company standard, api doesn't fit needs, etc).
Reakit may (should) provide own opinionated way to manage forms still, but moving it as separate package allows to have own versioning and continue exploring and experimenting without affecting base library.

> It’s not intentional that there’s no Input primitive. There should be one eventually. It’s just not one of my priorities right now, but I will review and accept PRs on it.

Should we start another issue to discuss expected API of Input primitive?

> Regarding the API, I tend to prefer throwing an error class like you suggested in the other issue, but I’m all open for suggestions.

Ok, I will use this issue to provide more pros/cons for different options here then.

**Comment by diegohaz** [comment]
> Form management may be built on top of the base reakit primitives very differently. Consumer might prefer to use any 3rd party for bunch of reasons (some company standard, api doesn't fit needs, etc).
Reakit may (should) provide own opinionated way to manage forms still, but moving it as separate package allows to have own versioning and continue exploring and experimenting without affecting base library.

Got it! The base library (`reakit`) has been designed so modules don't affect each other. Everything is treeshakeable, and you can always import individual modules like `reakit/Form` (or even deeper like `reakit/Form/FormInput`).

And, of course, you can choose not to use that specific modules in favor of any third party form library out there. If we come up with more primitive components like `Input`, people could combine it with those other libraries.

> Should we start another issue to discuss expected API of Input primitive?

Sure! I think the first question to answer is "what would that do that a simple `<input>` already doesn't?".

Unless we add some sort [editable content](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Editable_content) support when people do things like `<Input as="div">`, it's unclear to me how people could benefit from the `Input` component. But I haven't put much thought into that yet, so I'm probably missing something.

> Ok, I will use this issue to provide more pros/cons for different options here then.

Thanks! I appreciate that! Again, I don't have any strong opinion about this.

**Comment by Guria** [comment]
> Everything is treeshakeable

I see your point here, but my point was more about versioning. With separate package you can introduce a breaking change into forms (experimetal and opinionated) part and bump major only for this exact package without affecting base package which is tend to be much more stable.

**Comment by diegohaz** [comment]
> I see your point here, but my point was more about versioning. With separate package you can introduce a breaking change into forms (experimetal and opinionated) part and bump major only for this exact package without affecting base package which is tend to be much more stable.

Oh yeah! Right now it's being "solved" by prefixing the module with `unstable_`. And I think it's a matter of how many subjetive decisions we want to make.

With this naming approach, we can say that every new module should start as unstable/experimental, so there's no hard decision to make here.

But we do have one subjective decision to make: when will this module become stable? For [Composite](https://reakit.io/docs/composite/), which will be stable in `v1.1.0`, this means that it's being used in production in a large project (WordPress) and all major issues and API decisions were already made and tested.

If we start having modules as separate packages, the subjective decisions we would have to make would increase: should this new module be in a separate package? Will it eventually be integrated into the base library? etc.

And the same question remains: when will this module become stable?

I don't discard this option (there's even a `@reakit` npm scope available if we want to separate the library into more packages in the future). But right now I think separate packages should be used:

1. When the component is built on top of other dependencies that don't make sense being in the base library. For example, [reakit-playground](https://github.com/reakit/reakit/tree/c1d05deb3261d526dd9cddb87aed2f2dd5054194/packages/reakit-playground) depends on `buble`, `codemirror` and `emotion`.

2. When the component API is too different or doesn't follow what's described in our [basic concepts](https://reakit.io/docs/basic-concepts/), with components always rendering only one element and with state hooks exposed as a separate function.

    That would be the case, for example, if we come up with a high level component like `<Calendar />` that abstracts all the internal components instead of exposing them separately.

I don't think that's the case, at least with the current Form API, which still follows the library's basic concepts. If we want to experiment with completely different APIs, though, I agree that a separate package would be better.

**Comment by Guria** [comment]
Totally valid points. Completely agree with your criteria, that is what I thought too. And I do agree about forms that it is subjective on whether it should be extracted or not. So if you feel that it is better,  lets keep it as is for now.
