### ISSUE TITLE
MenuItemCheckbox and MenuItemRadio don't get checked

### ISSUE THREAD

**Issue by davidbarker** [reakit/reakit#472]
### Current behavior

MenuItemCheckbox and MenuItemRadio appear in the menu as items, but nothing is checked (no dot or tick), and clicking on any of the items doesn't check any items.

### Steps to reproduce the bug

Bug occurs in the documentation (https://reakit.io/docs/menu/#menu-bar) and also in the sandbox I recreated using the documentation code (https://codesandbox.io/s/reakit-2qm1d).

### Expected behavior

Clicking on an item should change its checked attribute. Changing the attributes in the HTML DOM manually does show a dot/tick, so it doesn't appear to be an issue with the CSS.

**Comment by diegohaz** [comment]
Thanks for reporting it @davidbarker! It'll be fixed in the next version.

As an alternative, it's more verbose, but you can also pass `onChange` and `checked` by yourself:
```jsx
const [value, setValue] = React.useState();
<MenuItemCheckbox onChange={() => setValue("a")} checked={value === "a"} />
```

**Comment by davidbarker** [comment]
You’re welcome — thanks for a great library!
