### ISSUE TITLE
Can HiddenDisclosure be based on anything other than a button?

### ISSUE THREAD

**Issue by thefrontendwizard** [reakit/reakit#478]
I have a case where I need a slightly more complex component to toggle a popover, can this be achieved currently on reakit?

**Comment by diegohaz** [comment]
@thefrontendwizard It's hard to answer without an example :(
Gonna close this for now. Please, use [Spectrum](https://spectrum.chat/reakit) or [StackOverflow](https://stackoverflow.com/questions/tagged/reakit) for usage questions.
