### ISSUE TITLE
Popovers get blurry when zooming out with browser

### ISSUE THREAD

**Issue by Slapbox** [reakit/reakit#482]
I guess this is just an inevitable fact of using `transform-3d`, but I found it curious that `unstable_portal` actually produces blurrier results, and I wondered if we know why that might be. Other than that one issue I've personally had better luck with `unstable_portal` than without.

I assume there's no good alternative to `transform-3d` here?

### Zoom 100%: 
![image](https://user-images.githubusercontent.com/6835891/68435476-5d8eac00-0189-11ea-8879-c850967dcfda.png)

### Zoom 90%

Left side: normal popover --- Right side: `unstable_portal`

(https://stackoverflow.com/questions/ask)
![image](https://user-images.githubusercontent.com/6835891/68435239-df320a00-0188-11ea-9087-852a2e9e19b0.png)

**Comment by diegohaz** [comment]
It seems to be an issue on `popper.js` (or on the browser itself).

Related:
- https://github.com/FezVrasta/popper.js/issues/764
- https://github.com/FezVrasta/popper.js/issues/682

**Comment by Slapbox** [comment]
Thanks for taking the time to document the suspected underlying cause @diegohaz!

Do you have any idea why `unsafe_portal` makes the issue worse? Is it simply a matter of requiring a "larger" `transform-3d` value to position properly, increasing blurriness? Is it simply a mystery?

The reason I ask is that the default entry motion without `unsafe_portal` is triggering a [Tippy](https://github.com/atomiks/tippyjs) element within my popover as it slides under the mouse and into view. Definitely not the end of the world in any case.

**Comment by diegohaz** [comment]
It’s a mystery for me. I can’t really reproduce it. Not sure if it’s the code (tried with the popover examples on the site), the browser or the MacBook screen, which has high PPI. I can check later with my wife’s PC, but its screen has also high resolution, so I’m afraid I’ll not be able to see this issue.
