### ISSUE TITLE
MenuItemRadio component throws warning message on conditional render

### ISSUE THREAD

**Issue by btzr-io** [reakit/reakit#488]
### Current behavior
When usign `menuItemRadio` component on conditional render throws warning message:

```
[reakit/RoverState]
rover-lna640 stop is not registered
...
```

### Steps to reproduce the bug

Provide a repo or sandbox with the bug and describe the steps to reproduce it.

1. Open sandbox: https://codesandbox.io/s/reakit-menu-with-tooltip-0f7nw?from-embed
2. Interact with menu to toggle condition rendering.
3. See console logs

### Expected behavior
Don't throw warnings of unregistered stops.

### Environment

Please, run the command below inside your project directory.
```sh
$ npx envinfo --system --binaries --browsers --npmPackages "{react*,reakit*}"

Environment:
  OS:  Linux 4.15
  Node:  10.15.3
  Yarn:  1.19.1
  npm:  6.12.0
  Watchman:  Not Found
  Xcode:  N/A
  Android Studio:  Not Found


```

**Comment by btzr-io** [comment]
Anyway to suppress this errors / warnings ?

**Comment by Intelecis** [comment]
Good of you for opening a question under discussion. We will get back to you as soon as we can.[ Click here](https://www.intelecis.com) for more information about warning message.
