### ISSUE TITLE
Integrate with issuehunt

### ISSUE THREAD

**Issue by artalar** [reakit/reakit#490]
### Motivation

Support this awesome project

### Example

https://issuehunt.io/r/ant-design/ant-design

### Possible implementations

https://issuehunt.io/r/new

**Comment by tom-sherman** [comment]
I'm interested if any other projects have combined both Open Collective and IssueHunt, do you know of any?

**Comment by artalar** [comment]
No :eyes:

**Comment by diegohaz** [comment]
Thank you for the suggestion. Just added Reakit to IssueHunt: https://issuehunt.io/r/reakit/reakit
