### ISSUE TITLE
Elaboration of plans for Reakit-integrated animations, if any?

### ISSUE THREAD

**Issue by Slapbox** [reakit/reakit#496]
## 🚀 Feature request

Following up on what @diegohaz mentioned [here](https://github.com/reakit/reakit/issues/350#issuecomment-533847935):

> in the future we may have a separate package to handle those animations more easily within Reakit (see how reakit-system-palette handles colors, for instance).

 I was wondering if there's any more information on the roadmap to bring animation features (like `fade` and `slide` for Popovers) back to the Reakit ecosystem. I've long been holding off on choosing an animation library, but I think it's about time I do that, and it would be great to get a better idea of what, if anything, is planned by Reakit in this regard before we nail down the specifics here.

### Motivation

A secondary package itself that allowed for easy animations like `slide` and `fade` from `reakit@0.x` would be amazing, but even some discussion of the plans would be a great help for planning.

### Example

Slide/fade in popovers like in `v0`

**Comment by diegohaz** [comment]
There's no plan yet, but here's an experimentation around how it could look like: https://codesandbox.io/s/reakit-animated-system-t3hxg

**Comment by diegohaz** [comment]
@gregberge Could you please add your thoughts and/or describe how you make animations with Reakit components? That will help us a lot to improve the API and make it stable. :)

**Comment by gregberge** [comment]
Hi, I have actually one example:

https://github.com/gregberge/gregberge.com/blob/master/src/components/Navbar.js#L140

**Comment by tom-sherman** [comment]
FYI, the animation API for Disclosure (and components composed on top of Disclosure) is now table. For Popover specifically see: https://reakit.io/docs/popover/#animating
