### ISSUE TITLE
Interacting with a toolbar item  triggers updates for all the other items

### ISSUE THREAD

**Issue by btzr-io** [reakit/reakit#497]
### Current behavior

Interacting with a toolbar `item` or menu `item` (also inside toolbar) triggers updates for all the other items.

### Steps to reproduce the bug
1. Open sandbox: https://codesandbox.io/s/reakit-menu-with-tooltip-4wbml?from-embed
2. Remove any line
3. See console logs

### Expected behavior

I'll expect to just update the button that the user is interacting.
Since the api requires to pass `useToolbarState` and `useMenuState` to all items I guess this is expected if is tracking the last focused element, current focused element, values etc...

So I'm not sure if this is a real issue or the intended / expected behavior :confused: 

### Environment

Please, run the command below inside your project directory.
```sh
$ npx envinfo --system --binaries --browsers --npmPackages "{react*,reakit*}"

Environment:
  OS:  Linux 4.15
  Node:  10.15.3
  Yarn:  1.19.1
  npm:  6.12.0
  Watchman:  Not Found
  Xcode:  N/A
  Android Studio:  Not Found
```

**Comment by diegohaz** [comment]
Thanks for opening the issue! That's the intended behavior, but maybe we can trigger updates only on the relevant components (the one that is losing focus and the one that is receiving focus).

But I'm not sure if the added check would be faster than just rendering the component. We need some automated performance test. Related to #429
