### ISSUE TITLE
Dependency error on rollup build

### ISSUE THREAD

**Issue by btzr-io** [reakit/reakit#505]
### Current behavior

Rollup trows this error while building a project usign `reakit` as a dependency
> [!] Error: 'disableBodyScroll' is not exported by node_modules/body-scroll-lock/lib/bodyScrollLock.min.js
https://rollupjs.org/guide/en/#error-name-is-not-exported-by-module
node_modules/reakit/es/Dialog/Dialog.js (19:9)

### Steps to reproduce the bug

Create a project that uses `reakit` as a dependency and build it with `rollup`.

### Expected behavior

Is this expected ?

:information_source:  **Update** : I think the solution or intended thing to do is to move reakit as a `peerDependency` 

### Environment

Please, run the command below inside your project directory.
```sh
$ npx envinfo --system --binaries --browsers --npmPackages "{react*,reakit*}"

Environment:
  OS:  Linux 4.15
  Node:  10.15.3
  Yarn:  1.19.1
  npm:  6.12.0
  Watchman:  Not Found
  Xcode:  N/A
  Android Studio:  Not Found
```

**Comment by btzr-io** [comment]
Closing this for now:
> :information_source:  **Update** : I think the solution or intended thing to do is to move reakit as a `peerDependency`

**Comment by diegohaz** [comment]
I guess that's an issue on `body-scroll-lock`? We use this rollup configuration:
https://github.com/reakit/reakit/blob/4931fef3070e0b56e454ae6c888b5dcf6043916c/scripts/build/rollup.config.js#L50-L55

**Comment by diegohaz** [comment]
Related: https://github.com/willmcpo/body-scroll-lock/issues/120

**Comment by diegohaz** [comment]
By the way, I would love to get rid of the `body-scroll-lock` dependency as it looks like they're not actively  maintained anymore.

**Comment by btzr-io** [comment]
Should I reopen this ?

**Comment by diegohaz** [comment]
According to the comments on that issue, it seems that it can be fixed if we import it from `body-scroll-lock/lib/bodyScrollLock.es6.js`:
```js
import { disableBodyScroll, enableBodyScroll, clearAllBodyScrollLocks } from 'body-scroll-lock/lib/bodyScrollLock.es6.js';
```

**Comment by gabrielreisn** [comment]
Is anyone already started solving it or can I take it?

**Comment by diegohaz** [comment]
@gabrielreisn Go ahead!
