### ISSUE TITLE
Dialogs close on a click that starts in the dialog, but ends outside

### ISSUE THREAD

**Issue by miketamis** [reakit/reakit#506]
### Current behavior
When you click and hold within a modal and then drag (while still pressed) outside the modal and release the click, the modal will close.  https://imgur.com/a/XYcKluc

### Steps to reproduce the bug

1. Go on https://reakit.io/docs/dialog/ 
2. Click open dialog
3. down click within modal (keep mouse click held down)
4. Drag cursor outside of modal
6. Release cursor

### Expected behavior
Modal only closes when down and upclick happens outside the modal (same way as button works, you can't click on a button then drag outside, or vice versa)

This modal library works correctly https://tingle.robinparisi.com

The reason its important is if your modal has an input field or text that the user try to highlight, they will drag there mouse outside the modal selecting it, when they release they dont expect the modal to disappear.

**Comment by diegohaz** [comment]
Thanks for opening the issue @miketamis! I'm working on a solution. :)
