### ISSUE TITLE
Popover: gutter - Accept string value

### ISSUE THREAD

**Issue by ItsJonQ** [reakit/reakit#511]
### Motivation

👋Hallo! First off, thank you for all for creating this magical thing that is Reakit! It's absolutely wonderful, and it's easily become one of my favourite libraries ❤️.

The feature request idea I had to was to enable the `gutter` option for `usePopoverState()` to accept a `string` value.

The underlying library, `popper.js`, accepts a string:
https://popper.js.org/popper-documentation.html#modifiers..offset.offset

The use case was to enable `x` offsetting in addition to `y`.

I recently needed this when I needed to negatively offset a Reakit Menu to the left. I wasn't able to do this with `useMenu()`, so I had to use CSS negative margins.

### Example

An example of this implementation would be something like:

```js
const popover = usePopoverState({ gutter: '-10px 10px' })
```

When passing it to `popper.js`, it should translate to:

`x`: `-10px`
`y`: `10px`

### Possible implementations

To enable this change, we'd need to adjust the options being passed to Popper, here:
https://github.com/reakit/reakit/blob/master/packages/reakit/src/Popover/PopoverState.ts#L168

To maintain backwards compatibility, we'd need to adjust the value based on either the `gutter` was a `string` or `number`.

Lastly, we'll need to update the `type`.

Thank you so much for your time!

**Comment by diegohaz** [comment]
That sounds very reasonable to me!

@ItsJonQ Would you like to work on that?

**Comment by jperasmus** [comment]
Briefly looked and just keep in mind that the string option with values separated by spaces will be deprecated in v2 of `popper.js`. They recommend separate values using a comma, ie. `-10px, 10px` and not `-10px 10px`. From Reakit's point of view, it probably doesn't matter because it will just pass along either the number or string to `popper.js` under the hood.

**Comment by ItsJonQ** [comment]
> Would you like to work on that?
@diegohaz Sure thing! I'd love to :)

> They recommend separate values using a comma, ie. -10px, 10px and not -10px 10px
Oo! Good catch

**Comment by FezVrasta** [comment]
Actually, in v2 we are going to accept only a tuple, with `[mainAxis, altAxis]` values.

here you find some documentation, but consider it may change since v2 is still under development.

https://github.com/popperjs/popper.js/blob/next/docs/src/pages/modifiers/offset.mdx

**Comment by ItsJonQ** [comment]
@FezVrasta Oh! Interesting. That seems like a better API. Thanks for the heads up!

P.S. I'm a big fan fan of Popper.js. Thank you for your amazing work 🎉

**Comment by diegohaz** [comment]
@FezVrasta Will v1 accept `offset` as a tuple before v2 is out? That would help with the migration I guess.

To be safer here, I'd suggest that we introduce a new `unstable_` property instead of augmenting `gutter`, that is already stable:

```js
usePopoverState({ unstable_offset: [-10, 10] });
```

I imagine the implementation being something like this for now:
```js
const [offsetA = 0, offsetB = gutter] = initialOffset || [];
const offset = `${offsetA}, ${offsetB}`; // [offsetA, offsetB] on Popper v2?
```

**Comment by FezVrasta** [comment]
I don’t plan to backport the API to v1, I’m sorry

**Comment by jperasmus** [comment]
The fact that Reakit uses Popper.js under the hood should probably be an implementation detail. Maybe Reakit should allow a number and a tuple for the `offset`. While Reakit uses v1 of Popper.js, it can transform the tuple (`[-10, 10]`) to the string (`-10px, 10px`) that Popper.js v1 understands. When v2 is released and Reakit upgrades to it, the transformation can be dropped.

**Comment by folz** [comment]
Just ran into this issue myself. @ItsJonQ, how is the PR going? I can make some time to address this today or tomorrow if there's a need.

**Comment by folz** [comment]
@FezVrasta Will the v2 API continue to support `'%p'`, `'%r'`, and other special strings, or do you intend to deprecate those in favor of the function case?

**Comment by FezVrasta** [comment]
The function callback will replace them

**Comment by ItsJonQ** [comment]
@folz Hai there! My apologies! Things have been a bit busy on my end, I haven't gotten around to it yet. You (or anyone else) is more than welcome to submit a PR 🙏

**Comment by folz** [comment]
All good! Just wanted to make sure I wouldn't be clobbering anything you were working on if I started something up. Thanks for getting back to me :) I'll take a crack at this and try to have a PR out by EOD.
