### ISSUE TITLE
Emulate v0's Popover slide="left"

### ISSUE THREAD

**Issue by Slapbox** [reakit/reakit#512]
### Motivation

In `v0` the popover flew in horizontally from the `right` for my use case ala 'slide="left"`, but now flies in diagonally from the `bottom-right`.

I understand that animation is no longer within the scope of the core package, but I don't know how I would emulate the `v0` behavior without basically rewriting the show/hide logic of of the whole popover element, and for the end user of the application the current behavior without the slide effect feels a lot sloppier.

I'm not faulting the library here, it's probably a good decision to separate animation from structure - I just don't know how to work around it to emulate `v0` though. If there's a way to do this already that I'm overlooking, please let me know!

### Possible implementations

Allow custom `transform3d` coordinates for hidden popover so it will slide in from a user-defined position?

**Comment by Slapbox** [comment]
@diegohaz is there any way to force/emulate this behavior right now besides to fall back to `v0`?

**Comment by diegohaz** [comment]
Have you tried a variation of this? https://github.com/reakit/reakit/issues/496#issuecomment-554796933

**Comment by Slapbox** [comment]
Apologies @diegohaz . I've got too much I'm juggling and I forgot all about that.
