### ISSUE TITLE
Portal has null context

### ISSUE THREAD

**Issue by danielbartsch** [reakit/reakit#513]
### Current behavior

PortalContext is evaluated immediately (eg. when importing from reakit).
This might be before there is even any Dom besides `document`. Thus `document.body` evaluates to `null`, rendering `Portal` useless, as it doesn't render anything.

### Steps to reproduce the bug

https://jsbin.com/xovonepete/1/edit?html,output
Here you  can see that `div` elements are rendered, but the `portal` children aren't

### Expected behavior

`PortalContext` should never be null, and `<Portal>` should always render its children.
(eg. `PortalContext` should be evaluated when `Portal` is rendered, and not immediately when importing from reakit)

### Possible solutions

See above: evaluate `PortalContext` in render of `Portal`.

### Environment

Please, run the command below inside your project directory.
```
  System:
    OS: Linux 5.0 Ubuntu 19.04 (Disco Dingo)
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Memory: 267.80 MB / 15.41 GB
    Container: Yes
    Shell: 5.0.3 - /bin/bash
  Binaries:
    Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
    npm: 6.4.1 - ~/.nvm/versions/node/v10.15.3/bin/npm
  Browsers:
    Chrome: 78.0.3904.108
    Firefox: 71.0
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-ace: 6.2.0 => 6.2.0 
    react-bootstrap: 0.31.5 => 0.31.5 
    react-bootstrap-daterangepicker: 4.1.0 => 4.1.0 
    react-dom: 16.8.6 => 16.8.6 
    react-highcharts: 16.0.2 => 16.0.2 
    react-highlight-words: 0.10.0 => 0.10.0 
    react-hot-loader: 4.12.15 => 4.12.15 
    react-onclickoutside: 6.7.1 => 6.7.1 
    react-overlays: 0.7.4 => 0.7.4 
    react-redux: 5.0.7 => 5.0.7 
    react-router: 3.2.1 => 3.2.1 
    react-select: github:pmedianetwork/react-select => 2.4.3 
    react-sortable-hoc: 0.8.4 => 0.8.4 
    react-test-renderer: 16.8.6 => 16.8.6 
    react-window: 1.8.5 => 1.8.5 
```

**Comment by diegohaz** [comment]
Thanks! Can you reproduce it with JSBin, maybe? https://jsbin.com/celiwun/edit?html,output

**Comment by danielbartsch** [comment]
Yes!
https://jsbin.com/xovonepete/1/edit?html,output

**Comment by danielbartsch** [comment]
I added a PR (https://github.com/reakit/reakit/pull/514) but I'm not sure if this  is a desired solution, as unfortunately I don't have a full picture of reakit just yet.
