### ISSUE TITLE
Popover - support popper.js `inner` modifier

### ISSUE THREAD

**Issue by folz** [reakit/reakit#516]
### Motivation

I am building a [Toast](https://getbootstrap.com/docs/4.2/components/toasts/) component in reakit/reakit-system. My original plan was to reuse Popover similar to how Tooltip does, but set `inner: true` and `reference` to `document.body`. However, PopoverState doesn't seem to expose the `inner` modifier.

### Example

A Toast component, or any other Popover-like component that needs to be positioned inside another element.

### Possible implementations

I think exposing an `unstable_inner` similar to how `unstable_shift` is exposed would work.

I'm happy to work on this PR if you think it'd be useful.

**Comment by folz** [comment]
As a side note, I should be able to contribute Toast to reakit once it's complete and made accessible. Is that something you'd consider including as a prebuilt component?

**Comment by diegohaz** [comment]
The `Notification`/`Toast` component has been requested on #464

I don't understand why it would compose Popover though. Do you think it would need any feature that only Popover provides? Why not just Portal?

**Comment by folz** [comment]
This is possibly specific to my use case, but we have Toasts that appear in the top, top-right, and bottom of the screen. I'm considering composing Popover because

1. Popover already comes with a positioning engine. I might as well reuse it instead of trying to recreate the behavior I can get from `{reference: document.body, inner: true}`.
2. Since Toasts can be positioned in various places, I'd to keep the same `{placement: ...}` API that is familiar from Popover and Tooltip.

**Comment by diegohaz** [comment]
I see! An `unstable_inner` option would be cool!

Out of curiosity, how did you set `document.body` as the reference? Did you set `popover.unstable_referenceRef.current`?

**Comment by folz** [comment]
Yep, that's exactly it. So far, I haven't needed much extra code, although the ref assignment feels quite hacky:

<details>

<summary>WIP</summary>

```ts
export const useToast = createHook<ToastOptions, ToastHTMLProps>({
  name: 'Toast',
  compose: useTooltip,
  useState: useToastState,

  useProps(options, {style: htmlStyle, ...htmlProps}) {
    options.unstable_referenceRef.current = document.body;

    return {
      role: 'alert',
      style: {
        ...htmlStyle,
        pointerEvents: undefined,
      },
      ...htmlProps,
    };
  },
});

export function useToastState(
  initialState: SealedInitialState<ToastInitialState> = {},
): ToastStateReturn {
  const {
    placement = 'top',
    unstable_boundariesElement = 'viewport',
    unstable_fixed = true,
    unstable_inner = true,
    ...sealed
  } = useSealedState(initialState);

  return usePopoverState({
    ...sealed,
    placement,
    unstable_boundariesElement,
    unstable_fixed,
    unstable_inner,
  });
}
```

</details>

I think I'll move future discussion about Alert/Toast to the issue you linked. In the meantime I'll open a PR with my `unstable_inner` changes.
