### ISSUE TITLE
Feature Request: Tooltip enter delay property

### ISSUE THREAD

**Issue by ynotdraw** [reakit/reakit#519]
### Motivation

First off, thanks so much for all of these great, a11y components.  This library has been a joy to work with!  Now onto the request...

I don't see a way to add a delay prop to Tooltips, which will wait the specified timeout before displaying the Tooltip content.  If the user moves focus/hover before the timeout has been hit, the Tooltip content never displays.  This is helpful in situations where you want to control when the Tooltip should be displayed to user versus when it shouldn't. Using material-ui as some inspiration: https://material-ui.com/api/tooltip/

### Example

```jsx
<Tooltip enterDelay={500} />
```

### Possible implementations

It appears popper.js is used under the hood for tooltips and popovers.  My thinking is that maybe we can leverage the `delay` prop mentioned here: https://github.com/popperjs/popper.js/blob/master/docs/_includes/tooltip-documentation.md?  If this makes sense to implement, I'd love to help contribute as well.

**Comment by diegohaz** [comment]
I guess we can't leverage popper.js' `delay` option since the visibility of the element is not controlled by popper.js.

But you can achieve something similar by following the approach described here: https://reakit.io/docs/composition/#state-hooks

**Comment by ynotdraw** [comment]
@diegohaz oh nice, sorry for missing the approach under state hooks!  I'll work on implementing it this way.  Thanks a bunch for your quick response!
