### ISSUE TITLE
Hidden: Add unstable_hiddenClassName prop

### ISSUE THREAD

**Issue by danielbartsch** [reakit/reakit#528]
## 🐛 Bug report

Mainly had that issue when using bootstrap css, as seen  in the jsbin.

### Current behavior

https://jsbin.com/zehupeluwo/1/edit?html,output

1. Click on the show dialog button.
2. the dialog contains two buttons. The second one should be focused as per React.useEffect, as seen here: https://reakit.io/docs/dialog/#initial-focus
3. the first one is actually focused

I tracked it down to this bootstrap class:
```css
.hidden {
    display: none !important;
}
```
And saw that a global class is added to the dialog (`hidden`) that interferes with this.
It seems that focusing an element that still has `display: none` does not work.

### Steps to reproduce the bug

See above.
Comment out the `<link>` that holds the bootstrap css to make it work.

### Expected behavior

Second button should be focused.
(or actually: reakit shouldn't have global classes)

The dialog component contains a `hidden` class if it's closed.

I could not definitely find in the code where a `hidden` class is added. I've only come near it, it feels: 
https://github.com/reakit/reakit/blob/cd1845a5f393100c064caf807a6f7454cdfe249c/packages/reakit/src/Hidden/Hidden.ts#L50
### Possible solutions

add `setTimeout` to the `ref.current.focus()` as seen here: https://reakit.io/docs/dialog/#initial-focus

### Environment

```
  System:
    OS: Linux 5.0 Ubuntu 19.04 (Disco Dingo)
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Memory: 216.63 MB / 15.41 GB
    Container: Yes
    Shell: 5.0.3 - /bin/bash
  Binaries:
    Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
    Yarn: 1.21.1 - ~/.nvm/versions/node/v10.15.3/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.15.3/bin/npm
  Browsers:
    Chrome: 79.0.3945.88
    Firefox: 72.0.1

```

**Comment by diegohaz** [comment]
I'm not sure if this should be classified as a bug or just a conflict between Bootstrap and Reakit. One solution is to remove the class name added by Reakit with [render props](https://reakit.io/docs/composition/#render-props):
```jsx
// Omit class name
<Dialog {...dialogState}>
  {({ className, ...htmlProps }) => <div {...htmlProps} />}
</Dialog>
```

**Comment by namjul** [comment]
@diegohaz is there a good reason why reakit adds the `hidden` class?

**Comment by namjul** [comment]
We are using the hooks directly and not the components. So if we remove the `className` the way you propose we might also remove others which we need. So would need to remove only `hidden` and leave the rest in place. Do you have any other idea this could be done?

**Comment by diegohaz** [comment]
@namjul The `hidden` class is removed shortly after `menu.visible` becomes `true`. It's useful for creating animations with CSS: https://codesandbox.io/s/reakit-animated-mm5u8

The whole `animated` feature is still in progress, so there's room to improve it. But for now I'd say that we can add an `unstable_hiddenClassName` prop to the `Hidden` component so people can change the class name.

**Comment by diegohaz** [comment]
> We are using the hooks directly and not the components.

Not sure if that's your question, but the hooks version would be something like this:
```jsx
const { className, unstable_wrap: wrap, ...htmlProps } = useDialog(dialogState, props);
const children = <div {...htmlProps} />;
return wrap ? wrap(children) : children; 
```

**Comment by namjul** [comment]
> > We are using the hooks directly and not the components.
> 
> Not sure if that's your question, but the hooks version would be something like this:
> 
> ```js-jsx
> const { className, unstable_wrap: wrap, ...htmlProps } = useDialog(dialogState, props);
> const children = <div {...htmlProps} />;
> return wrap ? wrap(children) : children; 
> ```
 perfect that will work.

**Comment by namjul** [comment]
The `unstable_hiddenClassName` makes sense because we might want to have animations in the future but need to use a different `className` than `hidden`.

**Comment by namjul** [comment]
For better understanding. 
By using the hooks we are skipping the `createComponent` util and therefore miss certain features.
I can see the following happening in `createComponent`
- splitProps
- wrap
- anything else?
So to make the hooks work without `createComponent` we need to manually apply these. We are doing the splitProps already but not the wrap. Can you explain why it exists?

**Comment by namjul** [comment]
@diegohaz iMaybe a section in the documentation to explain the differences in usage between the components and their underlining hooks would be a good thing.

**Comment by rumkin** [comment]
1. In my opinion classes like this should be provided through an OptionsProvider. Animation classes should have more speaking names like `animate-hidden` or so.
2. Using property `unstable_hiddenClassName` seems exhaustive and make component separation senseless due to leakage into application logic just to switch off single conflict behavior. Using property we got in a situation when visual theme switching leads to code refactoring.
3. Class name `hidden` isn't good though, it's a very common name for many css libraries with different implementations and now it's just using for no reason and it isn't obvious that the library could use global name like this. I'd suggest to add some prefix into it, like `reakit-hidden` or remove it completely and pass through provider, but it should be separated from global namespace.

TBH it's definitely not what I expect from UI library to do, I mean interrogation into my CSS structure. I would like Reakit to use zero of my classes without my will. So I'd prefer it to be switched off by default and to use provider for switching this feature on.

**Comment by diegohaz** [comment]
There's a Provider component where this kind of thing could live in. But I wouldn't like to force people to use Provider just to make animations. I'll try to think on a better solution to make animations easier after v1 gets out of beta (very soon). But I'm always accepting suggestions.

**Comment by rumkin** [comment]
Ok, could you add an option to switch it off through the global provider? Regular users should to change nothing and others will be able to do what they need. In my opinion it should be a class name property like `hiddenClassName` or so.
