### ISSUE TITLE
Menu position broken when using a custom MenuDisclosure component

### ISSUE THREAD

**Issue by darekkay** [reakit/reakit#543]
### Current behavior

The `MenuDisclosure` component renders a `<button>` by default, but it offers the `as` prop to use a custom component. When a custom (wrapper) component is being used, the menu position (style prop) is not being passed correctly

### Steps to reproduce the bug

Sandbox repository: https://codesandbox.io/s/peaceful-water-wbk4j

The native button positions the children correctly:

![image](https://user-images.githubusercontent.com/3101914/73868452-c3ea9f80-4848-11ea-830f-7cf3db104663.png)

![image](https://user-images.githubusercontent.com/3101914/73868547-f4323e00-4848-11ea-8e41-e531f67a4c9a.png)

The custom wrapper does not:

![image](https://user-images.githubusercontent.com/3101914/73868485-d1078e80-4848-11ea-85c4-3f914d9cd26f.png)

![image](https://user-images.githubusercontent.com/3101914/73868568-fb594c00-4848-11ea-9c5a-876e5aeab4a9.png)

### Expected behavior

A custom MenuDisclosure component should have the same behavior as a native component.

### Possible solutions

You can see that the `style` value is not being passed to the custom component. I could not figure out the reason why. Trying to pass the `style` prop directly does not solve the issue:

```jsx
const CustomButton = props => <button style={props.style} {...props} />;
```

**Comment by diegohaz** [comment]
Hi @darekkay! You should pass the `ref` prop to `CustomButton`:
```jsx
const CustomButton = React.forwardRef((props, ref) => <button {...props} ref={ref} />);
```
We could find a way to make it more obvious though. There's a warning in the console, but it's very generic.

**Comment by darekkay** [comment]
Thank a lot for the really quick response! 😃 
Indeed, I did not check the console, shame on me. While I did not know `React.forwardRef` until now, the message would probably have been enough to debug the issue myself.
