### ISSUE TITLE
Rename stopId

### ISSUE THREAD

**Issue by rumkin** [reakit/reakit#559]
## 🚀 Feature request

Components' property `stopId` should be renamed into something more meaningful and semantically correct.

### Motivation

For me `stopId` is something terminal, inactive or closed. And reading the docs I has been dropping it out of my attention as something secondary or unnecessary.

### Possible implementations

In my opinion there are more suitable names for this property:
* `aimId`,
* `innerId`,
* `myId`,
* `ownId`,
* `scopeId`
* `selfId`,
* `targetId`.

**Comment by diegohaz** [comment]
"Stop" in this context refers to "tab stop", but I agree that it may not be too obvious. And in some components it may not make much sense, such as `TabPanel`.

We're in the process of creating an alternative to `Rover` (which implements the `stopId` prop and is used by the other modules that have the same prop), so we have some opportunity to think about a better prop name. `stopId` won't go away though, but we can deprecate it if we find something better.

My current idea is to use just `id` where it's really used as the `id` attribute (`Tab`, `MenuItem`, `ToolbarItem`, `Radio`) and create an `idref` prop (which is another XML standard) on components that refers to another element's `id` (`TabPanel`).

What do you think? @rumkin

**Comment by diegohaz** [comment]
By the way, using just `id` is already supported in all components except `TabPanel`.

**Comment by rumkin** [comment]
1. Seems like I need to dig into this a little bit deeper, because `stopId` seems overloaded and I'm not sure if I understand all the use-cases. For example tabs have `stopId` which refers to corresponding panel's `stopId`, and the Reakit code makes them work together using tab state. In the same time `stopId` affects regular html id and if I overwrite id with a custom value the Tab component doesn't work anymore.
    
    I think it's better to use `panelId` for tabs to specify target panel and allow several tabs to refer to a single panel, for example if I want to duplicate tabs in the bottom of the tab panel.

    This is how I think it should work with `innerId` instead of `stopId` :

    ```jsx
    () => {
      const tabs = useTabState()
    
      return (
        <TabList>
          <Tab {...tabs} innerId="tab1" panelId="panel1" />
        </TabList>
        <TabPanel {...tabs} innerId="panel1" />
      )
    }
    ```
2. Property name `idref` have intersection with the `ref` prop of react and I'd suggest to use it carefully due to this intersection. I think it will be named `refId` according to the project name convention, but anyway developers could understand this wrong. While I like the idea of reusing existing standards, there are some tradeoffs. I will dig into the Rover to be helpful there.

I will read Rover component code to understand how it works. Also I have some thoughts on the name and id usage for creating nested components and to make them accessible programmatically from the top level and it seems that Reakit is very close to the concept I have in min. I'm about to create an example of how it could work together to solve issues like this and then I will send you the code to review when it will be ready. I think it will make the discussion more useful and productive.

**Comment by diegohaz** [comment]
As of `v1.0.0-rc.0`, `stopId` is deprecated in favor of just `id` (or `tabId` on `TabPanel`). Going to close this for now, but we can continue talking about that if needed.
