### ISSUE TITLE
Content don`t scroll inside Dialog component. 

### ISSUE THREAD

**Issue by zarabotaet** [reakit/reakit#594]
### Current behavior

Content don`t scroll inside Dialog component, on mobile (IOS, Safari or Chrome), when modal prop is true.

### Steps to reproduce the bug

[work](https://codesandbox.io/s/focused-sun-gmmhq)
[dont](https://codesandbox.io/s/naughty-wilbur-rq9dd)

**Comment by diegohaz** [comment]
Duplicate of #469
