### ISSUE TITLE
unstable_animated and measuring DOM nodes

### ISSUE THREAD

**Issue by tom-sherman** [reakit/reakit#602]
I'm using untable_animated and react-spring to add animations to a modal, so far it all works pretty great for animations that don't require measuring the size of the modal.

I'm basically trying to slide the modal (variable height) in from the bottom which requires to start the modal with `translateY(n)` where n is the height of the modal and animate it to `translateY(0)`. The exit animation works great but because I can't get a measurement on the modal before the animation starts, the modal doesn't slide in.

I'll try and post a sandbox when I get back to my desk but any help is appreciated!

**Comment by diegohaz** [comment]
Does using `translateY(100%)` help?

**Comment by tom-sherman** [comment]
Wow, TIL that it's a percentage of the height when using translateY - thanks for that it solves my problem perfectly!
