### ISSUE TITLE
Unable to use boolean values for Radio inputs

### ISSUE THREAD

**Issue by matthaywardwebdesign** [reakit/reakit#607]
### Current behavior

Setting the value of a Radio input to `false` (boolean) no longer works as of #599 

### Steps to reproduce the bug

Code Sandbox here - https://codesandbox.io/s/crazy-nightingale-xyzq3

Adjust the version of reakit from `1.0.0-rc.0` to `1.0.0-beta.16` to see the different in behaviour.

### Expected behavior

According to the HTML spec for Radio buttons, a string should be provided as the value, so technically this isn't a bug, however I could see this potentially being an issue for some people who have been using boolean values in the past, as the behaviour has changed.

Please close if this is fine.

### Possible solutions

Change https://github.com/reakit/reakit/blame/master/packages/reakit/src/Radio/Radio.ts#L39

from `return options.value && options.state === options.value;`

to `return options.state === options.value;`

**Comment by diegohaz** [comment]
Thanks for opening the issue! As you mentioned, `boolean` values are not supported on HTML, so I think we shouldn't support that.

But `value` may be an empty string or zero. So `options.value && options.state === options.value` should probably be something else. I'd appreciate a PR on that. Also, the types of `value` and `state` (on `RadioState`) should be updated. Right now they're `any`.

**Comment by matthaywardwebdesign** [comment]
No worries at all and agree with you on that one :)

Might get some time later today to submit that PR!

**Comment by tom-sherman** [comment]
@matthaywardwebdesign Are you ok if I pick this up or have you already made a start?

**Comment by matthaywardwebdesign** [comment]
@tom-sherman Thanks! I just pushed a PR :)

@diegohaz - I've resolved the issue with falsey values, however as the HTML spec says values must be strings, I've updated the types to reflect this. This will prevent zero being used as a value, do you see this as an issue?
