### ISSUE TITLE
Toolbar Orientation is unable to reach 'undefined' state

### ISSUE THREAD

**Issue by elitenoire** [reakit/reakit#611]
### Current behavior

The toolbar orientation has default `horizontal` state which makes the `undefined` state unreachable.
`version: reakit@1.0.0-rc.0`
### Steps to reproduce the bug

```js 

// reakit/packages/reakit/src/Toolbar/ToolbarState.ts

...

export function useToolbarState(
  initialState: SealedInitialState<ToolbarInitialState> = {}
): ToolbarStateReturn {
  const { orientation = "horizontal", ...sealed } = useSealedState(
    initialState
  );
  return useCompositeState({ orientation, ...sealed });
}

```

### Expected behavior

Orientation should be able to reach the `undefined` state so that all arrow keys can work as stated in the docs.

### Possible solutions

Remove the default state for the orientation option.

**Comment by diegohaz** [comment]
Alternatively, we can accept a `both` value.

**Comment by abidhkm** [comment]
Removing the default value will be an easy fix.
Adding `both` to the type Orientation may need some code changes in multiple files. I would like to raise PR if you can tell me the approach to be followed.

**Comment by diegohaz** [comment]
Removing the default value would be a breaking change, so it's not really something we can do right now. We can support both `both` and `undefined` for now, which I guess would need a change only on the Composite module.
