### ISSUE TITLE
FormMessage dont show in onSubmit event

### ISSUE THREAD

**Issue by eduardobento** [reakit/reakit#614]
Hi,

I´m using reakit default create user form. When the API callback a error, the onsubmit, with axios catch doenst show FormMessage message. Here is the code:
```js
    onSubmit: values => {
    axios.post('http://localhost:3000/users', values)
    .catch ( error => {
        const errors = {
          bla: "Usuário já existente"
        };  
        throw errors;
      })
```

This ```throw errors``` works perfectly in onValidate code.

**Comment by diegohaz** [comment]
@eduardobento You have to `return axios.post(...` or use `async/await`.

**Comment by eduardobento** [comment]
> @eduardobento You have to `return axios.post(...` or use `async/await`.

Ow, sorry about noobie question.

Works perfectly !
Thanks.
