### ISSUE TITLE
Dialog closes unexpectedly on Firefox when using hideOnClickOutside 

### ISSUE THREAD

**Issue by tom-sherman** [reakit/reakit#619]
### Current behavior

If focus leaves the Firefox window, any action inside of the window afterwards causes the modal to close - even if this action is clicking inside the modal itself.

### Steps to reproduce the bug

Provide a repo or sandbox with the bug and describe the steps to reproduce it.

1. Open sandbox: https://codesandbox.io/s/reakit-firefox-hideonclickoutside-bug-3lm0t
2. Open the dialog
3. Give focus to outside of the preview window, either by clicking the codesandbox ui, another application window, or pressing a browser keyboard shortcut such as F6 to focus the address bar.
4. Click anywhere inside the modal or resize the window

### Expected behavior

Nothing should happen

### Possible solutions

TBD

### Environment

Firefox 76.0b4 (64-bit) Dev Edition
```sh
  System:
    OS: Linux 4.19 Ubuntu 18.04.4 LTS (Bionic Beaver)       
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz   
    Memory: 12.09 GB / 12.37 GB
    Container: Yes
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 12.16.2 - ~/.config/nvm/12.16.2/bin/node
    Yarn: 1.22.4 - /mnt/c/Program Files (x86)/Yarn/bin/yarn 
    npm: 6.14.4 - ~/.config/nvm/12.16.2/bin/npm
  npmPackages:
    reakit: ^1.0.0-rc.0 => 1.0.0-rc.0
```

**Comment by diegohaz** [comment]
Thanks @tom-sherman!

Maybe checking [`document.hasFocus()`](https://developer.mozilla.org/en-US/docs/Web/API/Document/hasFocus) inside `useEventListenerOutside`?

**Comment by tom-sherman** [comment]
That seems to have done the job!

**Comment by tom-sherman** [comment]
Explanation as to why this bug exists: https://github.com/reakit/reakit/pull/620#issuecomment-614073432
