### ISSUE TITLE
Passing undefined to Dialog's tabIndex removed the tabIndex on the element

### ISSUE THREAD

**Issue by tom-sherman** [reakit/reakit#636]
### Current behavior

When passing `undefined` to tabIndex on the Dialog component, the tabIndex is removed from the DOM element. This can lead to the focus "leaking" out of the focus trap, causing features such as hideOnEsc not to work.

### Steps to reproduce the bug

1. Open sandbox: https://codesandbox.io/s/reakit-tabindex-undefined-v9stm
2. Open the dialog
3. Observe there is no tabIndex on the element
4. Click the "Welcome to reakit" text
5. `document.activeElement` is now the body, pressing esc doesn't close the dialog.

### Expected behavior

Because Reakit is applying a default of `tabIndex={-1}` for me, I would expect passing undefined to have no effect.

### Possible solutions

https://github.com/reakit/reakit/blob/master/packages/reakit/src/Dialog/Dialog.tsx#L201

It looks like a tabIndex from the htmlProps will override the -1 default, even if this prop is undefined, causing the prop to be removed in the DOM. We can override the -1 when the tabIndex is not undefined.

**Comment by tom-sherman** [comment]
I've added the potential bug label because my assumption of the expected behaviour could be incorrect. If we do agree that my expectations are correct, I can go ahead and add a quick fix.

**Comment by tom-sherman** [comment]
Hmmm, there's a test that looks to be relying on the current behaviour when using undefined so I'm not sure if my suggested solution is correct.

https://github.com/reakit/reakit/blob/master/packages/reakit/src/Dialog/__tests__/index-test.tsx#L799-L830

**Comment by diegohaz** [comment]
I think you’re correct! That test shouldn’t be there. The Dialog container should behave as the `document.body` for the dialog contents.
