### ISSUE TITLE
browser support?

### ISSUE THREAD

**Issue by giladgray** [reakit/reakit#648]
### Motivation

First, hi! 👋 This library looks awesome, very excited that it exists!

Quick question, should be simple. What is the browser support story for Reakit? Does it rely on modern ES features that must be polyfilled for older browsers?

I'm sure you have an answer ready for this, just a matter of supplying it on the docs site 😄 

### Example

https://reactjs.org/docs/javascript-environment-requirements.html
https://blueprintjs.com/docs/#blueprint/getting-started.js-environment

### Possible implementations

Add a section on https://reakit.io/docs/get-started/.

This is a little bit related to #624, as listing which browsers you test on is a good way of declaring which are officially supported.

**Comment by diegohaz** [comment]
It would be nice to have automated tests to enforce this as mentioned in #624

But we support all the modern browsers plus IE 11.
