### ISSUE TITLE
Typescript helpers/documentation to extend components and maintain "as" types.

### ISSUE THREAD

**Issue by tiagoengel** [reakit/reakit#649]
### Motivation

Following up on this discussion: https://spectrum.chat/reakit/general/typescript-utilities-to-extend-components~b9825325-4345-4082-b266-b14523ca2a99

One of the most interesting features of Reakit is the ability to compose functionality using the `as` prop.

It's not uncommon for me to want to extend a component to add some small extra functionality, but to keep all the base functionality the same. 

Doing so in plain Javascript is straightforward, there is no issue in wrapping the component and keeping the `as` functionality. The problem is in keeping the types working for Typescript codebases.

It would be great if Reakit can provide a standard way of doing this so in Typescript. 

### Example

A simple example of how I'd expect to be able to extend this in Typescript.

```typescript
import { Button as RkitButton, ButtonProps as RkitButtonProps } from "reakit";

type Props = RkitButtonProps & { loading: boolean; }

const MyButton: React.FC<Props> = ({ loading, disabled, ...rest }: Props) => {
  const isDisabled = disabled || loading;
  return (
    <RkitButton 
       disabled={isDisabled} 
       className={cs("button", isDisabled && "button-disabled")}
       {...rest} 
     />
  )
}
```

### Possible implementations

One possible solution is to provide a type akin to `React.FC`, e.g. `Reakit.FC<Props>` that would know how to properly define the component type to keep the `as` functionality.

The only working solution I've found so far is to use `Component` from `reakit-system/createComponent` and cast the export to the desired type. 

E.g. `as Component<"button", Omit<Props, "ref">>`. (https://github.com/reakit/reakit/blob/master/packages/reakit-system/src/createComponent.ts#L89)

This is not ideal as things inside `reakit-system` are unstable and this is not officially supported.

**Comment by diegohaz** [comment]
Thanks! I think we can start with some docs maybe. You've mentioned that you have problems with `React.forwardRef` as well, right? I imagine that it's because `React.forwardRef` doesn't keep the generics from the passed component.

**Comment by tiagoengel** [comment]
Yeah `forwardRef` also fails but I think that is not as important considering it's only one prop, in the worst case scenario it can be set to `any`, whereas `as` affects a few more props the component accepts.

I agree docs is a good start, maybe a new entry in the `Guide` section called `Typescript`? 

Do you think is best to suggest something similar to what you've suggested to me on spectrum? E.g. to create custom types to support the `as` property?

**Comment by lluia** [comment]
We had a similar issue on the company I work for when using [`as` from Styled Components](https://styled-components.com/docs/api#as-polymorphic-prop).

Given you can use `as` to render almost anything, it becomes so unpredictable to type 😕
I wonder if you could you use generics to work-around this 🤔

The solution we took was to limit for each component what can `as` be ( _not ideal though_ )
```ts
interface ITextProps extends HTMLAttributes<HTMLEelement> {
  as?: 'p' | 'span' 
} 
```

**Comment by tiagoengel** [comment]
It can be done with generics @lluia, I believe is what Reakit is doing, but as you mentioned it's not straightforward. That's why I think some utility types and/or docs will be very helpful.

**Comment by diegohaz** [comment]
Another thing we can do to help people extending Reakit components is to accept a generic `as` type on the `ComponentProps` types:

```ts
import { MenuProps } from "reakit";

type MyMenuProps<T extends React.ElementType> = MenuProps<T> & {
  myCustomProp: string;
};

function MyMenu<T extends React.ElementType>(
  { myCustomProp, ...props }: MyMenuProps<T>
) {
  ...
}
```

**Comment by diegohaz** [comment]
For people coming to this issue in the future, here's something that might help you: https://twitter.com/diegohaz/status/1297886375941873664
