### ISSUE TITLE
Dialog's click trap blocks Google Maps SDK autocomplete dropdown.

### ISSUE THREAD

**Issue by folz** [reakit/reakit#657]
## 🐛 Bug report

We want to render the Google Maps SDK inside a Dialog. `Dialog` has a click trap to prevent clicks outside the DOM tree of the Dialog. Unfortunately, the Maps SDK always inserts the autocomplete dropdown just before `<body>`, meaning it's always outside of the Dialog's DOM tree, then positions it absolutely with CSS.

As a result, the autocomplete dropdown appears visually inside the Dialog, but cannot be clicked because Dialog rejects the click for being on an element outside the DOM tree.

<img width="684" alt="Screen Shot 2020-05-28 at 4 07 27 PM" src="https://user-images.githubusercontent.com/299281/83204758-777de500-a101-11ea-9c30-0f9e77d5a1c9.png">

### Steps to reproduce the bug

See sandbox at https://codesandbox.io/s/reakit-gh-657-qgsvr

### Expected behavior

I should be able to click the Maps SDK's dropdown.

### Possible solutions

I think an option to disable the click trap, for when we Really Know What We're Doing™, could work.

Alternatively, it could be nice to pass a ref or list of elements as things Dialog should consider "inside it".

We have a hacky solution that moves the autocomplete's DOM element inside the Dialog DOM tree, but I don't know how robust that will be.

### Environment

We're on reakit@1.0.0-beta.16, so if this is fixed in a later version, my apologies. We're not able to upgrade at this time for reasons unrelated to Reakit.

**Comment by tom-sherman** [comment]
> Alternatively, it could be nice to pass a ref or list of elements as things Dialog should consider "inside it".

This sounds like a similar solution to something I suggested for scrollable elements inside of a Dialog: https://github.com/reakit/reakit/issues/469#issuecomment-618936539

I don't know if it's relevant but I thought I'd surface the similarity!

**Comment by tom-sherman** [comment]
Here's a sandbox for what I think you are describing: https://codesandbox.io/s/reakit-gh-657-x92zy

The button is still clickable on v1.0.0-beta.16 and v1.0.0 though. Maybe I'm missing a trick?

**Comment by diegohaz** [comment]
Is there any option on the Maps SDK to change the dropdown's container target? Ideally, the dialog portal element should be considered the `document.body` for all elements inside it.

How are you working around that in the code? If you're able to, at least, move the dropdown element into the dialog portal element, I'd say that this is the best solution.

**Comment by folz** [comment]
We're working around it currently by moving the element into the Dialog. This has worked so far, but I don't know if we're quietly breaking something else in the Maps SDK that we aren't using or haven't tested yet. I was able to write a sandbox demonstrating the issue, using approximately the same code we're running in prod: https://codesandbox.io/s/reakit-gh-657-qgsvr.

The first instance does not do anything special, note how you can hover elements but you cannot click to select items in the dropdown. Arrow keys and enter work, though.

The second instance will move its dropdown into an element inside Dialog, but you need to type a character after the first results appear to trigger that behavior. Once it's moved inside, you can click to select like normal.

There's not an option to have the Maps SDK change the dropdown's parent element. This is apparently on purpose, not an oversight, according to this thread from 2011: https://groups.google.com/forum/#!topic/google-maps-js-api-v3/ibIknTkPTho.

And yeah, I agree that we should consider Dialog the `document.body`. We do (or try to, at least) for the rest of the code we write. The issue is with 3rd-party code that doesn't follow that practice and doesn't allow an option for us to override.

**Comment by folz** [comment]
@tom-sherman you know, I also would have thought your example would have behaved like what I'm seeing with the Maps SDK. Whatever the reason, I'm missing it too.
