### ISSUE TITLE
introduce Error class for throwing in form onValidate

### ISSUE THREAD

**Issue by Guria** [reakit/reakit#661]
### Motivation

https://eslint.org/docs/rules/no-throw-literal

> It is considered good practice to only throw the Error object itself or an object using the Error object as base objects for user-defined exceptions. The fundamental benefit of Error objects is that they automatically keep track of where they were built and originated.

### Example

```
import {
  unstable_useFormState as useFormState,
  unstable_ValidationError as ValidationError,
  /* ... */
} from "reakit/Form";

function Example() {
  const form = useFormState({
    values: { message: "" },
    onValidate: (values) => {
      if (!values.message) {
        throw new ValidationError({
          message: "Please enter a message.",
        });
      }
    },
    onSubmit: (values) => {
      alert(JSON.stringify(values, null, 2));
    },
  });
  return (
    /* ... */
  );
}
```

**Comment by diegohaz** [comment]
This somehow overlaps with #468 

It seems that having this kind of validation error object would be the best solution.

**Comment by Guria** [comment]
@diegohaz 
I do agree with no throwing API proposed there. So I think we can close this issue in favor of referenced one.
