### ISSUE TITLE
Feature request: A "password" field with option to hide and show password input

### ISSUE THREAD

**Issue by julienemo** [reakit/reakit#664]
## 🚀 Feature request

A "password" field with option to hide and show password input

### Motivation

In a sign in form, a password field is often in need. By default, password is always hidden as little black dots and it would be nice if we could have an option to see the exact input (for example with a little eye icon)

### Example

Here is an example from [antd](https://ant.design/components/form/)

The form looks like this
![ex1](https://user-images.githubusercontent.com/29869362/83657857-b90b0600-a5c1-11ea-9db9-97fa23ec82a0.png)

By default when a password is entered, it is hidden
![ex2](https://user-images.githubusercontent.com/29869362/83657881-c0caaa80-a5c1-11ea-8e27-62e82d694b97.png)

If we click on the little eye icon on the right, the password is revealed
![ex3](https://user-images.githubusercontent.com/29869362/83657916-ce803000-a5c1-11ea-8bff-7c8b19dea1ae.png)

### Possible implementations

On sign in pages

**Comment by StephaneP** [comment]
wouldn't mind working on this one

**Comment by diegohaz** [comment]
This seems too specific to be a component. Maybe just an [example](https://github.com/reakit/reakit/issues/626) would be enough?

**Comment by hc-codersatlas** [comment]
Instead of just password, the option to add a component at the start and end of an input would be good. Seems to common in other ui frameworks.

**Comment by mattrothenberg** [comment]
I think this is closed by #753?
