### ISSUE TITLE
Introduce Input primitive as base for FormInput

### ISSUE THREAD

**Issue by Guria** [reakit/reakit#665]
> I think the first question to answer is "what would that do that a simple `<input>` already doesn't?".
> Unless we add some sort [editable content](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Editable_content) support when people do things like `<Input as="div">`, it's unclear to me how people could benefit from the `Input` component. But I haven't put much thought into that yet, so I'm probably missing something.

_Originally posted by @diegohaz in https://github.com/reakit/reakit/issues/468#issuecomment-638306619_

**Comment by Guria** [comment]
@diegohaz 
I would reverse a question: "what would that simple <input> will not have that FormInput does?"
It wouldn't have dependency on useFormState, first of all.

On the other side it would still can be [styled](https://github.com/reakit/reakit/blob/master/packages/reakit-system-bootstrap/src/Form.ts#L78) as Input using `useInputProps` hook.

**Comment by Guria** [comment]
@diegohaz so do you agree with this suggestion?

**Comment by diegohaz** [comment]
Yeah! I think that's a good start. :)
