### ISSUE TITLE
htmlWrapElement before portal wrap

### ISSUE THREAD

**Issue by namjul** [reakit/reakit#686]
### Motivation

Currently all `wrapElement` prop calls like the following are called after a component typically wraps its content into a portal. https://github.com/reakit/reakit/blob/ce766d57b97e6b081a41504e8676e5d47e23e9cd/packages/reakit/src/Dialog/DialogBackdrop.tsx#L37-L43

```       
if (htmlWrapElement) {
	return htmlWrapElement(element);
}
```

### Example

In my case i am using the hooks only and want use `wrapElement` prop to wrap it conditionally by another component. But since the mentioned call above is happening after the wrap into a portal my wrapping component does not get rendered into the portal. Probably there a good reason for the existing order but what if we swap it?

### Possible implementations

https://github.com/reakit/reakit/compare/master...namjul:patch-2

**Comment by diegohaz** [comment]
@namjul Could you please create a CodeSandbox demonstrating the current behavior with the issue (so we can compare after opening a PR)? With that, I would accept a PR on that if you're willing to work on this. :)
