### ISSUE TITLE
[Radio] Tab moves focus to body instead of next tabbable item in the dom

### ISSUE THREAD

**Issue by navin-moorthy** [reakit/reakit#702]
### Current behavior

Hitting `Tab` from the <Radio/> moves the focus to body instead of the next focusable element in the DOM.

### Steps to reproduce the bug

https://codesandbox.io/s/useradio-reakit-issue-xu62i

1. Click on top of the body.
2. Hit `Tab` to move the focus to the 1st <Radio /> within 2st <RadioGroup />
3. Hit `Tab` moves the focus to the body

### Expected behavior

3. Hit `Tab` should move the focus to the 1st <Radio /> within 2nd <RadioGroup />

### Possible solutions

I tried to look into solving this issue, but I am still getting familiar with Reakit repo. So no luck.

But here's something I tried, I did the same Radio example with React Aria

Works smooth - https://codesandbox.io/s/useradio-spectrum-rl7hj?file=/src/App.js

---

More examples with Radio using Reakit and `useFocusRing` from React-Aria - https://codesandbox.io/s/useradio-reakit-c72nc

### Environment

"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36"

Mac OS - Catalina 10.15.5
Google Chrome 84

**Comment by tom-sherman** [comment]
This is intentional behaviour for radio groups I believe. From the [WAI-ARIA docs](https://www.w3.org/TR/wai-aria-practices/#radiobutton):

> <kbd>Tab</kbd> and <kbd>Shift + Tab</kbd>: Move focus into and out of the radio group. When focus moves into a radio group

The radio group is a single tab stop in the document to allow for fast navigation for keyboard users within the page. You can then use the arrow keys to move between radio elements.

To get the behaviour you're after, you would likely need to compose your own Radio component using Clickable and Tabbable.

**Comment by navin-moorthy** [comment]
Thanks, @tom-sherman for answering, but I understand how Radio work according to the link you attached but my point is traversing from one Radio group to another.

I think you mis-understood OR I did not convey it much clear earlier.

Let me show you what I mean

![reakit-tab-focus](https://user-images.githubusercontent.com/39694575/89994807-3def5b80-dca6-11ea-8396-11a0ff65664a.gif)

But I am expecting this as in [WAI-ARIA Example](https://www.w3.org/TR/wai-aria-practices/examples/radio/radio-1/radio-1.html)

![radio-group-wai-aria](https://user-images.githubusercontent.com/39694575/89995306-f1585000-dca6-11ea-9021-03d8b658317e.gif)

See, I can move between two radio groups using `Tab`

**Comment by tom-sherman** [comment]
Oh, ok sorry! I'm not seeing that behaviour on either Chrome or Firefox on my machine so assumed you were asking about different behaviour, entirely my fault.

What browser are you seeing this in?

**Comment by navin-moorthy** [comment]
I am using Chrome 84, let me check in other browsers as-well and will let you my results.

**Comment by navin-moorthy** [comment]
But I get the expected behaviour with React Aria - https://codesandbox.io/s/useradio-spectrum-rl7hj?file=/src/App.js.
Just in case you need.

**Comment by navin-moorthy** [comment]
I am getting the expected behaviour in Firefox Developer Edition v80.

**Comment by tom-sherman** [comment]
What OS and version?

**Comment by navin-moorthy** [comment]
I think, I should have posted these details when raising the issue, but I did not it was necessary before.
Sorry for that.

"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36"

**Comment by tom-sherman** [comment]
I am now seeing your described behaviour as well on Chrome 84.0.4147.125 on Windows. Thanks for this Navin, looks like a bug to me!

**Comment by navin-moorthy** [comment]
Got it, thanks. So, you were using an older version of Chrome and it works as expected before?
If so please add that Chrome Version.

**Comment by tom-sherman** [comment]
I've downloaded Chromium 83 and the bug still exists, so I must have had open the wrong sandbox at the time!

**Comment by diegohaz** [comment]
Thanks for reporting @navin-moorthy! The issue, I guess, is that we aren't including the `name` attribute on the radio elements (radios in the same group should have the same name).

You can work around it by manually adding the name. But that's something we should fix here as well. In case you want to contribute, I think you can just add `name` prop here as `options.baseId` (generated automatically) when `isNativeRadio` is `true`: https://github.com/reakit/reakit/blob/eec7a44be656b49c96c17c1d76796b5800bea29e/packages/reakit/src/Radio/Radio.ts#L145-L155

**Comment by navin-moorthy** [comment]
OH!! Adding name attribute fixed it. I did not think that would cause an issue 😑 

Good to know @diegohaz , I will take it up and raise a PR for this fix.

Cheers 🎉

**Comment by navin-moorthy** [comment]
I hope the above PR is sufficient. Also, shouldn't we add a note or something like that anywhere so others don't report this in future.

Since, in the docs I don't see a name prop and I just tried copy pasted the example. So got the bug.

Is it a good idea to send out a auto generated `name` prop by default(not onlyi if it's a `isNativeRadio` ? and the when there's a `name` prop provided for <Radio /> that will take the precedence.

**Comment by navin-moorthy** [comment]
> I hope the above PR is sufficient.
> 
> Also, shouldn't we add a note or something like that anywhere so others don't report this in future.
> 
> Since, in the docs I don't see a name prop and I just tried copy pasted the example. So got the bug.
> 
> Is it a good idea to return an auto generated `name` prop by default(not onlyi if it's a `isNativeRadio`) ? and the when there's a `name` prop provided for that will take the precedence.

Any thoughts on this @diegohaz ?

**Comment by diegohaz** [comment]
Do you still think it's necessary to explain about the `name` prop in the docs now that it's fixed? People who want to use a custom `name` prop can do it by just passing the prop to the element. Non-native radio elements don't suffer from this issue.

**Comment by navin-moorthy** [comment]
Okay !! I understand now. I am still looking into the Radio Component Source code to understand.

I don't think it's necessary now. Thanks !!
