### ISSUE TITLE
[Separator] Return role and aria-orientation when the element is not `hr`

### ISSUE THREAD

**Issue by navin-moorthy** [reakit/reakit#721]
## 🚀 Feature request

Only return `Role: seperator` when the element is not `hr` tag and `Orientation: vertical` when the orientation is vertical.

Adding them when the tag is `hr` and in horizontal orientation is redundant IMO.

### Motivation

Seperator `<hr />` by default has `Role: seperator` and `Orientation: horizontal`.

![Resizer](https://user-images.githubusercontent.com/39694575/90950806-cde59000-e472-11ea-8c6c-6624c7a3d63f.jpg)

### Possible implementations

We check the `as` prop, if it's other than `hr`, we return `Role: seperator` and the orientation is `vertical` when return `Orientation: vertical`

**Comment by navin-moorthy** [comment]
@diegohaz Can I work on this changes, if you think we can do these checks ?

**Comment by diegohaz** [comment]
@navin-moorthy Sure! I think we could set the initial value based on the `as` prop and then check the element ref on the effect. But this would probably require some change on the `createHook` util as I think the `as` prop is not passed to the hook (not sure though).

**Comment by navin-moorthy** [comment]
Thanks @diegohaz , I will look into it.
