### ISSUE TITLE
[Button] As 'a' with disabled prop focuses on `tab`

### ISSUE THREAD

**Issue by navin-moorthy** [reakit/reakit#722]
### Current behavior

![image](https://user-images.githubusercontent.com/39694575/91055069-c88a7000-e641-11ea-9425-b0575dba309e.png)

### Steps to reproduce the bug

1. Open sandbox: https://codesandbox.io/s/button-with-a-disabled-bug-7znw8
2. Press Tab on the preview to see the button focus when keyboard press but not on pointer press.
3. Expect to see the button getting focused.

### Expected behavior

Button should not be focusable at all when `disabled`

### Possible solutions

```
const [isLink, setIsLink] = React.useState(false);

React.useEffect(() => {
      const element = ref.current;
      if (!isButton(element)) {
       if(element.tagName === "A") {
          setIsLink(true)
       }
     }
    }, []);

return {
   href: isLink & disabled ? undefined : htmlHref
}
```

**Comment by tom-sherman** [comment]
It's worth noting that there is potentially another expected behavior. Because `<a>` tags don't have a disabled property (and therefore no native disabled focus semantics) you may expect that clicking the anchor focuses the button.

Your solution looks good and easily achievable in userland. I'd vote to add this as a section to the Button docs instead of adding it as new default behavior.

**Comment by navin-moorthy** [comment]
Got Got !! Thanks for the clarification !!

I will just use the solution for my use-case.

**Comment by diegohaz** [comment]
I would say it's a bug that we're passing `disabled` to `a` elements.

We pass the `disabled` prop to all native tabbable elements from this list: https://github.com/reakit/reakit/blob/365f1583633e2c6ffbda4fb4ec46d74a7c63e9d8/packages/reakit/src/Tabbable/Tabbable.ts#L111-L121

https://github.com/reakit/reakit/blob/365f1583633e2c6ffbda4fb4ec46d74a7c63e9d8/packages/reakit/src/Tabbable/Tabbable.ts#L199

But this should be considered a bug: `<a>`, `<audio>` and `<video>` elements don't support the `disabled` attribute.

In this case, we shouldn't pass the `disabled` prop, and we must pass `tabIndex={-1}` to them so they're not tabbable. This would also fix your issue.

**Comment by navin-moorthy** [comment]
So, you mean this can be fixed in `Tabbable` by returning `tabIndex={-1}` to `<a>`, `<audio>` and `<video>` instead of `disabled`.

Am I correct ?

**Comment by diegohaz** [comment]
Haven't tested it, but in theory yes!

**Comment by diegohaz** [comment]
@navin-moorthy Do you want to work on this? Otherwise, I can do it later this week. :)

**Comment by navin-moorthy** [comment]
@diegohaz thanks, I will work on this on my free time.
