### ISSUE TITLE
Conflicting peer dependency, project not installable with npm v7

### ISSUE THREAD

**Issue by isaacs** [reakit/reakit#723]
## 🐛 Bug report

Conflicting `peerDependencies` that are not resolvable properly.

### Current behavior

npm v7 now automatically resolves `peerDependencies` so that packages can be fully and correctly installed in most cases, and incompatible behavior can be detected and fixed earlier in the development process.  However, in the current npm v7 beta, the error message it presents in unresolvable cases is not ideal.

I'm trying out an explanation implementation, and here's what I see for this repo:

```
While resolving
  eslint-config-react-app@5.2.1,
  could not add @typescript-eslint/eslint-plugin@2.34.0
  at node_modules/@typescript-eslint/eslint-plugin
  which satisfies the peer dependency on 2.x
    from eslint-config-react-app@5.2.1

This conflicts with @typescript-eslint/eslint-plugin@3.9.1
  at node_modules/@typescript-eslint/eslint-plugin
  which satisfies the dev dependency on 3.9.1
    from the root project

Fix the upstream dependency conflict, or run this command with
  --legacy-peer-deps
to accept an incorrect (and potentially broken) dependency resolution.
```

### Steps to reproduce the bug

Run `npm i -g npm@next-7`

Run `npm install` in this repository.

### Expected behavior

Should install properly, with peerDependencies that meet the stated dependency version range requirements.

### Possible solutions

1. Upgrade the version of `eslint-config-react-app` to a version that supports `@typescript-eslint/eslint-plugin` version `3.9.1`.
2. Downgrade the version of `@typescript-eslint/eslint-plugin` in `devDependencies` to a range that includes `2.34.0`, so that `eslint-config-react-app@5.2.1` can install properly.
3. Create a file in the root of this repo named `.npmrc` with the following line: `legacy-peer-deps = true` (not recommended!)

### Environment

Not relevant to this, except that `npm -v` reports `v7.0.0-beta.6`.

### Questions

1. Is this a legitimate dependency failure?  Ie, is something not working (or only working partly, or working in a brittle manner) that this is properly catching?
2. If it is a legitimate problem, would the error messaging pasted above help you know what to do to fix this problem?  If it is not helpful, is there some way you can suggest that it should be improved?  (For esthetics/clarity/completeness/etc.?)
3. If it is _not_ a legitimate problem, how would you suggest that it handle this error?  Use the stated prod dependency instead of the peer dep?  Ignore the peer dep entirely?  Have the peer dep override the stated prod dependency?

Thanks for any feedback you can provide!

**Comment by isaacs** [comment]
Excuse me, the root dependency on `eslint-config-react-app` is a `dev` dependency, not a `prod` dependency.  So, follow-up question: if it _was_ a prod dep, would that change any of your answers?

**Comment by isaacs** [comment]
Alternative styling, terser, maybe easier to scan?  Feedback very much welcome!

```
While resolving: eslint-config-react-app@5.2.1
Could not add: @typescript-eslint/eslint-plugin@2.34.0 at node_modules/@typescript-eslint/eslint-plugin
  for: peer dependency @typescript-eslint/eslint-plugin@"2.x"
  from: eslint-config-react-app@5.2.1

Conflict: @typescript-eslint/eslint-plugin@3.9.1 at node_modules/@typescript-eslint/eslint-plugin
  for: dev dependency @typescript-eslint/eslint-plugin@"3.9.1"
  from: the root project

Fix the upstream dependency conflict, or run this command with
  --legacy-peer-deps
to accept an incorrect (and potentially broken) dependency resolution.
```

**Comment by diegohaz** [comment]
> Is this a legitimate dependency failure? Ie, is something not working (or only working partly, or working in a brittle manner) that this is properly catching?

The project uses lerna and yarn workspaces. It works well. I remember seeing some errors when running `yarn upgrade-interactive`, but it doesn't always happen, and it's usually fixed by removing `yarn.lock` and letting yarn generate it again. I'm not sure if it's related though.

I just removed the `eslint-config-react-app` dependency as it seems that we're not using it anywhere.

> Run `npm i -g npm@next-7`
>
> Run `npm install` in this repository.

I get this error when I run `npm install` with npm 7:

```
Maximum call stack size exceeded
```

It looks like it's related to yarn. 

<details><summary>Complete logs</summary>

```
0 verbose cli [
0 verbose cli   '~/.nvm/versions/node/v12.18.3/bin/node',
0 verbose cli   '~/.nvm/versions/node/v12.18.3/bin/npm',
0 verbose cli   'install'
0 verbose cli ]
1 info using npm@7.0.0-beta.6
2 info using node@v12.18.3
3 timing config:load:defaults Completed in 1ms
4 timing config:load:file:~/.nvm/versions/node/v12.18.3/lib/node_modules/npm/npmrc Completed in 0ms
5 timing config:load:builtin Completed in 0ms
6 timing config:load:cli Completed in 1ms
7 timing config:load:env Completed in 0ms
8 timing config:load:file:~/proj/reakit/.npmrc Completed in 0ms
9 timing config:load:project Completed in 1ms
10 timing config:load:file:~/.npmrc Completed in 1ms
11 timing config:load:user Completed in 1ms
12 timing config:load:file:~/.nvm/versions/node/v12.18.3/etc/npmrc Completed in 0ms
13 timing config:load:global Completed in 0ms
14 timing config:load:cafile Completed in 0ms
15 timing config:load:validate Completed in 1ms
16 timing config:load:setEnvs Completed in 0ms
17 timing config:load Completed in 5ms
18 verbose npm-session bddcf2a98ff10c1e
19 timing npm:load Completed in 11ms
20 timing arborist:ctor Completed in 0ms
21 timing arborist:ctor Completed in 0ms
22 timing idealTree:init Completed in 4183ms
23 timing idealTree:userRequests Completed in 4ms
24 silly idealTree buildDeps
25 timing idealTree:#root Completed in 0ms
26 timing idealTree:buildDeps Completed in 2ms
27 timing idealTree:fixDepFlags Completed in 11ms
28 timing idealTree Completed in 4200ms
29 timing reify:loadTrees Completed in 4200ms
30 timing reify:diffTrees Completed in 27ms
31 silly reify moves {}
32 timing reify:retireShallow Completed in 1ms
33 timing reify:createSparse Completed in 0ms
34 timing reify:loadBundles Completed in 0ms
35 timing reify:unpack Completed in 7ms
36 timing reify:unretire Completed in 0ms
37 timing build:queue Completed in 0ms
38 timing build Completed in 0ms
39 timing reify:build Completed in 0ms
40 timing reify:trash Completed in 0ms
41 timing command:install Completed in 4336ms
42 verbose stack RangeError: Maximum call stack size exceeded
42 verbose stack     at YarnLock.addEntryFromNode (~/.nvm/versions/node/v12.18.3/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/yarn-lock.js:231:17)
42 verbose stack     at visit (~/.nvm/versions/node/v12.18.3/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/yarn-lock.js:171:27)
42 verbose stack     at visitNode (~/.nvm/versions/node/v12.18.3/lib/node_modules/npm/node_modules/treeverse/lib/breadth.js:26:25)
42 verbose stack     at next (~/.nvm/versions/node/v12.18.3/lib/node_modules/npm/node_modules/treeverse/lib/breadth.js:53:19)
42 verbose stack     at processKids (~/.nvm/versions/node/v12.18.3/lib/node_modules/npm/node_modules/treeverse/lib/breadth.js:48:12)
42 verbose stack     at kidNodes (~/.nvm/versions/node/v12.18.3/lib/node_modules/npm/node_modules/treeverse/lib/breadth.js:42:55)
42 verbose stack     at visitNode (~/.nvm/versions/node/v12.18.3/lib/node_modules/npm/node_modules/treeverse/lib/breadth.js:36:14)
42 verbose stack     at next (~/.nvm/versions/node/v12.18.3/lib/node_modules/npm/node_modules/treeverse/lib/breadth.js:53:19)
42 verbose stack     at processKids (~/.nvm/versions/node/v12.18.3/lib/node_modules/npm/node_modules/treeverse/lib/breadth.js:48:12)
42 verbose stack     at kidNodes (~/.nvm/versions/node/v12.18.3/lib/node_modules/npm/node_modules/treeverse/lib/breadth.js:42:55)
43 verbose cwd ~/proj/reakit
44 verbose Darwin 19.4.0
45 verbose argv "~/.nvm/versions/node/v12.18.3/bin/node" "~/.nvm/versions/node/v12.18.3/bin/npm" "install"
46 verbose node v12.18.3
47 verbose npm  v7.0.0-beta.6
48 error Maximum call stack size exceeded
49 verbose exit [ 1, undefined ]

```

</details>

**Comment by isaacs** [comment]
> I just removed the eslint-config-react-app dependency as it seems that we're not using it anywhere.

Cool, that seems like a valid problem to raise then!

> I get this error when I run npm install with npm 7:

Yes, yes, this was all just a very elaborate ploy to get you to find this bug for me 😈  Thanks, I'll dig into that one :)

I was running `npm install` on a different commit than the latest, so this is a great find.  I can reproduce on your master branch.

**Comment by isaacs** [comment]
https://github.com/npm/arborist/pull/118 <-- In the next npm v7 beta (not the one just shipped today), the `Maximum call stack size exceeded` and `cannot read property 'name' of null` errors will be fixed, the error reported will be actually helpful, and this project will be installable with `--force` (albeit with conflicting peer deps due to https://github.com/gatsbyjs/gatsby/pull/26689).

Thanks again for trying it and providing some feedback.  It was very helpful :)  If this issue is not providing you with any value, I have no problem with closing it.  If you'd prefer to leave it open until the peerDependencies can be brought out of a conflicted state, then that's understandable as well.
