### ISSUE TITLE
Migrate to GitHub discussions beta from Spectrum?

### ISSUE THREAD

**Issue by tom-sherman** [reakit/reakit#734]
It looks as though it's [possible to apply](https://github.community/t/can-one-apply-for-github-discussions-beta/121120/16) to join the GitHub Discussions beta.

Examples:

https://github.com/githubevents/satellite2020/discussions

https://github.com/vercel/vercel/discussions

**Comment by diegohaz** [comment]
Thanks Tom! I just commented on that thread requesting access.

**Comment by diegohaz** [comment]
YAAY!

https://github.com/reakit/reakit/discussions
