### ISSUE TITLE
[RFC] Link Component

### ISSUE THREAD

**Issue by navin-moorthy** [reakit/reakit#740]
## The Goal

Create a Link component to properly apply aria attributes and keyboard
navigation for the elements other than html `a` tag.

By Default, Link component renders an `a` tag which uses [`useClickable`](https://reakit.io/docs/clickable/) hook. As
per the nature of [`useClickable`](https://reakit.io/docs/clickable/), it doesn't change the native link `a` tags
behaviour.

## Key Features

- Applies `role: link` when the element is not a native link - `a` tag.
- Adds all [`useClickable`](https://reakit.io/docs/clickable/) features with keyboard navigation and
  `unstable_clickOnSpace: false`.
- Returns `{ target: "_blank", rel: "noopener noreferrer" }` when `isExternal`.

## Options

- `isExternal` - Returns `{ target: "_blank", rel: "noopener noreferrer" }`

## API

```jsx
<Link href="https://reakit.io/" isExternal>
  Link
</Link>
```

```jsx
<Link as="span" onClick="() => window.location.href = 'https://reakit.io/'">
  Custom Link
</Link>
```

## Complete Implementation & Preview

- Implementation Details -
  https://github.com/timelessco/renderless-components/blob/master/src/link/Link.ts
- Storybook -
  https://renderless-components.netlify.app/?path=/story/component-link-reakit--default

## Related WAI-ARIA resources

- https://www.w3.org/TR/wai-aria-practices-1.2/#link
- https://www.w3.org/TR/wai-aria-practices-1.2/examples/link/link.html
- https://www.w3.org/TR/wai-aria-1.2/#link

## Examples 

- With Next JS - https://codesandbox.io/s/nestjs-reakit-link-example-28893
- With React Router - https://codesandbox.io/s/react-router-link-example-38bb6?file=/example.js
- With Gatsby JS - https://codesandbox.io/s/gatsby-js-link-example-ver07

**Comment by StorytellerCZ** [comment]
Would be nice to take into account integration with popular React routing libraries like `react-router`.

**Comment by navin-moorthy** [comment]
> Would be nice to take into account integration with popular React routing libraries like `react-router`.

I will experiment with routing libraries and let know the results here. Thanks.

**Comment by tom-sherman** [comment]
This is a good article about "block links" which describe an issue with using `<a>` elements around a large block of content: https://css-tricks.com/block-links-are-a-pain-and-maybe-just-a-bad-idea/

**Comment by tom-sherman** [comment]
> Would be nice to take into account integration with popular React routing libraries like react-router.

@StorytellerCZ I believe this would be achievable with [composition patterns already available in Reakit](https://reakit.io/docs/composition/), no extra stuff needed for Link specifically.

**Comment by tom-sherman** [comment]
The one draw back I see with a custom link component when you start rendering them as non `<a>` elements is that you lose browser context menu behaviour - this is definitely not an ideal UX and good be a footgun for a lot of users.

**Comment by navin-moorthy** [comment]
> The one draw back I see with a custom link component when you start rendering them as non `<a>` elements is that you lose browser context menu behaviour - this is definitely not an ideal UX and good be a footgun for a lot of users.

You are correct, non `<a>` tag (i.e, elements with role="link") will not have the browser context & also will not accept any attributes specific to `<a>` tag.

As mentioned in the Note seciont here - https://w3c.github.io/aria-practices/#link

It is the responsibility of the authors to be aware of this when using a non native link element. We only provide them with the necessary aria attributes.

**Comment by navin-moorthy** [comment]
> > Would be nice to take into account integration with popular React routing libraries like react-router.
> 
> @StorytellerCZ I believe this would be achievable with [composition patterns already available in Reakit](https://reakit.io/docs/composition/), no extra stuff needed for Link specifically.

Exactly, here is an example with Next JS - https://codesandbox.io/s/nestjs-reakit-link-example-28893

**Comment by navin-moorthy** [comment]
> Would be nice to take into account integration with popular React routing libraries like `react-router`.

@StorytellerCZ Here is an example with `react-router` - https://codesandbox.io/s/react-router-link-example-38bb6?file=/example.js

**Comment by navin-moorthy** [comment]
> This is a good article about "block links" which describe an issue with using `<a>` elements around a large block of content: https://css-tricks.com/block-links-are-a-pain-and-maybe-just-a-bad-idea/
> 
> So I'd like a link component to solve this problem by:
> 
> * Nested links "just work"
> * "Block links" have good a11y
> * Can still select text inside of the link
> * Obviously all of the UX and WAI-ARIA practices of a regular link still apply

@tom-sherman Do you think, we should handle "Block Links" ourselves ?
Solution for `Block Links` requires some amount of CSS with `::before` which I am not sure how we can do with Reakit.

Chakra UI has a similar solution for this - [Link Box](https://github.com/chakra-ui/chakra-ui/blob/develop/packages/layout/src/link-box.tsx)
But `Can still select text inside of the link` is not solved.

**Comment by tom-sherman** [comment]
Other than handling block links, I don't see what value a Reakit link component can have over a regular a tag.

**Comment by navin-moorthy** [comment]
> Other than handling block links, I don't see what value a Reakit link component can have over a regular a tag.

Like [Button](https://github.com/reakit/reakit/blob/master/packages/reakit/src/Button/Button.ts) Component, this component will set `role` to `link` for non native link tag.

Also you can pass `isExternal` to handle the external links and pass the respective attributes ourselves.
```
<Link href="https://reakit.io/" isExternal>
      Reakit
    </Link>
```

As already found in the RFC description.

**Comment by tom-sherman** [comment]
Reakit solves browser inconsistencies regarding focus that occur with native buttons. I would personally say that without this feature there would be no point in a Reakit Button component. Because I'm not aware of any such issues with `<a>`s, I've never had a use case for this kind of Link component but that's not to say that other's do.

**Comment by navin-moorthy** [comment]
Okay I got it and yes this component doesn't do anything for the native <a> tag.

Like I said before
> this component will set `role` to `link` for non native link tag & onClick is handled by `Clickable`

```js
<span
    role="link"
    tabindex="0"
  >
    Reakit
  </span>
```

Kindly give me an idea on how we can solve the `Block Links` in Reakit
