### ISSUE TITLE
Show typescript autocompletion for `role` prop in components

### ISSUE THREAD

**Issue by anuraghazra** [reakit/reakit#741]
I was thinking that since we are showing warnings for invalid `role` prop in the Composite component we can also enforce the types as well, this way users would get autocompletion for the valid role values.

https://github.com/reakit/reakit/blob/6f6d1ad9177156cafa4adf9c987a43c79a1bbb90/packages/reakit/src/Composite/Composite.ts#L47-L58

We can change it so that users would get the autocompletion

```ts

const validCompositeRoles = [
  "combobox",
  "grid",
  "tablist",
  "listbox",
  "menu",
  "menubar",
  "toolbar",
  "radiogroup",
  "tree",
  "treegrid",
] as const;

type CompositeRoles = typeof validCompositeRoles[number];

export type CompositeOptions = TabbableOptions &
  Pick<
    Partial<CompositeStateReturn>,
    | "baseId"
    | "unstable_virtual"
    | "currentId"
    | "orientation"
    | "unstable_moves"
    | "wrap"
    | "groups"
  > &
  Pick<
    CompositeStateReturn,
    "items" | "setCurrentId" | "first" | "last" | "move"
  > & { role?: CompositeRoles };
```

![reakit-autocomplete](https://user-images.githubusercontent.com/35374649/93330979-3c80f800-f83d-11ea-98a8-852102346be2.png)

**Comment by diegohaz** [comment]
That's a great idea @anuraghazra! Thanks!

Would you like to work on that?

**Comment by anuraghazra** [comment]
Yes i can open a PR for this :)
