### ISSUE TITLE
RFC: Replace state spreading by single state prop

### ISSUE THREAD

**Issue by diegohaz** [reakit/reakit#744]
Currently, this is the API for all the components which depend on a state hook. You should spread the state object onto the components:

```jsx
const state = useDialogState();
<DialogDisclosure {...state} />
<Dialog {...state} />
```

In this issue, I'm proposing to change it so there's a single state prop:

```jsx
const state = useDialogState();
<DialogDisclosure state={state} />
<Dialog state={state} />
```

## The problem

The biggest problem in spreading the state onto the components is that it can easily cause name conflicts. For example, we can't use the name `value` on the state because it would conflict with the native `value` attribute:

```jsx
const state = useRadioState({ value: "orange" });
// 🔴 state.value will be overidden by the component's value prop
<RadioGroup {...state}>
  <Radio {...state} value="apple" />
  <Radio {...state} value="banana" />
  <Radio {...state} value="orange" />
</RadioGroup>
```

We solve it by using a different name:

```jsx
const state = useRadioState({ state: "orange" });
// state.state === "orange"
```

This is not a big deal as we have control over both the state and the component's props. We can name them so as to avoid those conflicts.

But consider the following example:

```jsx
const ComponentWithWrapProp = React.forwardRef(
  ({ wrap, ...props }, ref) => {...}
);

const state = useCompositeState();
// state.wrap === false
<Composite {...state} as={ComponentWithWrapProp} wrap />
```

In the example above, we're defining a custom component that expects to receive a `wrap` prop. But our `Composite` component also expects to receive that prop from the state.

This causes a series of unexpected effects. The user wants to pass `wrap` to `ComponentWithWrapProp`, but it's actually being consumed by `Composite` and not passed down to `ComponentWithWrapProp`. Also, they're unintentionally modifying `Composite`'s behavior because `wrap` is `false` by default.

This is not so easy to debug and can cause a lot of frustration.

But it can be worse. Let's see another example:

```jsx
const ComponentWithActiveIdProp = React.forwardRef(
  ({ activeId, ...props }, ref) => {...}
);

const state = useCompositeState();
<Composite {...state} as={ComponentWithActiveIdProp} activeId="id" />
```

This works fine because there's no `state.activeId` prop...

Yet.

What if we add `state.activeId` in the next *minor* version? This would totally break the user code.

I understand this is not a very common situation. I've never seen this myself even though I'm always looking at how people are using Reakit out there. But this will become a bigger problem as we encourage more and more the usage of the `as` prop (which I'm planning to do).

## This solution

Instead, components would rely on a single `state` prop. So, only this prop wouldn't be passed down and we could add as many properties there as we want.

As a side effect, we can also simplify the code in the library as we could more easily separate the state props from the rest:

```javascript
// This
const { state, ...rest } = props;
// Instead of this
const { baseId, currentId, down, first, <more state props>, ...rest } = props;
```

I also have a hypothesis that this would improve runtime performance, but this needs to be tested.

## `state` should be memoized

Because we would be passing `state` as a prop, the `state` object itself should be memoized in the state hook before being returned.

But this would also benefit people who are passing the `state` to React Context as they wouldn't neet to memoize the context value by themselves.

### v1

- Introduce `state={state}` API.
- Deprecate `{...state}` API.

Currently, we have 3 components that are expecting a `state` prop that is unrelated to this change: `Radio`, `RadioGroup` and `Checkbox`. We would have to accept both `state` props on them in v1.

### v2

- Remove `{...state}` API.

**Comment by tom-sherman** [comment]
> Currently, we have 3 components that are expecting a state prop that is unrelated to this change [...] We would have to accept both state props on them in v1.

Just to be clear I'm understanding, does this require duck typing the value?

**Comment by diegohaz** [comment]
> Just to be clear I'm understanding, does this require duck typing the value?

I imagine something like this:
```jsx
const value = state?.state || state;
```

`state.state` is not the best name, but we could change it to `value`/`checked` in v2.

**Comment by navin-moorthy** [comment]
RFC looks cool. 

But in my opinion, I think the general mindset would be to just spread the props from useHooks is easier than wanting them to use `state={state} ` in user land. 

Especially for the library, this API will be very useful. 

So, making move to this API in v2 means we won't be needing `useOptions` and `KEYS` to filter  anymore within the library?

**Comment by diegohaz** [comment]
> So, making move to this API in v2 means we won't be needing `useOptions` and `KEYS` to filter anymore within the library?

Yeah! I'm pretty sure we can get rid of `KEYS`, `__keys`, and all those things with this change.

I'm not sure about `useOptions` though. It's useful so we can get options at the beginning of the hooks.

For example, `useOptions` in `useCompositeItem` automatically generates an `id` prop. We wouldn't be able to access this prop without a separate `useOptions` hook:

```js
function useGridCell({ state, customProp, ...props }) {
  React.useEffect(() => {
    // do something with grid cell id, but the id will be generated only in useCompositeItem
    // and this function needs to be passed to useCompositeItem 🤷🏽‍♂️
  }, []);
  ...
  return useCompositeItem({ state, ...props });
}
```

This is fixed with the separate hook:

```js
function useGridCell({ state, customProp, ...props }) {
  const options = useCompositeItemOptions({ state, ...props });
  React.useEffect(() => {
    // do something with grid cell id
  }, [options.id]);
  ...
  return useCompositeItemProps({ state, ...options, ...props });
}
```

But there may be something I'm not seeing here.

**Comment by navin-moorthy** [comment]
Exactly, I understood your point. 

Thanks for the explanation. 

I forgot that we need `useOptions` to interact with other hooks options.

**Comment by david-szabo97** [comment]
RFC looks good to me! Object spreading is cool and handy.... but has its own cons. I'd definitely prefer `state={state`} over `{...state}`.

How do you feel about starting the implementation? I'd be happy to work on the PRs to make this happen - if you think this is ready to be implemented.

**Comment by diegohaz** [comment]
@david-szabo97 I'd say it should be implemented as soon as possible. But I still don't know how to implement it while maintaining backward compatibility and not messing up with the code, so I'm open to suggestions and PRs. Easier modules to start are [`Radio`](https://github.com/reakit/reakit/tree/3c7421d2e6a9054f72b9af87aa7e8f4e5813233d/packages/reakit/src/Radio), [`Checkbox`](https://github.com/reakit/reakit/tree/3c7421d2e6a9054f72b9af87aa7e8f4e5813233d/packages/reakit/src/Checkbox) and [`Disclosure`](https://github.com/reakit/reakit/tree/3c7421d2e6a9054f72b9af87aa7e8f4e5813233d/packages/reakit/src/Disclosure).

Anyway, I feel like the code will be so much cleaner in v2 with #744 and #745 as we'll be able to get rid of most complexity around [`keys`](https://github.com/reakit/reakit/blob/3c7421d2e6a9054f72b9af87aa7e8f4e5813233d/packages/reakit/src/Radio/Radio.ts#L71), [`createHook`](https://github.com/reakit/reakit/blob/3c7421d2e6a9054f72b9af87aa7e8f4e5813233d/packages/reakit/src/Radio/Radio.ts#L68), [`createComponent`](https://github.com/reakit/reakit/blob/3c7421d2e6a9054f72b9af87aa7e8f4e5813233d/packages/reakit/src/Radio/Radio.ts#L160) etc.

**Comment by david-szabo97** [comment]
Cool! I'll open a PR in the next days!
