### ISSUE TITLE
Infinite Toolbar/Composite rendering loop on Firefox

### ISSUE THREAD

**Issue by guillaumewuip** [reakit/reakit#747]
### Current behavior

I'm in the process of debugging a strange performance issue with Firefox in the old and big app I'm in charge of.

The app uses multiple `Toolbar`s inside a big component. This component is rendered in different ReactDOM tree (new React UIs attached to legacy views) at different moment.

First, there is only one `Toolbar`. Then, the user click somewhere and there is another one. Then three, etc.

After the second `Toolbar` is rendered, the performance issue starts. The `useToolbarState` hook of the second `Toolbar` keeps firing, rerendering the component hosting the toolbar. According to the React profiler, there is a new `items` prop passed to the toolbars components. It's like an infinite loop.

Seems to have appeared after the `2.0.0` update.

### Steps to reproduce the bug

I've not succeeded for now at reproducing the bug in a Codesandbox the cleanest way possible but it's on this Codesandbox : https://codesandbox.io/s/bug-reakit-toolbar-fujdb?file=/src/App.tsx

1. Open the sandbox with the app preview in the right panel
2. Open the Firefox console. You should see some `console.log({ toolbar })`. No infinite loop for now
3. Edit the `aria-label` from "test" to "test-111234" for example. In the console you should now see an infinite steam of `console.log({ toolbar })` after the hot loading has updated the component.

### Expected behavior

No infinite rendering loop.

### Possible solutions

I think I have a fix. Debugging Reakit locally I came across the `sortBasedOnDOMPosition` Composite helper.

https://github.com/reakit/reakit/blob/62cfafecb85521fd15c292a80af40da93adf705a/packages/reakit/src/Composite/__utils/sortBasedOnDOMPosition.ts#L8-L25

The `sort` function, and especially the way it sets `isOrderDifferent` to `true` seems to be the source of the issue. I think Firefox is not calling the sorting function consistently (`a` and `b` sometimes inverted ?) and that could make the function think the order of `copy` after sorting is different than `items` but it's not.

With the version of the function below the rendering issue seems to be fixed because we compute `isOrderDifferent` by comparing `items` and `copy`.

```ts
export function sortBasedOnDOMPosition<T extends Item>(items: T[]): T[] {
  const copy = items
    .map((item, index) => [index, item] as [number, T])
    .slice();

  copy.sort((a, b) => {
    const elementA = a[1].ref.current;
    const elementB = b[1].ref.current;

    if (!elementA || !elementB) return 0;

    // a before b
    if (isElementPreceding(elementA, elementB)) {
      // isOrderDifferent = true;
      return -1;
    }

    // a after b
    if (isElementFollowing(elementA, elementB)) {
      return 1;
    }

    return 0;
  });

  const isOrderDifferent = copy.reduce<boolean>(
    (localIsOrderDifferent: boolean, slot: [number, T]) => {
      const [index, newItem] = slot;

      const initialItem = items[index];

      return localIsOrderDifferent || newItem !== initialItem;
    }, false,
  );

  if (isOrderDifferent) {
    return copy.map(([_, item]) => item);
  }

  return items;
}
```

### Environment

Firefox 80.0.1. Not reproduced on Chrome.

Please, run the command below inside your project directory.
```sh
$ npx envinfo --system --binaries --browsers --npmPackages "{react*,reakit*}"

  System:
    OS: macOS 10.15.6
    CPU: (4) x64 Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz
    Memory: 875.79 MB / 16.00 GB
    Shell: 5.0.0 - /usr/local/bin/bash
  Binaries:
    Node: 12.18.1 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.5 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Brave Browser: 85.1.14.81
    Chrome: 85.0.4183.102
    Firefox: 80.0.1
    Safari: 14.0
  npmPackages:
    react: 16.13.1 => 16.13.1 
    react-dom: 16.13.1 => 16.13.1 
    react-spring: 8.0.27 => 8.0.27 
    react-test-renderer: 16.13.1 => 16.13.1 
```

What do you think of this issue ? Do you want me to open a PR with this `sortBasedOnDOMPosition` fix ?

**Comment by tom-sherman** [comment]
Your reproduction seems to rely on HMR, is that the case? Is it possible to repro without HMR, say in a production version of create-react-app?

**Comment by diegohaz** [comment]
Based on the implementation you provided, I think `reduce` is not needed (which is good, because it's super slow). We can set `isOrderDiffefent` inside the `sort` function by comparing `a` and `b` indexes. If `a` preceds `b`, `isOrderDifferent` will be `true` only if `indexA > indexB`, right?

Maybe something like this (didn't test)?

```js
if (isElementPreceding(elementA, elementB)) {
  if (indexA > indexB) {
    isOrderDifferent = true;
  }
  return -1;
}
if (indexB > indexA) {
  isOrderDifferent = true;
}
return 1;
```

**Comment by guillaumewuip** [comment]
@tom-sherman I'm not sure about HMR. It seems to be the cause of the bug for the sandbox but not for my app that doesn't have HMR. Haven't found a way to reproduce properly in a sandbox without HMR for now :/

@diegohaz I will test your implementation and post the result here

**Comment by guillaumewuip** [comment]
```ts
export function sortBasedOnDOMPosition<T extends Item>(items: T[]): T[] {
  const copy = items
    .map((item, index) => [index, item] as [number, T])
    .slice();

  let isOrderDifferent = false;

  copy.sort((a, b) => {
    console.log({a, b})

    const indexA = a[0];
    const elementA = a[1].ref.current;

    const indexB = b[0];
    const elementB = b[1].ref.current;

    if (!elementA || !elementB) return 0;

    // a before b
    if (isElementPreceding(elementA, elementB)) {
      if (indexA > indexB) {
        isOrderDifferent = true
      }
      return -1;
    }

    // a after b
    if (indexA < indexB) {
      isOrderDifferent = true
    }
    return 1;
  });

  if (isOrderDifferent) {
    return copy.map(([_, item]) => item);
  }

  return items;
}
```

seems to work well @diegohaz 👍 Do you want a PR ?

**Comment by diegohaz** [comment]
Awesome!

Sure! Thanks for catching this!
