### ISSUE TITLE
Click on menu,Screen scrolled upwards automatically

### ISSUE THREAD

**Issue by harshilparmar** [reakit/reakit#751]
## 🐛 Bug report
This is not a bug in library,but when I visited home page https://reakit.io and after first load of page clicking on menu button of `TabsModalMenu.js` and `TabsModalMenuMenu.js` ,it automatically scrolled upward.
### Steps to reproduce the bug
1. Open new tab
2. Go to reakit.io
3. Click on menu of two tabs mentioned above

### Possible solutions
I think we have to put `event.stopPropagation()`.I can't find code of that in this repo.

### Environment 
Browser : FireFox (81.0), Chrome (Version 85.0.4183.121)

![real](https://user-images.githubusercontent.com/45915468/94365824-8b5a4780-00f1-11eb-8481-8e79f4b37ca0.PNG)
![reakkit](https://user-images.githubusercontent.com/45915468/94365825-8e553800-00f1-11eb-96fc-afa6cc0f761d.PNG)

**Comment by diegohaz** [comment]
Thanks for reporting @harshilparmar! I can reproduce it. It's weird that it only happens on the home page. Not sure what's happening, but I remember it was working well the last time I used it.

This is the file that renders that part of the UI: https://github.com/reakit/reakit/blob/master/packages/website/src/components/HomePlayground.tsx

**Comment by harshilparmar** [comment]
@diegohaz ohh thanks,I will let you know If I find something.

**Comment by tom-sherman** [comment]
This is intermittent for me in Chrome on Windows, I haven't managed to repro at all in Firefox.

**Comment by navin-moorthy** [comment]
Like @tom-sherman said, buggy behaviour is intermittent in "Firefox/82.0"
Not reproducable after restarting the browser 😕 

I couldn't reproduce it in "Chrome/85.0.4183.121"

**Comment by TheSisb** [comment]
Browsers scroll to view the newly focused element. My wild guess is that the `transform: translate3d()` applied to the hidden menu is not updating before the focus is granted and so the browser jumps to where it previously was before opening. Could be a race where sometimes it jumps before updating and other times it updates correctly before focusing and jumping.

**Comment by diegohaz** [comment]
I can reproduce it on https://deploy-preview-694--reakit.netlify.app

But I can't on https://deploy-preview-693--reakit.netlify.app

So I believe it has something to do with these changes where we're calling `menu.move(null)` to focus on the menu container at the same time we call `menu.show()`:

https://github.com/reakit/reakit/blob/bf9a795921d07c4a39e7c8a9ca67c879441d69d2/packages/reakit/src/Menu/Menu.tsx#L43-L44

https://github.com/reakit/reakit/blob/bf9a795921d07c4a39e7c8a9ca67c879441d69d2/packages/reakit/src/Menu/MenuButton.ts#L148-L152

https://github.com/reakit/reakit/blob/bf9a795921d07c4a39e7c8a9ca67c879441d69d2/packages/reakit/src/Menu/MenuButton.ts#L181-L188

**Comment by harshilparmar** [comment]
@diegohaz  Perfect 😃 ,Can't reproduce on https://deploy-preview-693--reakit.netlify.app 👍

**Comment by devnaumov** [comment]
@diegohaz https://deploy-preview-693--reakit.netlify.app works well 👍

**Comment by diegohaz** [comment]
Has anyone been able to reproduce it in a context that's not the website home page? I still can't understand why it's happening there.

**Comment by devnaumov** [comment]
@diegohaz yes, I've found similiar behavior here, please check it out
https://github.com/dbeaver/cloudbeaver/blob/devel/webapp/packages/core-blocks/src/PropertiesTable/PropertyValueSelector.tsx#L87
[
![behaviorExample](https://user-images.githubusercontent.com/48489896/96375927-b4b44380-1184-11eb-8332-a166c69f6fa6.gif)
](url)

**Comment by diegohaz** [comment]
@devnaumov Oh, thanks! That's very helpful! I'll have a look at it.

**Comment by SiTaggart** [comment]
We see it in a few places where we use the Menu on our website https://paste.twilio.design

The left sidebar contact menu, and component page table of contents "ask a question" menu seemed to suffer the most, especially when you haven't scrolled the page yet.

As @TheSisb mentioned, the initial position of the menu is incorrectly calculated when it's not been invoked. It's way off screen and the browser tries to jump you to the newly focused thing, and then the position gets correctly set.
