### ISSUE TITLE
Modal dialog shifts content, but fixed parts stay in place

### ISSUE THREAD

**Issue by ezhikov** [reakit/reakit#754]
### Current behavior

When we open modal dialog there is padding applied to body to compensate missing scroll. In our case, we have header with `position: fixed` which doesn't shifts with the rest of content and it creates odd 17px  gap on the right. Sadly, we can't change this header markup and behavior since it's third party and used not only on our site, but on many others. It would be great if we had ability to disable scroll, but decide if we want to compensate it with padding or not

### Steps to reproduce the bug

1. Open sandbox: https://codesandbox.io/s/strange-minsky-9h0vu?file=/src/App.tsx
2. Press "Open modal dialog" button
3. See how red block aligned relative to rest of content

### Expected behavior

There should be no compensation of scroll or (preferably) it should be configurable

### Possible solutions

Prop could be added to configure `body-scroll-lock` in `usePreventBodyScroll` hook

### Environment

```sh
$ npx envinfo --system --binaries --browsers --npmPackages "{react*,reakit*}"

 System:
    OS: Linux 4.19 Ubuntu 20.04 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
    Memory: 11.09 GB / 12.37 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 12.18.3 - ~/.nodenv/versions/12/bin/node
    Yarn: 1.22.5 - /home/linuxbrew/.linuxbrew/bin/yarn
    npm: 6.14.7 - ~/.nodenv/versions/12/bin/npm
  Browsers:
    Edge : 85
  npmPackages:
    react: ^16.13.1 => 16.13.1
    react-dom: 16.13.1 => 16.13.1
    react-keyed-flatten-children: ^1.2.0 => 1.2.0
    react-redux: ^7.2.0 => 7.2.0
    reakit: ^1.1.2 => 1.1.2
```

**Comment by tom-sherman** [comment]
Slightly different solution; instead of having the ability to configure the padding, if reakit added a known attribute to the body along with the style eg. `data-reakit-scroll-lock`, could you use that to override the styles of the header container to counteract the padding?

**Comment by tom-sherman** [comment]
In fact, you should be able to accomplish on your end as a temporary workaround: https://codesandbox.io/s/elastic-dijkstra-y2hn9?file=/src/App.tsx

**Comment by ezhikov** [comment]
I did almost that as temporary workaround, but I have no guarantee that header won't change it's markup in the future, meaning that at some point in future it might break. I spoke to team responsible for that and they will consider adding API for such cases. If they will, this wouldn't be an issue anymore, but until then ability to prevent padding is more preferable.

I also thought about possibility to tell reakit that it's not modal and pass required attributes and make scroll blocking myself.

**Comment by tom-sherman** [comment]
> I also thought about possibility to tell reakit that it's not modal and pass required attributes and make scroll blocking myself.

That was going to be my next suggestion, it's something I've done to work around issues with the body-scroll-lock dependency that Reakit uses. There are conversations in #469 around solutions to this problem.

I think that may be your best option for now, then when Reakit exposes an API for scroll locking you can migrate over.

**Comment by ezhikov** [comment]
Since there is probable plans to replace `body-scroll-lock` with internal solution, we can possibly close this in favor of #469 ?

**Comment by tom-sherman** [comment]
I would personally keep this issue open as well if you don't mind as it describes a slightly different problem.
