### ISSUE TITLE
Icon svg button 

### ISSUE THREAD

**Issue by prbxr** [reakit/reakit#764]
I would like to request Icon svg  button 
Similar to 
https://chakra-ui.com/iconbutton

**Comment by tom-sherman** [comment]
I've marked this as a question as I don't believe that Reakit should provide a specific component for this. Reakit provides low level primitives and an `IconButton` can be easily accomplished in userland.

By the way, if you have general questions about how to use Reakit then you can ask in [GitHub discussions](https://github.com/reakit/reakit/discussions)
