### ISSUE TITLE
Treeview component

### ISSUE THREAD

**Issue by tom-sherman** [reakit/reakit#767]
### Motivation

I'm mainly opening this issue as a tracking issue as I'm pretty sure that I've read discussions of implementing a Treeview in Reakit.

### Example

https://www.w3.org/TR/wai-aria-practices-1.1/examples/treeview/treeview-2/treeview-2a.html

https://gist.github.com/diegohaz/c7855a2d96ec7faa27738bef6fa28867

Reakit API TBD

### Possible implementations

It would use Composite.

**Comment by tom-sherman** [comment]
@diegohaz Do you have anything to add here? Is this available to be worked on or have you started working on it?

**Comment by diegohaz** [comment]
Thanks for opening this issue, Tom. I haven't worked on anything related to this component besides the gist you linked. Also, the API on that gist depends on #744 and #745.

My initial idea for the current Reakit API can be found in this revision: https://gist.github.com/diegohaz/c7855a2d96ec7faa27738bef6fa28867/80345c63584aa4cbd7b5e61f13dbb29435164165

**Comment by diegohaz** [comment]
Current issue: #4059
