### ISSUE TITLE
Purgecss removing classes with data-enter

### ISSUE THREAD

**Issue by horaciosystem** [reakit/reakit#773]
### Motivation

Docs improvement.
Include tips to the docs helping developers solve problems related to the use of Reakit and PostCSS.

### Case
When using an animated Dialog, and styling it with CSS modules classes,

```js
useDialogState({ animated: true })
``` 
In order to enable animations, Reakit adds two attributes to Dialog component, **data-enter** and **data-leave**.

When using PostCSS with [purgecss](https://github.com/FullHuman/purgecss) the generated classes with these attributes are wiped out the from the production css files.

### Solution

Adding data attributes to purgecss whitelistPatterns. 
regex:
```whitelistPatterns: [/data-.*/]```

postcss.config.js
```js
module.exports = {
  plugins: [
    "tailwindcss",
    ],
    process.env.NODE_ENV === "production"
      ? [
          "@fullhuman/postcss-purgecss",
          {
            content: ["./src/**/*.js", "./pages/**/*.js"],
            defaultExtractor: (content) =>
              content.match(/[\w-/:]+(?<!:)/g) || [],
            whitelist: [
              "html",
              "body",
              "theme-light",
              "theme-dark",              
            ],
            whitelistPatterns: [/data-.*/],
          },
        ]
      : undefined,
  ],
}

```

Related:
https://github.com/FullHuman/purgecss/pull/279/files

**Comment by lluia** [comment]
I wonder what would be the best way to address this. 🤔 

I understand that the library's components often use `data-*` attributes to query elements in the DOM (cc. @diegohaz).

As an aside  I think it would be better if those would be named `data-reakit-*` to prevent integration issues with other code that might operate querying`data-` attributes in the DOM.

Maybe a new entry on the **"Guides"** section of the docs called "Integration" would help? 

<img width="120" alt="Screenshot 2021-02-10 at 16 12 27" src="https://user-images.githubusercontent.com/5938217/107529737-77544580-6bbb-11eb-8a7b-226b49101cd7.png" />

**Comment by diegohaz** [comment]
@lluia Yeah! We could definitely have an Integration section in the docs.

The `data-*` attributes prefixing has been discussed on #634. My opinion is that prefixing data attributes with `reakit` would be equivalent to prefixing component props as well. They're also part of the public API. And just like you can remap props so they don't conflict with other libraries, you can do with data attributes as demonstrated on #634. But I'm open to suggestions.
