### ISSUE TITLE
RFC: Group stories by components

### ISSUE THREAD

**Issue by david-szabo97** [reakit/reakit#774]
### Motivation

Right now the storybook has only one group that's called `Examples`. I think it would be better to have groups by component.

### Example

Provide an example for how this feature would be used.

#### Implementation 1
Change each examples' files default export to:

```js
{
  title: 'Name of the component/Name of the test',
  component: StoryComponent
}
```

Then we can change how the stories are loaded in `.storybook/main.js`:
```js
  stories: [
    `${__dirname}/../packages/reakit/src/**/__examples__/!(__tests__)/*.tsx`,
  ],
```

#### ~Implementation 2~ This doesn't work, misread the documentation
~Dynamically generate all the stories in the `stories.js`. We can load all the modules and use named exports: https://storybook.js.org/docs/react/writing-stories/introduction~

#### Implementation 3
Add `index.stories.ts` next to each example file which properly creates a story for that example.

Then we can change how the stories are loaded in `.storybook/main.js`:
```js
  stories: [
    `${__dirname}/../packages/reakit/src/**/__examples__/**/*.stories.tsx`,
  ],
```

Example how it would look like for `Button`

```js
import { Button } from "../Button";

export { default as AccessibleButton } from "./AccessibleButton";
export { default as ButtonAsDiv } from "./ButtonAsDiv";
export { default as ButtonAsLink } from "./ButtonAsLink";
export { default as ButtonWithTooltip } from "./ButtonWithTooltip";

export default {
  title: "Button",
  component: Button,
};
```

**Comment by tom-sherman** [comment]
I think that any change we make to accomplish this needs to preserve the idea of the examples just being modules that export some component tree. This is so that we can utilise them easily for other things that aren't storybook eg. E2E tests.

**Comment by david-szabo97** [comment]
> I think that any change we make to accomplish this needs to preserve the idea of the examples just being modules that export some component tree. This is so that we can utilise them easily for other things that aren't storybook eg. E2E tests.

Definitely. Implementation 1 is a breaking change, we could add one more property to the default export, something like `exampleComponent` (I don't know what it should be called, just made this up), then we could use that to access the example and use it in E2E or documentation.

Just added Implementation 3 which should be totally compatible with the system, but it adds one more step for creating examples. The `index.stories.ts` file would solely exist just to create a story in the storybook.

> Also while I'm in favour of grouping them more logically, I don't think by component is always the best approach. Many of the examples capture how multiple components interact with eachother so it doesn't make sense to me to group them by some arbitrary component in the example.

Makes sense, thanks for pointing that out. Implementation 3 would be perfect in our case. We could create the file and specify the `title`, `component` and `subcomponents` to make all of them easily findable and add them to custom groups.

**Comment by diegohaz** [comment]
[Stories used to be grouped by components](https://deploy-preview-718--reakit.netlify.app/storybook/?path=/story/button--button-with-tootltip), but then after upgrading Storybook to v6 in #719 we lost the ability to do that as Storybook stopped supporting our dynamic configuration.

**Old file**
https://github.com/reakit/reakit/blob/61dbb0250cd76567145f1f126a88b86e22165704/.storybook/preview.js#L1-L29

**New file**
https://github.com/reakit/reakit/blob/3ac8395575e25848a8f23fd38bab9678e97ba9a7/.storybook/stories.js#L1-L28

That said, what @tom-sherman said is important. Right now we're using the example files for stories and integration testing. But, in the future, we want to expand it to E2E tests and for the site code examples (the code playgrounds on each page), so they can't be specific to Storybook.

**Comment by david-szabo97** [comment]
Would you be OK with **Implementation 3**? It's more work since we need to create the files manually, but we get full control over how we present the stories. What do you think? In this implementation, we don't need to touch the example files so it would be fully compatible with everything we have now.

**Comment by diegohaz** [comment]
> Would you be OK with **Implementation 3**? It's more work since we need to create the files manually, but we get full control over how we present the stories. What do you think? In this implementation, we don't need to touch the example files so it would be fully compatible with everything we have now.

@david-szabo97 Yeah! Let's do that! :)
