### ISSUE TITLE
Peer deps: Add React 17

### ISSUE THREAD

**Issue by ricokahler** [reakit/reakit#776]
### Current behavior

With React 17 installed, there's a bunch of warnings like so:

```
reakit@1.1.0 requires a peer of react@^16.8.0 but none is installed.
``` 

reakit has react 16 as a peer dep. The new React 17 is very compatible is probably still compatible with reakit. I would assume it's fine changing this line (and similar):

https://github.com/reakit/reakit/blob/3ac8395575e25848a8f23fd38bab9678e97ba9a7/packages/reakit/package.json#L48-L49

to this:

```json
"react": "^16.8 || ^17"
```

### Steps to reproduce the bug

Ensure npm 6

```
mkdir test-react-17
cd test-react-17
npm init -y
npm i react react-dom
npm i reakit
```

![image](https://user-images.githubusercontent.com/10551026/97197113-a3ba9200-1783-11eb-9948-23e84a1c4887.png)

### Expected behavior

No peer dep warnings.

### Possible solutions

Use an or clause for peer deps (assuming it's compatible)

```json
"peerDependencies": {
  "react": "^16.8 || ^17"
}
```

### Environment

Please, run the command below inside your project directory.
```sh
$ npx envinfo --system --binaries --browsers --npmPackages "{react*,reakit*}"

npx: installed 1 in 0.88s

  System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 250.59 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.13.1 - /usr/local/bin/node
    Yarn: 1.22.0 - /usr/local/bin/yarn
    npm: 6.14.8 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 86.0.4240.111
    Edge: 86.0.622.51
    Firefox: 80.0.1
    Firefox Developer Edition: 73.0
    Safari: 14.0
  npmPackages:
    react: ^17.0.1 => 17.0.1 
    react-dom: ^17.0.1 => 17.0.1 
    reakit: ^1.2.5 => 1.2.5 
```

Related #723

**Comment by tom-sherman** [comment]
We should probably do a full upgrade to React 17 right? The test suite has been passing against it for a while now.

**Comment by diegohaz** [comment]
@tom-sherman Yeah! Peer dependencies should probably be `^16.8.0 || ^17.0.0`. But I guess we will need another of those github actions for React 16 🤔

What do you think?

**Comment by tom-sherman** [comment]
Yeah I think you're right, it should be a simple copy and paste of the [react-next](https://github.com/reakit/reakit/blob/master/.github/workflows/react-next.yml) workflow with a few tweaks.
