### ISSUE TITLE
Radio button onChange handler fires twice

### ISSUE THREAD

**Issue by max-winderbaum** [reakit/reakit#790]
### Current behavior

When you click on a radio button with an onChange handler, it fires twice: once for a click event and once for a change event.

### Steps to reproduce the bug

1. Open sandbox: https://codesandbox.io/s/react-playground-forked-lt85u?file=/index.js
2. Open the console
3. Click the Radio button
4. Watch two events fire

### Expected behavior

The onChange handler should fire once.

### Possible solutions

I'd look into not using the `onChange` handler [here](https://github.com/reakit/reakit/blob/57b1238e714bb4dda3984d62268313c180fcc6a8/packages/reakit/src/Radio/Radio.ts#L128) and instead making a separate handler for clicks

### Environment

Please, run the command below inside your project directory.
```sh
$ npx envinfo --system --binaries --browsers --npmPackages "{react*,reakit*}"

  System:
    OS: macOS 11.0.1
    CPU: (8) x64 VirtualApple @ 2.50GHz processor
    Memory: 119.90 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 10.23.0 - ~/.config/nvm/versions/node/v10.23.0/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.8 - ~/.config/nvm/versions/node/v10.23.0/bin/npm
  Browsers:
    Chrome Canary: 89.0.4335.0
    Safari: 14.0.1
  npmPackages:
    reakit-utils: ^0.13.1 => 0.13.1
```

**Comment by david-szabo97** [comment]
I think this is related to native radio vs non-native radio. See an example of non-native radio element: https://codesandbox.io/s/react-radio-non-native-vrsb3?file=/index.js

The change is only triggered once. Since we don't have a native `change` event. I think it would be safe to prevent `fireChange` in the `onClick` handler if `isNativeRadio`.
