### ISSUE TITLE
Combobox popover position is wrong when Combobox container is fixed/relative + minValueLength + input click

### ISSUE THREAD

**Issue by vvo** [reakit/reakit#808]
### Current behavior

When using the Combobox inside a container that is either fixed or relative, and using the minValueLength option: bad things happen. The positioning of the popover is wrong initially and once you validate an option will become OK.

(tested on chrome and safari latest, macOS bigsur)

### Steps to reproduce the bug

1. Open sandbox: https://codesandbox.io/s/zealous-sara-ljyyb?file=/src/App.tsx
2. **Click** on the input
3. Type "a"
4. Popover position is bad
5. Validate first result
6. Click again on the input
7. Popover position is good

**Demo:**
![Kapture 2020-12-09 at 00 11 22](https://user-images.githubusercontent.com/123822/101552417-2190d080-39b3-11eb-910b-a4975e28a342.gif)

**How it's made:**
I replicated the Combobox fetch example (https://github.com/reakit/reakit/tree/master/packages/reakit/src/Combobox/__examples__/ComboboxFetch) and added:
- two containers to demonstrate the issue
- minValueLength: 1

### Expected behavior

Popover position should be good even if minValueLength: 1 is used and the container is fixed/relative

### Possible solutions

As discussed on Twitter, because this only happens on click (if you tab to the input: it works!) this might be an issue with the click handler of the input doing some unexpected changes compared to tab.

As a workaround, instead of using the minValueLength option, for now I am using:

```js
      <ComboboxPopover
        {...combobox}
        style={{
          visibility:
            combobox.inputValue.length < 1 || matches.length === 0
              ? "hidden"
              : "visible",
        }}
      >
```

Which seems to be "fine" but most probably not very aria friendly.

### Environment

Please, run the command below inside your project directory.
```sh
$ npx envinfo --system --binaries --browsers --npmPackages "{react*,reakit*}"

  System:
    OS: macOS 11.0.1
    CPU: (4) x64 Intel(R) Core(TM) i7-6567U CPU @ 3.30GHz
    Memory: 51.84 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.20.0 - ~/.nvm/versions/node/v12.20.0/bin/node
    Yarn: 1.22.5 - ~/.yarn/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v12.20.0/bin/npm
  Browsers:
    Chrome: 87.0.4280.88
    Firefox: 73.0.1
    Safari: 14.0.1
  npmPackages:
    react: 17.0.1 => 17.0.1
    react-dom: 17.0.1 => 17.0.1
    react-hook-form: 6.12.2 => 6.12.2
    react-loading-skeleton: 2.1.1 => 2.1.1
    react-script-hook: 1.2.1 => 1.2.1
    react-select-search: 2.2.3 => 2.2.3
    react-transition-group: 4.4.1 => 4.4.1
    react-use: 15.3.4 => 15.3.4
    reakit: 1.3.1 => 1.3.1
```

**Comment by diegohaz** [comment]
Thanks @vvo!

I haven't tested it yet, but my guess is that we should check the input length before calling `options.show?.()` here: https://github.com/reakit/reakit/blob/96f5dd52704444862d16167db3c82fb89838e3ae/packages/reakit/src/Combobox/Combobox.ts#L226-L235
