### ISSUE TITLE
Menu abstracting with sub menus throws an error

### ISSUE THREAD

**Issue by ZachHaber** [reakit/reakit#839]
## 🐛 Bug report

I'm working following the 'abstracting API' example and extending that to make submenus easier

### Current behavior

I'm getting an error thrown when I open a sub menu and the hover back to the original menu.

The error is `Cannot read property 'current' of null` at `hoveringAnotherMenuItem` in `MenuItem.js`

```tsx
function hoveringAnotherMenuItem(
  event: React.MouseEvent<HTMLElement, MouseEvent>,
  items: MenuItemOptions["items"]
) {
  const nextElement = getMouseDestination(event);
  if (!nextElement) return false;
  return items?.some(
    (item) => item.ref.current && contains(item.ref.current, nextElement)
  );
}
```

The item in question when breakpointing at the exception shows the following properties (from the codesandbox provided):

```
$$typeof: Symbol(react.element)
key: null
props: {children: "Option 3"}
ref: null
type: "button"
_owner: FiberNode {tag: 0, key: null, stateNode: null, elementType: ƒ, type: ƒ, …}
_store: {validated: false}
_self: undefined
_source: undefined
__proto__: Object
```

### Steps to reproduce the bug

1. Open sandbox: https://codesandbox.io/s/reakit-menu-error-vkg3m
2. Open the menu
3. Hover over "Sub Menu" to open the sub menu
4. Hover over back to "Option 2"

### Expected behavior

It shouldn't throw an error and crash the application

### Possible solutions

I'm not sure why those sub items aren't getting a ref attached to them, but using `item.ref?.current &&` for that line would suffice to prevent crashes if not full expected behavior of that function.

### Environment

Please, run the command below inside your project directory.
```
npx envinfo --system --binaries --browsers --npmPackages "{react*,reakit*}"  

  System:
    OS: Windows 10 10.0.18362
    CPU: (12) x64 Intel(R) Xeon(R) E-2176M  CPU @ 2.70GHz
    Memory: 10.89 GB / 31.81 GB
  Binaries:
    Node: 14.15.0 - C:\nodejs\node.EXE
    npm: 6.14.8 - C:\nodejs\npm.CMD
  Browsers:
    Chrome: 83.0.4103.116
    Edge: Spartan (44.18362.449.0)
    Internet Explorer: 11.0.18362.1
  npmPackages:
    react: ^17.0.1 => 17.0.1
    react-collapsed: ^3.0.1 => 3.0.1
    react-dom: ^17.0.1 => 17.0.1
    react-dropzone: ^11.2.4 => 11.2.4
    react-is: ^16.13.1 => 16.13.1
    react-popper-tooltip: ^3.1.0 => 3.1.0
    react-test-renderer: ^16.13.1 => 16.13.1
    reakit: ^1.3.4 => 1.3.4
    reakit-utils: ^0.14.4 => 0.14.4
```

**Comment by diegohaz** [comment]
@ZachHaber the `items` prop on the sub menu is overwriting the `items` prop coming from the menu state. In this case, you should use a different prop name: https://codesandbox.io/s/reakit-menu-error-forked-mlt2o?file=/src/App.tsx

We should probably use another name on the docs too.

**Comment by ZachHaber** [comment]
That worked beautifully. Thank you!

For updating the docs to help others avoid that pitfall, would you like me to modify the abstracting example to enable sub menus akin to what I set up?
