### ISSUE TITLE
When Button is disabled, it sets style="pointer-events: none;"

### ISSUE THREAD

**Issue by smacintyre** [reakit/reakit#845]
### Current behaviour

Currently, when `Button` has `disabled={true}` set, it adds a style property to the element: `style="pointer-events: none;"` -- this overrides the cursor CSS set for the disabled state.

The current document says that Reakit elements are [unstyled by default,](https://reakit.io/docs/styling/#unstyled) but this is incorrect here.

### Steps to reproduce the bug

See: https://codesandbox.io/s/frosty-waterfall-uf4c8?file=/index.js

### Expected behavior

Reakit shouldn't set the `style` property on the button by default, as per the docs. 

### Possible solutions

- Stop setting the `style` property in the default setup when the button is disabled
- If some users depend on this functionality, pass a prop to optionally enable the current behaviour
- Alternately document when Reakit adds styles with the default config and document how to override this behaviour

### Environment

Please, run the command below inside your project directory.
```sh
$ npx envinfo --system --binaries --browsers --npmPackages "{react*,reakit*}"

  System:
    OS: Linux 5.4 Ubuntu 20.04.1 LTS (Focal Fossa)
    CPU: (16) x64 Intel(R) Xeon(R) CPU
    Memory: 862.39 MB / 62.81 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 14.16.0 - ~/.nvm/versions/node/v14.16.0/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v14.15.5/bin/yarn
    npm: 6.14.11 - ~/.nvm/versions/node/v14.16.0/bin/npm
  npmPackages:
    react: ^17.0.1 => 17.0.1 
    react-dom: ^17.0.1 => 17.0.1 
    react-hook-form: ^6.15.1 => 6.15.1 
    react-router: ^5.2.0 => 5.2.0 
    react-router-dom: ^5.2.0 => 5.2.0 
    react-scripts: ^4.0.0 => 4.0.2 
    react-select-event: ^5.1.0 => 5.1.0 
    reakit: ^1.3.5 => 1.3.5 
```

**Comment by diegohaz** [comment]
Thanks for bringing it up @smacintyre!

> Alternately document when Reakit adds styles with the default config and document how to override this behaviour

I'd say that's the best option. There are a few exceptions to the "unstyled" rule, but these styles are added only when a11y is affected. For example, `DisclosureContent` (and derived components like `Dialog`, `Popover` etc.) will add `display: none` when the element is hidden.

**Comment by smacintyre** [comment]
Thank you for the quick reply @diegohaz !

Yes, I guess I expect the `display: none` for `DisclosureContent`. But was a bit surprised by the style on the button. I'm using TailwindCSS for styling and spent a fair bit of time debugging why cursor wasn't changing before I noticed the style setting. :)

Is there a way to override setting that style currently? I'm evaluating Reakit for use in a project. We usually set `cursor: not-allowed;` ([tailwind class](https://tailwindcss.com/docs/cursor#not-allowed) `cursor-not-allowed`) for the disabled state of buttons to be explicit to the user. I think it's a better behaviour than `pointer-events: none;`.

**Comment by diegohaz** [comment]
The `pointer-events: none` style makes more sense when the `Button` component is not rendered as a button element. Since other elements don't support the `disabled` attribute, disabling pointer-events in CSS is the closest we can get. We keep this even when the component is rendered as a native button for consistency.

> Is there a way to override setting that style currently?

Yes! I think this is the easiest way:
```jsx
<Button style={{ pointerEvents: "initial" }} />
```

But you can also use [render props](https://reakit.io/docs/composition/#render-props) to override or omit anything.

**Comment by smacintyre** [comment]
@diegohaz  Thank you again for the quick reply. I've never tried to the whole render props thing before, but I gave it a try and it works! Thank you very much for your help! 

I tried the first example, of setting the `style` directly and that didn't work for me. 

I would suggest adding an example to the docs. Feel free to close this ticket if you wish. Thank you again!

**Comment by beeFlaherty** [comment]
I would second the request for an option to turn off all inline styles in components, and handle the state changes with classnames.  CSP would be easier to meet with no inline styles to work through.
