### ISSUE TITLE
Firefox: Links inside a Dialog can't be tabbed to

### ISSUE THREAD

**Issue by Kataract** [reakit/reakit#851]
### Current behavior

When `<a>`s are inside of a `<Dialog>`, I can't tab to them in Firefox.  It doesn't seem to matter whether they're plain anchor tags or something like a `<Link>` from React router.  In Chrome and Safari I don't see this issue at all.

### Steps to reproduce the bug

Sandbox: https://codesandbox.io/s/infallible-swirles-ye897

Firefox:
* Open dialog by either mouse or keyboard
* Attempt to tab through content
* Observe links are not highlighted, but buttons are

Other browsers:
* Open dialog by either mouse or keyboard
* Attempt to tab through content
* Observe both links and buttons are highlighted

### Expected behavior

All focusable content should be able to be tabbed to.

### Possible solutions

It's not clear to me if this is an issue because of portals or not - I didn't try without because we want to retain the focus trapping of the portal and I'm not very familiar with the internals of portals.

### Environment

Please, run the command below inside your project directory.
```sh
$ npx envinfo --system --binaries --browsers --npmPackages "{react*,reakit*}"

  System:
    OS: macOS 11.2.3
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 2.93 GB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.5.1 - ~/.nvm/versions/node/v15.5.1/bin/node
    Yarn: 2.4.0 - ~/.nvm/versions/node/v15.5.1/bin/yarn
    npm: 7.3.0 - ~/.nvm/versions/node/v15.5.1/bin/npm
  Browsers:
    Chrome: 89.0.4389.90
    Chrome Canary: 91.0.4456.0
    Firefox Developer Edition: 88.0
    Safari: 14.0.3
    Safari Technology Preview: 14.2

(I don't know why the packages section didn't work but we're using React 16.13.1 and Reakit 1.3.6)
```

**Comment by diegohaz** [comment]
Thanks for reporting it @Kataract!

I tested with Firefox 84 and 86 and couldn't reproduce the bug. Maybe it's something on the Firefox Developer Edition?

**Comment by Kataract** [comment]
Yeah I'm seeing now I didn't have the option enabled to tab normally. Sorry for the false report!
