### ISSUE TITLE
Clickable does not handle Space onClick if rendered as anchor

### ISSUE THREAD

**Issue by eddeee888** [reakit/reakit#864]
### Current behavior

In the docs, it mentions "Pressing Enter or Space triggers a click event on Clickable regardless of its rendered element." in the [Accessibility section](https://reakit.io/docs/clickable/#accessibility).

However, it seems like when rendered as an anchor, Clickable component does not handle the Space case correctly.

### Steps to reproduce the bug

Provide a repo or sandbox with the bug and describe the steps to reproduce it.

1. Open sandbox: https://codesandbox.io/s/practical-smoke-t8ewo?file=/index.js
2. The first Clickable is rendered as button ( named "Enter, Space and Clicking works" ) will trigger an alert on pressing enter, space and clicking. ( This is expected, I'm including it for comparison )
3. The second Clickable renders as an anchor ( named "Enter and Clicking works, Space does not work" ) will trigger an alert on pressing enter, clicking but not for the case of Space. This is the bug.

### Expected behavior

Clickable should handle the Space case for anchors as well - as mentioned in the doc

### Possible solutions

I haven't looked into the internals of Clickable but maybe an extra handler if it renders an anchor? :)

### Environment

Please, run the command below inside your project directory.
```sh
$ npx envinfo --system --binaries --browsers --npmPackages "{react*,reakit*}"
```

![Screen Shot 2021-04-27 at 12 29 26 pm](https://user-images.githubusercontent.com/33769523/116175730-3b5d6500-a754-11eb-853e-a04a14231b60.png)

^ That's from the attached code sandbox. Please let me know if that's not what we are asking for.

**Comment by diegohaz** [comment]
That's intended. Links shouldn't be activated with space. I guess we should update the docs to reflect that.

**Comment by eddeee888** [comment]
Thanks for confirming that @diegohaz!
