### ISSUE TITLE
Specify DOM node for Portal?

### ISSUE THREAD

**Issue by anderoonies** [reakit/reakit#868]
### Motivation

We run a React app in a non-React site, so it attaches to a non-`body` root element. I'm wondering if it's possible to specify the DOM node for a `Portal` to attach to in order to keep it within the root element. The biggest motivator is that we have some styles for the root that the children in the React app inherits from, so our workaround is likely just to specify the full style on the `Tooltip` etc.

### Example

```js
const tooltipState = useTooltipState({portalDomNodeIdentifier: 'root'}); 
```
...or anything else that composes from `Portal`

### Possible implementations

```ts
function getPortalMountNode(identifier: string | null) {
    if (canUseDOM) {
        const target = document.querySelector(identifier);
        if (target) {
            return target;
        }
        return document.body;
    }
    return null;
}

export function Portal({ children, portalDomNodeIdentifier }: PortalProps) {
    const context = React.useContext(PortalContext) || getPortalMountNode(portalDomNodeIdentifier);
    // ...
}
```

Let me know if there's a more straightforward way to solve this! For now just going to move forward with manually styling the Tooltip :)

**Comment by tkhquang** [comment]
Hi @anderoonies 

As the `PortalContext` is already exposed (https://github.com/reakit/reakit/pull/431), I think you can achieve what you're looking for with something like this: https://codesandbox.io/s/lucid-mendel-d66mn?file=/src/App.js
