### ISSUE TITLE
Checkbox should support boolean `value` prop, and not only `checked`

### ISSUE THREAD

**Issue by devagja** [reakit/reakit#874]
checkbox cannot be referenced, prop inputRef is missing

https://reakit.io/docs/checkbox/#main

```js
import { useController } from 'react-hook-form'
import { Checkbox  } from 'reakit/Checkbox'

function ControlledCheckbox ({ control, name }) {
  const {
    field: { ref, ...inputProps }
  } = useController({
    name,
    control,
    defaultValue: false
  })

  return <Checkbox {...inputProps} ref={ref} />// not working ref
}

export default ControlledCheckbox

```

**Comment by diegohaz** [comment]
`Checkbox` does support the `ref` prop. The custom `inputRef` prop doesn't exist though. Do you mean this?
```jsx
const { field: { inputRef, ...inputProps } } = useController(...);
<Checkbox {...inputProps} ref={inputRef} />;
```

**Comment by diegohaz** [comment]
Hmm, after some research, I can see that the `value` prop is not really a valid way to set the checkbox value, and `checked` should be used instead. So this is not really an issue. My comment (https://github.com/reakit/reakit/issues/874#issuecomment-849150390) describes the idiomatic way to do that.
