### ISSUE TITLE
update docs to indicate styled-components has 'forwardedAs' and we dont need to use render props

### ISSUE THREAD

**Issue by noahehall** [reakit/reakit#876]
[see styled-components docs for forwardedAs](https://styled-components.com/docs/api#forwardedas-prop)

would have saved 15 minutes by switching to geico

**Comment by manojkumar-ally** [comment]
Hi @diegohaz,

I want to pick this issue. If I am not wrong [this section css-in-js](https://github.com/reakit/reakit/blob/a211d94da9f3b683182568a56479b91afb1b85ae/docs/STYLING.md#css-in-js) needs to be updated.

**Current**
> When using libraries like styled-components, you'll not be able to use the Reakit [`as` prop](https://reakit.io/docs/composition/#as-prop) since styled components have their own built-in `as` prop which is not passed down to the underlying component. You can use [render props](https://reakit.io/docs/composition/#render-props) instead to achieve the same functionality

**New Draft**
> When using styled-components, you will have to use [`forwardedAs` prop](https://styled-components.com/docs/api#forwardedas-prop) instead of Reakit [`as` prop](https://reakit.io/docs/composition/#as-prop) since styled-components have their own built-in `as` prop. Otherwise, you can use [render props](https://reakit.io/docs/composition/#render-props) to achieve the same functionality

tried `forwardedAs` seems to work fine - [sandbox link](https://codesandbox.io/s/ecstatic-jackson-u4hgs?file=/index.js)

Let me know your thoughts on this draft, any changes you want to see

**Comment by diegohaz** [comment]
@manojkumar-ally That looks great!
