### ISSUE TITLE
Add "onClose" prop to DialogBackdrop

### ISSUE THREAD

**Issue by BrunoS3D** [reakit/reakit#877]
### Motivation

I'm using the `Dialog` component and keeping some useState inside it, however I have a function responsible for resetting the props value when closing the modal.

It would be very nice to have a prop to component `DialogBackdrop` that is called when the user clicks on the component or starts an interaction that will close the modal. Suggestion name: `onClose`

Another interesting feature would be the creation of a `closeMode` option for the `useDialogState` hook.

### Example

onClose prop:

```jsx
import { Portal } from "reakit/Portal";
import {
  useDialogState,
  Dialog,
  DialogDisclosure,
  DialogBackdrop,
} from "reakit/Dialog";

function Example() {
  const dialog = useDialogState();
  return (
    <>
      <DialogDisclosure {...dialog}>Open dialog</DialogDisclosure>
      <DialogBackdrop {...dialog} onClose={() => alert("Modal Closed!")}>
        <Dialog {...dialog} aria-label="Welcome">
          Welcome to Reakit!
        </Dialog>
      </DialogBackdrop>
    </>
  );
}
```

closeMode option:

```jsx
 // optional and the default value, keeps the Dialog element in the DOM
 const dialog = useDialogState({ closeMode: "hide" });

 // optional, remove the element from the DOM and clear its state
 const dialog = useDialogState({ closeMode: "destroy" });
```

**Comment by diegohaz** [comment]
Thanks for the suggestion @BrunoS3D!

This can be done in userland already: https://codesandbox.io/s/reakit-dialog-with-onclose-prop-o7jv1
