### ISSUE TITLE
Blur event closes dialog, can this be prevented?

### ISSUE THREAD

**Issue by everdimension** [reakit/reakit#881]
### Current behavior

I'm using a `Dialog` component. The inner component can open a third-party library which shows it's own overlay. When this overlay gets focused, the `Dialog` component closes itself, losing all state and basically crashing the flow.

### Expected behavior

The dialog doesn't get closed

### Possible solutions

The dialog should either not get closed on blur event or there should be an option provided to `useDialogState` hook to prevent this behavior

### Environment

Please, run the command below inside your project directory.
```sh
OS: macOS 11.2.3
react: 17.0.1
reakit: 1.2.5
```

**Comment by diegohaz** [comment]
I guess you can pass `hideOnClickOutside={false}` to the Dialog component to prevent this from happening. And implement a click handler on a backdrop element to close the dialog.
