### ISSUE TITLE
Menu

### ISSUE THREAD

**Issue by diegohaz** [reakit/reakit#90]
http://blueprintjs.com/docs/#core/components/menu
https://material-ui.com/demos/menus/
https://react.semantic-ui.com/collections/menu
http://adrianroselli.com/2017/10/dont-use-aria-menu-roles-for-site-nav.html
https://www.smashingmagazine.com/2017/11/building-accessible-menu-systems/
https://stackoverflow.com/questions/41141247/aria-role-menuitem-for-a-or-li

```jsx
<Menu>
  <Menu.Item>Item 1</Menu.Item>
  <Menu.Item>Item 2</Menu.Item>
  <Menu.Divider />
  <Menu.Item>Item 3</Menu.Item>
</Menu>
```

**Comment by enesTufekci** [comment]
Is there any one on that? otherwise I wanna dive into it.

**Comment by diegohaz** [comment]
You can take it, @enesTufekci. If you need any help, just ask. :)

**Comment by kevinwolfcr** [comment]
@enesTufekci are you still working on that? otherwise I can start working on it.

**Comment by enesTufekci** [comment]
@kevinwolfcr please go for it, i couldnt find time to do it.

**Comment by kevinwolfcr** [comment]
Ok, will start on it tonight.

**Comment by lluia** [comment]
I would like to have a try on this, @kevinwolfcr are you still on it? 

@diegohaz is there any preferred default layout for it? 

As per the links above, I see 2 patterns, the typical **horizontal menu**:
<img width="752" alt="captura de pantalla 2018-09-10 a las 21 39 46" src="https://user-images.githubusercontent.com/5938217/45309854-51d23600-b542-11e8-8b2b-512d05f49984.png">
( _which is not always friendly in small viewports_ )

and an **horizontal menu**, the one that material-ui uses:

<img width="157" alt="captura de pantalla 2018-09-10 a las 21 40 14" src="https://user-images.githubusercontent.com/5938217/45309911-7dedb700-b542-11e8-8ce6-0c5abd1f3615.png">

which plays well on small viewports but maybe is too concise on wide ones.

Would it make sense for it by default to render horizontally and _only_ if there's space available to do so horizontally? 🤔 📐

```jsx
// by default its layout is determined by available space
<Menu>
 ...
</Menu>

// force it to layout horizontally
<Menu layout='horizontal'>
 ...
</Menu>

// force it to layout vertically
<Menu layout='vertical'>
 ...
</Menu>
```

**Comment by diegohaz** [comment]
@lluia I think no one is on this right now, so feel free to take it. 😊

Regarding `vertical`/`horizontal`, we already have some patterns around it. [`Toolbar`](https://reakit.io/components/toolbar), for example, defaults to horizontal layout, but it has a `vertical` prop to change it.

[`Group`](https://reakit.io/components/group) does the same, but it has also a `verticalAt` prop, which turns on the vertical layout when the viewport reaches given width.

I think we could make `Menu` vertical by default and have `horizontal`/`horizontalAt` props to change its direction. I'm not sure if `horizontalAt` would be useful though. Maybe we can do it without that prop and add it when use cases show up.

**Comment by diegohaz** [comment]
Closing as this has been added in v1.
