### ISSUE TITLE
Tabs Component re-rendering unnecessarily

### ISSUE THREAD

**Issue by CMatias** [reakit/reakit#908]
### Current behavior

I'm trying to implement a keyframes animation that animates the tab's content. Since I don't want the animation to play on page load I'm using an effect to determine if the component has been mounted. However, for some reason, the Tabs component re-renders, effectively always triggering the animation. 

### Steps to reproduce the bug

1. Open sandbox: https://codesandbox.io/s/nice-sound-x1r8e?file=/index.js
3. See 3 console logs every time you refresh the sandbox

### Expected behavior

I would expect just only one console.log

**Comment by diegohaz** [comment]
That's expected. Internally, the tabs are registered to the state, which causes a re-render, and then the first tab is automatically selected, which causes another re-render.

But that's an implementation detail. Your code shouldn't rely on how many times the component re-renders. If you share your code with the actual animation and the issue, I can try to suggest a better solution.

**Comment by CMatias** [comment]
Hey @diegohaz, 

Thanks for the quick reply. I eventually figured out some props such as `items` or `panels` were only being set after.

Here's a simple sandbox that mimics want I want: https://codesandbox.io/s/reakit-tabs-rerender-forked-f8tyd

Ideally, the tab would only animate and show as red after the "first load", meaning it should only happen after a tab change.

**Comment by CMatias** [comment]
In the meantime I realised my approach was too naive. Going to follow your advice of not relying on re-renders.

**Comment by diegohaz** [comment]
That wouldn't work even if the tab components were rendered just once. The simple fact that you're setting a state in an effect will already trigger a re-render after the first render and set the `fade` class on the panels.

One way to achieve what you want is listening to the `selectedId` state and only update the class name if it has changed, ignoring the initial value. I made a fork of your sandbox with a simple example, but this could be improved: https://codesandbox.io/s/reakit-tab-animated-19nm1
