### ISSUE TITLE
Duplicate setState calls on keyboard changes to Radio

### ISSUE THREAD

**Issue by stokesman** [reakit/reakit#910]
### Current behavior
When passing in my own `setState` to `Radio` the result is that keyboarding to change the checked radio calls `setState` twice each change. Additionally, after keyboard use, even changes with the pointer cause two calls per change when they do not before keyboard use.

Initially, I encountered this while working on a PR for Gutenberg and thought it could be something in their composed version of `RadioGroup`. I made a sandbox with just Reakit and was able to reproduce it.

### Steps to reproduce the bug

1. Open https://codesandbox.io/s/reakit-radiogroup-repro-of-duplicate-setstate-calls-after-keyboarding-e3b4k?file=/index.js
2. See console
3. use pointer to change radios
4. use keyboard to change radios
5. repeat step 3
6. Observe the duplicate logs from steps 4 & 5.

### Expected behavior
Calls the custom `setState` a single time per change of checked radio.

### Possible solutions

Let me get back to you on that one. This is still just a potential bug after all. Maybe this is just "doing it wrong".

### Environment

Please, run the command below inside your project directory.

```
  System:
    OS: macOS Sierra 10.12.6
    CPU: (4) x64 Intel(R) Core(TM) i5-2435M CPU @ 2.40GHz
    Memory: 514.81 MB / 8.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.3.0 - ~/.nix-profile/bin/node
    Yarn: 1.22.4 - ~/.nix-profile/bin/yarn
    npm: 6.14.5 - ~/.nix-profile/bin/npm
  Browsers:
    Brave Browser: 92.1.28.105
    Chrome: 93.0.4577.82
    Firefox: 88.0.1
    Safari: 12.1.2
  npmPackages:
    react: 17.0.1 => 17.0.1 
    react-dom: 17.0.1 => 17.0.1 
    react-native: 0.64.0 => 0.64.0 
    react-native-url-polyfill: 1.1.2 => 1.1.2 
    react-test-renderer: 17.0.1 => 17.0.1
```
That's from my local machine in Gutenberg project. Reakit is in components package is: ^1.3.8

**Comment by diegohaz** [comment]
If `setState` is a pure function, there shouldn't be a problem if it gets called twice with the same arguments. If it's really a problem though, you should create the custom `setState` function with `useCallback`:
```js
const setState = useCallback((v) => {
  radio.setState(v);
}, [radio.setState]);
```

**Comment by stokesman** [comment]
Thanks! I was going to add that I found a stable/memoized function will not be called twice. Still, it seemed funny the difference between key versus pointer initiated changes.
