### ISSUE TITLE
<Future />

### ISSUE THREAD

**Issue by diegohaz** [reakit/reakit#94]
**Status**

- [x] Move to @reakit organization.
- [x] Change the package name to `reakit`.
- [x] Add a deprecate warning on `reas` package.
- [x] Launch new website.

Branch: [reakit](https://github.com/diegohaz/reas/tree/reakit)

---

I'm really impressed how this project, which started as something highly experimental, has evolved so much. And this is certainly due to the fact that so many people have believed on it, either collaborating directly or just testing it on their projects.

This project is one of the reasons I quit my job a few months ago. Improving it is my highest priority right now.

I'm opening this issue to tell you guys what I'm planning for Reas in the near future, to say thank you for collaborating on this project, and to invite you to participate in what's to come.

@Thomazella @Andarist @jyash97 @wordofchristian @joao-alberto @Thebigbignooby @BoyWithSilverWings @mgmgpyaesonewin @menor @nathanforce 

 # ReaKit

<p align="center"><br><br><img width="300" alt="logo" src="https://user-images.githubusercontent.com/3068563/41595744-4f9ad1b6-739e-11e8-9bb1-6d2c81785a0d.png"><br><br><br></p>

When I first designed Reas, its only focus was composability. `as` was the main method responsible for ensuring high composability, and every component was built around it. So, the name of the library was an obvious combination of "React" and "as".

Let me give you a brief example of what I mean by composability. Let's create some styled components:

```js
import { styled, Base, Button as BaseButton } from "reakit";

const Button = styled(BaseButton)`
  text-transform: uppercase;
  font-weight: 600;
`;

const ButtonRounded = styled(Button)`
  border-radius: 1.25em;
  padding: 0 1.375em;
`;

const ButtonPrimary = styled(Button)`
  background-color: #fc4577;
  border: none;
  color: white;
`;
```

Now, we can render each one separately:
```jsx
<Button>Button</Button>
```
<img height="40" alt="button" src="https://user-images.githubusercontent.com/3068563/41597628-5d9e2bb8-73a4-11e8-9730-eeb7df812bf6.png">

```jsx
<ButtonRounded>Rounded</ButtonRounded>
```
<img height="45" alt="button" src="https://user-images.githubusercontent.com/3068563/41597978-51a262d8-73a5-11e8-8326-2880a06a54dd.png">

```jsx
<ButtonPrimary>Primary</ButtonPrimary>
```
<img height="45" alt="button" src="https://user-images.githubusercontent.com/3068563/41597535-1af4a648-73a4-11e8-9e61-581a73d58c8b.png">

Finally, we can leverage composability and combine them:
```jsx
<ButtonPrimary as={ButtonRounded}>Primary + Rounded</ButtonPrimary>
```
<img height="45" alt="button" src="https://user-images.githubusercontent.com/3068563/41597562-305df458-73a4-11e8-9ced-97931ef1778c.png">

As the project evolved, it became more ambitious. Not only it needed to be composable, but also accessible, and a focus on interactivity was emerging with Containers. It turned out that calling it a "Toolkit" was more appropriate. 

And, as you have noticed, I like the obvious:

*React + Toolkit = **ReaKit***

> Keeping the tradition of #40, I also don't know how to pronounce it. 😆

Changing the repository name should be seamless. Commit history and everything will be kept. GitHub will automatically redirect `diegohaz/reas` to `diegohaz/reakit` and the latter to `reakit/reakit`.

Migrating to https://www.npmjs.com/package/reakit should be as easy as just replacing all instances of `reas` to `reakit` or creating an alias.

> Thanks to @brunomacf and @marco-souza from @nosebit for the npm package name.

The new website is being built in the [reakit](https://github.com/diegohaz/reas/tree/reakit) branch and should be done by the next few weeks. Here are some screenshots of it:

<p align="center">
<img width="75%" alt="desktop website" src="https://user-images.githubusercontent.com/3068563/41596878-20c92e06-73a2-11e8-8ca7-bef06585596a.png">
<img width="22%" alt="mobile website" src="https://user-images.githubusercontent.com/3068563/41596902-32d98640-73a2-11e8-8f9a-5c3018eae9e2.png">
</p>

The work on `master` will continue as normal during this time. Nothing will change.

If you like what you read and would like to follow or contribute to this future, join us on https://reakit.slack.com (message me your email address and I'll send you an invite).

Thank you, guys.

**Comment by Thomazella** [comment]
🚀💫🎉🎉 Great.

**Comment by jyash97** [comment]
Hey,
The new site looks **awesome**. **Reakit** sounds good. Would surely contribute.

Please send me an invite to `jyash97@gmail.com` .

**Comment by joao-alberto** [comment]
Awesome!

I'm glad to participate in this project and anxious to contribute more. 🤘

**Comment by renatorib** [comment]
🚀

**Comment by Andarist** [comment]
Do u plan any API changes (or additions)? Would love to see a draft of what you have in mind.

**Comment by nickisaacs** [comment]
I would like to contribute as well. This looks interesting

**Comment by tsiq-swyx** [comment]
hello! latecomer here. can i get an invite? (alternately, can you move to spectrum because slack sucks)
