### ISSUE TITLE
`npm run dev` is giving me this error

### ISSUE THREAD

**Issue by saideepesh000** [reakit/reakit#945]
### Current behavior

When I run `npm run dev`, I got this error on the terminal, couldn't able to figure why

![image](https://user-images.githubusercontent.com/43727167/145704493-29a203d6-ddc3-4a2b-9378-174f58da1758.png)

### Steps to reproduce the bug

1. clone project locally
2. cd project
3. npm i
4. npm run dev

### Expected behavior

local dev server should start as expected

**Comment by diegohaz** [comment]
Hi @saideepesh000!

Thanks for reporting it. It turns out that it wasn't working on Windows. It should be fixed now, but `npm run dev` should be run as administrator because it needs to create symlinks.
