### ISSUE TITLE
[v2] Allow modifications to the position and width of the ComboboxPopover component

### ISSUE THREAD

**Issue by mkarajohn** [reakit/reakit#975]
### Motivation

First of all, sorry of this is already implemented, there are currently no v2 docs, so I am going a little blind here.

What I would like is the option to modify the `translation` and `width` parameters of the `ComboboxPopover` component (I mean the outermost HTML element, the one with `role='presentation'`)

Right now it sets the width and translates the position of the list wrapper according to the position and width of the `Combobox` input element

![image](https://user-images.githubusercontent.com/3789226/148417527-3be829f4-b6ad-4ad9-8029-183ba20c4fa2.png)

What I would like to be able to achieve, without hacking around the calculated element CSS that are applied, is something like this: 

![image](https://user-images.githubusercontent.com/3789226/148417767-76bc11e8-4690-4524-9c71-9d7ca8808c9a.png)

 

### Possible implementations

A possible way to implement this would be to introduce a `anchorRef: HTMLElement | null` prop to the `ComboboxPopover` component so that whatever calculations it does right now based on the input element in order to position the list, it should do them based on the `anchorRef` HTML element.

Another `fullWidth: boolean` prop could also be introduced in order to allow the list to have a width that matches that of the `anchorRef`

**Comment by diegohaz** [comment]
@mkarajohn It's already possible. Do you have your example in a CodeSandbox or something?

**Comment by mkarajohn** [comment]
Hi @diegohaz !
No unfortunately I do not have public code for this. If you just tell me the props or point me to a source file, I will be able to figure it out :)
Thanks

**Comment by diegohaz** [comment]
You can use `PopoverAnchor`:

```jsx
import { PopoverAnchor } from "ariakit/popover";

<>
  <PopoverAnchor state={combobox}>
    <Combobox state={combobox} />
  </PopoverAnchor>
  <ComboboxPopover state={combobox}>
    ...
  </ComboboxPopover>
</>
```

The popover width should be manually set on the `ComboboxPopover` element (with inline style, class name etc.). If you want something more dynamic, you should be able to retrieve the anchor reference width using `combobox.anchorRef`. But we can also add a `sameWidth` prop to the library to make it easier.

**Comment by mkarajohn** [comment]
Thank you @diegohaz ! That works!

>But we can also add a sameWidth prop to the library to make it easier.

Um, I mean, sure, having the library do something for the user for little to no cost is always welcome! (I do think `fullWidth` better communicates the purpose, but maybe I am biased because that's what it's called in MaterialUI)

May I also suggest one more thing?  A `topOffset` for the popover :sweat_smile: . The anchor functionality works great, but it places the popover immediately below the anchor element. Some designs may require the popover to be a little lower, as is in my case. I know it can be done by hacking around the calculated `translate` value, but it's always better if there is a "native" way of doing things. 

BTW, are there any issues ht you are actively working for v2 that could use community PRs ?

Thanks

**Comment by diegohaz** [comment]
> May I also suggest one more thing? A `topOffset` for the popover 😅 . The anchor functionality works great, but it places the popover immediately below the anchor element. Some designs may require the popover to be a little lower, as is in my case. I know it can be done by hacking around the calculated `translate` value, with something like
> 
> ```css
> > [role='presentation'] {
>    top: <VALUE> !important;
> }
> ```
> 
> but it's always better if there is a "native" way of doing things.

You can do that with the `gutter` prop:

```jsx
useComboboxState({ gutter: 5 });
```

It's going to be more obvious when the documentation is out, but in the meantime, you can use the built-in JSDocs. Most components/props are already covered. But feel free to submit a PR if you see something that could be improved:
![Hovering over the gutter prop and displaying the JSDocs popup](https://user-images.githubusercontent.com/3068563/148617103-48a19b00-a547-42cf-af14-1b3b464ae7f6.png)

> BTW, are there any issues that you are actively working for v2 that could use community help/PRs ?

Yeah! We're currently working on the component examples. You'll find more info on #939.

**Comment by diegohaz** [comment]
> The popover width should be manually set on the `ComboboxPopover` element (with inline style, class name etc.). If you want something more dynamic, you should be able to retrieve the anchor reference width using `combobox.anchorRef`. But we can also add a `sameWidth` prop to the library to make it easier.

`sameWidth` should be available as a prop on the `usePopoverState` hook and derivates (like `useComboboxState`) on `v2.0.0-alpha.19` (still unreleased). Closing the issue for now. :)
