### ISSUE TITLE
Recursive Looping on Menus Causes Arrow navigation to not work

### ISSUE THREAD

**Issue by httpete** [reakit/reakit#990]
### Current behavior

I have been trying to use your Menu component to do a recursive menu system, where some items have submenus and some don't. It completely works with the mouse, but when I try to keyboard navigate, I can arrow down through the first menuItems, and then onto the first submenu. But then, I can't tab back and arrow my way back up.

Notice how I loop over the menuItems, and then use the as prop as your examples show to call my CAMenu again. 
What I can see in the html output, compared to your r[eference example](https://reakit.io/docs/menu/#submenu),  is that my submenu item doesn't have a tabindex on it, and it isn't shuffled to 0 / -1 like the example does. 

I am pretty sure it has something to do with the as= prop, and the forwardRef. If I do all MenuItems in the loop the keyboard behavior is fine. The minute I try to use the CAMenu in the as prop, it renders properly htmlwize, but the keyboard arrow is dead.

```

import { forwardRef, useRef } from 'react';
import { Menu, MenuButton, MenuItem, useMenuState } from 'reakit/Menu';

export type CAMenuProps = {
  menuItem: any;
};

// eslint-disable-next-line react/display-name
export const CAMenu = forwardRef(({ menuItem }: CAMenuProps, ref) => {
  const rkMenu = useMenuState();
  const orientation = 'top';
  const activeMenu = 'home';
  const thisRef = useRef();

  return (
    <>
      <MenuButton ref={ref} {...rkMenu}>
        {orientation == 'false' && <Icon iconName="home" ariaLabel="search" />}
        {menuItem.menuTitle}
      </MenuButton>
      <Menu
        ref={thisRef}
        {...rkMenu}
        arial-label={menuItem.menuTitle}>
        {
          //@ts-ignore
          menuItem?.menuItems?.map(item => {
            return (
              <MenuItem
                {...rkMenu}
                as={item?.menuItems?.length && CAMenu}
                key={item.menuTitle}
                menuItem={item?.menuItems?.length && item}>
                {item.menuTitle}
              </MenuItem>
            );
          })
        }
      </Menu>
    </>
  );
});
```

### Steps to reproduce the bug

1. Open sandbox: https://codesandbox.io/s/m4n32vjkoj
2. Remove any line
3. See console logs

### Expected behavior

I tried copying your MenuBar example and it does work fine, it has something to do with the recursion and refs.

### Possible solutions

I tried some of your unstable props, like the one that uses the aria-descendant virtual thing, to see if I wouldn't need this shuffling of tabindex behavior. Didn't work. You have some other unstable props, but I don't know what they do. Thank you.

**Comment by diegohaz** [comment]
Could you please create a reproduction on CodeSandbox?

**Comment by httpete** [comment]
@diegohaz  you are correct, it is my error. What I failed to do was spread the ...props onto the MenuButton. Once I did it lit up great. Possibly some warning or typing error would have helped me to determine this. Thank you. Looking forward to ariakit going live.

**Comment by diegohaz** [comment]
Nice! Yeah! We currently have warnings for the ref prop, but not for the other props.
